// Generated by utils/generate-programmatic-view-tags.mjs. Do not edit.
namespace AngularTs.Wasm;

public static partial class Tags
{
    /// <summary>Creates a <c>a</c> element.</summary>
    public static ProgrammaticViewChild A(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("a", propertiesJson, children);
    }

    /// <summary>Creates a <c>abbr</c> element.</summary>
    public static ProgrammaticViewChild Abbr(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("abbr", propertiesJson, children);
    }

    /// <summary>Creates a <c>address</c> element.</summary>
    public static ProgrammaticViewChild Address(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("address", propertiesJson, children);
    }

    /// <summary>Creates a <c>area</c> element.</summary>
    public static ProgrammaticViewChild Area(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("area", propertiesJson, children);
    }

    /// <summary>Creates a <c>article</c> element.</summary>
    public static ProgrammaticViewChild Article(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("article", propertiesJson, children);
    }

    /// <summary>Creates a <c>aside</c> element.</summary>
    public static ProgrammaticViewChild Aside(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("aside", propertiesJson, children);
    }

    /// <summary>Creates a <c>audio</c> element.</summary>
    public static ProgrammaticViewChild Audio(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("audio", propertiesJson, children);
    }

    /// <summary>Creates a <c>b</c> element.</summary>
    public static ProgrammaticViewChild B(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("b", propertiesJson, children);
    }

    /// <summary>Creates a <c>base</c> element.</summary>
    public static ProgrammaticViewChild Base(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("base", propertiesJson, children);
    }

    /// <summary>Creates a <c>bdi</c> element.</summary>
    public static ProgrammaticViewChild Bdi(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("bdi", propertiesJson, children);
    }

    /// <summary>Creates a <c>bdo</c> element.</summary>
    public static ProgrammaticViewChild Bdo(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("bdo", propertiesJson, children);
    }

    /// <summary>Creates a <c>blockquote</c> element.</summary>
    public static ProgrammaticViewChild Blockquote(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("blockquote", propertiesJson, children);
    }

    /// <summary>Creates a <c>body</c> element.</summary>
    public static ProgrammaticViewChild Body(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("body", propertiesJson, children);
    }

    /// <summary>Creates a <c>br</c> element.</summary>
    public static ProgrammaticViewChild Br(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("br", propertiesJson, children);
    }

    /// <summary>Creates a <c>button</c> element.</summary>
    public static ProgrammaticViewChild Button(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("button", propertiesJson, children);
    }

    /// <summary>Creates a <c>canvas</c> element.</summary>
    public static ProgrammaticViewChild Canvas(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("canvas", propertiesJson, children);
    }

    /// <summary>Creates a <c>caption</c> element.</summary>
    public static ProgrammaticViewChild Caption(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("caption", propertiesJson, children);
    }

    /// <summary>Creates a <c>cite</c> element.</summary>
    public static ProgrammaticViewChild Cite(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("cite", propertiesJson, children);
    }

    /// <summary>Creates a <c>code</c> element.</summary>
    public static ProgrammaticViewChild Code(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("code", propertiesJson, children);
    }

    /// <summary>Creates a <c>col</c> element.</summary>
    public static ProgrammaticViewChild Col(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("col", propertiesJson, children);
    }

    /// <summary>Creates a <c>colgroup</c> element.</summary>
    public static ProgrammaticViewChild Colgroup(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("colgroup", propertiesJson, children);
    }

    /// <summary>Creates a <c>data</c> element.</summary>
    public static ProgrammaticViewChild Data(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("data", propertiesJson, children);
    }

    /// <summary>Creates a <c>datalist</c> element.</summary>
    public static ProgrammaticViewChild Datalist(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("datalist", propertiesJson, children);
    }

    /// <summary>Creates a <c>dd</c> element.</summary>
    public static ProgrammaticViewChild Dd(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("dd", propertiesJson, children);
    }

    /// <summary>Creates a <c>del</c> element.</summary>
    public static ProgrammaticViewChild Del(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("del", propertiesJson, children);
    }

    /// <summary>Creates a <c>details</c> element.</summary>
    public static ProgrammaticViewChild Details(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("details", propertiesJson, children);
    }

    /// <summary>Creates a <c>dfn</c> element.</summary>
    public static ProgrammaticViewChild Dfn(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("dfn", propertiesJson, children);
    }

    /// <summary>Creates a <c>dialog</c> element.</summary>
    public static ProgrammaticViewChild Dialog(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("dialog", propertiesJson, children);
    }

    /// <summary>Creates a <c>div</c> element.</summary>
    public static ProgrammaticViewChild Div(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("div", propertiesJson, children);
    }

    /// <summary>Creates a <c>dl</c> element.</summary>
    public static ProgrammaticViewChild Dl(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("dl", propertiesJson, children);
    }

    /// <summary>Creates a <c>dt</c> element.</summary>
    public static ProgrammaticViewChild Dt(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("dt", propertiesJson, children);
    }

    /// <summary>Creates a <c>em</c> element.</summary>
    public static ProgrammaticViewChild Em(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("em", propertiesJson, children);
    }

    /// <summary>Creates a <c>embed</c> element.</summary>
    public static ProgrammaticViewChild Embed(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("embed", propertiesJson, children);
    }

    /// <summary>Creates a <c>fieldset</c> element.</summary>
    public static ProgrammaticViewChild Fieldset(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("fieldset", propertiesJson, children);
    }

    /// <summary>Creates a <c>figcaption</c> element.</summary>
    public static ProgrammaticViewChild Figcaption(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("figcaption", propertiesJson, children);
    }

    /// <summary>Creates a <c>figure</c> element.</summary>
    public static ProgrammaticViewChild Figure(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("figure", propertiesJson, children);
    }

    /// <summary>Creates a <c>footer</c> element.</summary>
    public static ProgrammaticViewChild Footer(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("footer", propertiesJson, children);
    }

    /// <summary>Creates a <c>form</c> element.</summary>
    public static ProgrammaticViewChild Form(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("form", propertiesJson, children);
    }

    /// <summary>Creates a <c>h1</c> element.</summary>
    public static ProgrammaticViewChild H1(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("h1", propertiesJson, children);
    }

    /// <summary>Creates a <c>h2</c> element.</summary>
    public static ProgrammaticViewChild H2(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("h2", propertiesJson, children);
    }

    /// <summary>Creates a <c>h3</c> element.</summary>
    public static ProgrammaticViewChild H3(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("h3", propertiesJson, children);
    }

    /// <summary>Creates a <c>h4</c> element.</summary>
    public static ProgrammaticViewChild H4(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("h4", propertiesJson, children);
    }

    /// <summary>Creates a <c>h5</c> element.</summary>
    public static ProgrammaticViewChild H5(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("h5", propertiesJson, children);
    }

    /// <summary>Creates a <c>h6</c> element.</summary>
    public static ProgrammaticViewChild H6(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("h6", propertiesJson, children);
    }

    /// <summary>Creates a <c>head</c> element.</summary>
    public static ProgrammaticViewChild Head(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("head", propertiesJson, children);
    }

    /// <summary>Creates a <c>header</c> element.</summary>
    public static ProgrammaticViewChild Header(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("header", propertiesJson, children);
    }

    /// <summary>Creates a <c>hgroup</c> element.</summary>
    public static ProgrammaticViewChild Hgroup(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("hgroup", propertiesJson, children);
    }

    /// <summary>Creates a <c>hr</c> element.</summary>
    public static ProgrammaticViewChild Hr(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("hr", propertiesJson, children);
    }

    /// <summary>Creates a <c>html</c> element.</summary>
    public static ProgrammaticViewChild Html(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("html", propertiesJson, children);
    }

    /// <summary>Creates a <c>i</c> element.</summary>
    public static ProgrammaticViewChild I(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("i", propertiesJson, children);
    }

    /// <summary>Creates a <c>iframe</c> element.</summary>
    public static ProgrammaticViewChild Iframe(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("iframe", propertiesJson, children);
    }

    /// <summary>Creates a <c>img</c> element.</summary>
    public static ProgrammaticViewChild Img(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("img", propertiesJson, children);
    }

    /// <summary>Creates a <c>input</c> element.</summary>
    public static ProgrammaticViewChild Input(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("input", propertiesJson, children);
    }

    /// <summary>Creates a <c>ins</c> element.</summary>
    public static ProgrammaticViewChild Ins(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("ins", propertiesJson, children);
    }

    /// <summary>Creates a <c>kbd</c> element.</summary>
    public static ProgrammaticViewChild Kbd(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("kbd", propertiesJson, children);
    }

    /// <summary>Creates a <c>label</c> element.</summary>
    public static ProgrammaticViewChild Label(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("label", propertiesJson, children);
    }

    /// <summary>Creates a <c>legend</c> element.</summary>
    public static ProgrammaticViewChild Legend(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("legend", propertiesJson, children);
    }

    /// <summary>Creates a <c>li</c> element.</summary>
    public static ProgrammaticViewChild Li(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("li", propertiesJson, children);
    }

    /// <summary>Creates a <c>link</c> element.</summary>
    public static ProgrammaticViewChild Link(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("link", propertiesJson, children);
    }

    /// <summary>Creates a <c>main</c> element.</summary>
    public static ProgrammaticViewChild Main(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("main", propertiesJson, children);
    }

    /// <summary>Creates a <c>map</c> element.</summary>
    public static ProgrammaticViewChild Map(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("map", propertiesJson, children);
    }

    /// <summary>Creates a <c>mark</c> element.</summary>
    public static ProgrammaticViewChild Mark(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("mark", propertiesJson, children);
    }

    /// <summary>Creates a <c>menu</c> element.</summary>
    public static ProgrammaticViewChild Menu(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("menu", propertiesJson, children);
    }

    /// <summary>Creates a <c>meta</c> element.</summary>
    public static ProgrammaticViewChild Meta(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("meta", propertiesJson, children);
    }

    /// <summary>Creates a <c>meter</c> element.</summary>
    public static ProgrammaticViewChild Meter(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("meter", propertiesJson, children);
    }

    /// <summary>Creates a <c>nav</c> element.</summary>
    public static ProgrammaticViewChild Nav(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("nav", propertiesJson, children);
    }

    /// <summary>Creates a <c>noscript</c> element.</summary>
    public static ProgrammaticViewChild Noscript(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("noscript", propertiesJson, children);
    }

    /// <summary>Creates a <c>object</c> element.</summary>
    public static ProgrammaticViewChild Object(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("object", propertiesJson, children);
    }

    /// <summary>Creates a <c>ol</c> element.</summary>
    public static ProgrammaticViewChild Ol(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("ol", propertiesJson, children);
    }

    /// <summary>Creates a <c>optgroup</c> element.</summary>
    public static ProgrammaticViewChild Optgroup(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("optgroup", propertiesJson, children);
    }

    /// <summary>Creates a <c>option</c> element.</summary>
    public static ProgrammaticViewChild Option(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("option", propertiesJson, children);
    }

    /// <summary>Creates a <c>output</c> element.</summary>
    public static ProgrammaticViewChild Output(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("output", propertiesJson, children);
    }

    /// <summary>Creates a <c>p</c> element.</summary>
    public static ProgrammaticViewChild P(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("p", propertiesJson, children);
    }

    /// <summary>Creates a <c>picture</c> element.</summary>
    public static ProgrammaticViewChild Picture(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("picture", propertiesJson, children);
    }

    /// <summary>Creates a <c>pre</c> element.</summary>
    public static ProgrammaticViewChild Pre(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("pre", propertiesJson, children);
    }

    /// <summary>Creates a <c>progress</c> element.</summary>
    public static ProgrammaticViewChild Progress(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("progress", propertiesJson, children);
    }

    /// <summary>Creates a <c>q</c> element.</summary>
    public static ProgrammaticViewChild Q(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("q", propertiesJson, children);
    }

    /// <summary>Creates a <c>rp</c> element.</summary>
    public static ProgrammaticViewChild Rp(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("rp", propertiesJson, children);
    }

    /// <summary>Creates a <c>rt</c> element.</summary>
    public static ProgrammaticViewChild Rt(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("rt", propertiesJson, children);
    }

    /// <summary>Creates a <c>ruby</c> element.</summary>
    public static ProgrammaticViewChild Ruby(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("ruby", propertiesJson, children);
    }

    /// <summary>Creates a <c>s</c> element.</summary>
    public static ProgrammaticViewChild S(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("s", propertiesJson, children);
    }

    /// <summary>Creates a <c>samp</c> element.</summary>
    public static ProgrammaticViewChild Samp(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("samp", propertiesJson, children);
    }

    /// <summary>Creates a <c>script</c> element.</summary>
    public static ProgrammaticViewChild Script(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("script", propertiesJson, children);
    }

    /// <summary>Creates a <c>search</c> element.</summary>
    public static ProgrammaticViewChild Search(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("search", propertiesJson, children);
    }

    /// <summary>Creates a <c>section</c> element.</summary>
    public static ProgrammaticViewChild Section(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("section", propertiesJson, children);
    }

    /// <summary>Creates a <c>select</c> element.</summary>
    public static ProgrammaticViewChild Select(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("select", propertiesJson, children);
    }

    /// <summary>Creates a <c>slot</c> element.</summary>
    public static ProgrammaticViewChild Slot(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("slot", propertiesJson, children);
    }

    /// <summary>Creates a <c>small</c> element.</summary>
    public static ProgrammaticViewChild Small(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("small", propertiesJson, children);
    }

    /// <summary>Creates a <c>source</c> element.</summary>
    public static ProgrammaticViewChild Source(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("source", propertiesJson, children);
    }

    /// <summary>Creates a <c>span</c> element.</summary>
    public static ProgrammaticViewChild Span(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("span", propertiesJson, children);
    }

    /// <summary>Creates a <c>strong</c> element.</summary>
    public static ProgrammaticViewChild Strong(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("strong", propertiesJson, children);
    }

    /// <summary>Creates a <c>style</c> element.</summary>
    public static ProgrammaticViewChild Style(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("style", propertiesJson, children);
    }

    /// <summary>Creates a <c>sub</c> element.</summary>
    public static ProgrammaticViewChild Sub(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("sub", propertiesJson, children);
    }

    /// <summary>Creates a <c>summary</c> element.</summary>
    public static ProgrammaticViewChild Summary(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("summary", propertiesJson, children);
    }

    /// <summary>Creates a <c>sup</c> element.</summary>
    public static ProgrammaticViewChild Sup(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("sup", propertiesJson, children);
    }

    /// <summary>Creates a <c>table</c> element.</summary>
    public static ProgrammaticViewChild Table(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("table", propertiesJson, children);
    }

    /// <summary>Creates a <c>tbody</c> element.</summary>
    public static ProgrammaticViewChild Tbody(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("tbody", propertiesJson, children);
    }

    /// <summary>Creates a <c>td</c> element.</summary>
    public static ProgrammaticViewChild Td(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("td", propertiesJson, children);
    }

    /// <summary>Creates a <c>template</c> element.</summary>
    public static ProgrammaticViewChild Template(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("template", propertiesJson, children);
    }

    /// <summary>Creates a <c>textarea</c> element.</summary>
    public static ProgrammaticViewChild Textarea(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("textarea", propertiesJson, children);
    }

    /// <summary>Creates a <c>tfoot</c> element.</summary>
    public static ProgrammaticViewChild Tfoot(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("tfoot", propertiesJson, children);
    }

    /// <summary>Creates a <c>th</c> element.</summary>
    public static ProgrammaticViewChild Th(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("th", propertiesJson, children);
    }

    /// <summary>Creates a <c>thead</c> element.</summary>
    public static ProgrammaticViewChild Thead(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("thead", propertiesJson, children);
    }

    /// <summary>Creates a <c>time</c> element.</summary>
    public static ProgrammaticViewChild Time(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("time", propertiesJson, children);
    }

    /// <summary>Creates a <c>title</c> element.</summary>
    public static ProgrammaticViewChild Title(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("title", propertiesJson, children);
    }

    /// <summary>Creates a <c>tr</c> element.</summary>
    public static ProgrammaticViewChild Tr(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("tr", propertiesJson, children);
    }

    /// <summary>Creates a <c>track</c> element.</summary>
    public static ProgrammaticViewChild Track(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("track", propertiesJson, children);
    }

    /// <summary>Creates a <c>u</c> element.</summary>
    public static ProgrammaticViewChild U(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("u", propertiesJson, children);
    }

    /// <summary>Creates a <c>ul</c> element.</summary>
    public static ProgrammaticViewChild Ul(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("ul", propertiesJson, children);
    }

    /// <summary>Creates a <c>var</c> element.</summary>
    public static ProgrammaticViewChild Var(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("var", propertiesJson, children);
    }

    /// <summary>Creates a <c>video</c> element.</summary>
    public static ProgrammaticViewChild Video(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("video", propertiesJson, children);
    }

    /// <summary>Creates a <c>wbr</c> element.</summary>
    public static ProgrammaticViewChild Wbr(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("wbr", propertiesJson, children);
    }

    /// <summary>Creates a <c>acronym</c> element.</summary>
    public static ProgrammaticViewChild Acronym(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("acronym", propertiesJson, children);
    }

    /// <summary>Creates a <c>applet</c> element.</summary>
    public static ProgrammaticViewChild Applet(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("applet", propertiesJson, children);
    }

    /// <summary>Creates a <c>basefont</c> element.</summary>
    public static ProgrammaticViewChild Basefont(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("basefont", propertiesJson, children);
    }

    /// <summary>Creates a <c>bgsound</c> element.</summary>
    public static ProgrammaticViewChild Bgsound(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("bgsound", propertiesJson, children);
    }

    /// <summary>Creates a <c>big</c> element.</summary>
    public static ProgrammaticViewChild Big(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("big", propertiesJson, children);
    }

    /// <summary>Creates a <c>blink</c> element.</summary>
    public static ProgrammaticViewChild Blink(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("blink", propertiesJson, children);
    }

    /// <summary>Creates a <c>center</c> element.</summary>
    public static ProgrammaticViewChild Center(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("center", propertiesJson, children);
    }

    /// <summary>Creates a <c>dir</c> element.</summary>
    public static ProgrammaticViewChild Dir(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("dir", propertiesJson, children);
    }

    /// <summary>Creates a <c>font</c> element.</summary>
    public static ProgrammaticViewChild Font(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("font", propertiesJson, children);
    }

    /// <summary>Creates a <c>frame</c> element.</summary>
    public static ProgrammaticViewChild Frame(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("frame", propertiesJson, children);
    }

    /// <summary>Creates a <c>frameset</c> element.</summary>
    public static ProgrammaticViewChild Frameset(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("frameset", propertiesJson, children);
    }

    /// <summary>Creates a <c>isindex</c> element.</summary>
    public static ProgrammaticViewChild Isindex(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("isindex", propertiesJson, children);
    }

    /// <summary>Creates a <c>keygen</c> element.</summary>
    public static ProgrammaticViewChild Keygen(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("keygen", propertiesJson, children);
    }

    /// <summary>Creates a <c>listing</c> element.</summary>
    public static ProgrammaticViewChild Listing(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("listing", propertiesJson, children);
    }

    /// <summary>Creates a <c>marquee</c> element.</summary>
    public static ProgrammaticViewChild Marquee(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("marquee", propertiesJson, children);
    }

    /// <summary>Creates a <c>menuitem</c> element.</summary>
    public static ProgrammaticViewChild Menuitem(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("menuitem", propertiesJson, children);
    }

    /// <summary>Creates a <c>multicol</c> element.</summary>
    public static ProgrammaticViewChild Multicol(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("multicol", propertiesJson, children);
    }

    /// <summary>Creates a <c>nextid</c> element.</summary>
    public static ProgrammaticViewChild Nextid(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("nextid", propertiesJson, children);
    }

    /// <summary>Creates a <c>nobr</c> element.</summary>
    public static ProgrammaticViewChild Nobr(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("nobr", propertiesJson, children);
    }

    /// <summary>Creates a <c>noembed</c> element.</summary>
    public static ProgrammaticViewChild Noembed(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("noembed", propertiesJson, children);
    }

    /// <summary>Creates a <c>noframes</c> element.</summary>
    public static ProgrammaticViewChild Noframes(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("noframes", propertiesJson, children);
    }

    /// <summary>Creates a <c>param</c> element.</summary>
    public static ProgrammaticViewChild Param(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("param", propertiesJson, children);
    }

    /// <summary>Creates a <c>plaintext</c> element.</summary>
    public static ProgrammaticViewChild Plaintext(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("plaintext", propertiesJson, children);
    }

    /// <summary>Creates a <c>rb</c> element.</summary>
    public static ProgrammaticViewChild Rb(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("rb", propertiesJson, children);
    }

    /// <summary>Creates a <c>rtc</c> element.</summary>
    public static ProgrammaticViewChild Rtc(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("rtc", propertiesJson, children);
    }

    /// <summary>Creates a <c>spacer</c> element.</summary>
    public static ProgrammaticViewChild Spacer(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("spacer", propertiesJson, children);
    }

    /// <summary>Creates a <c>strike</c> element.</summary>
    public static ProgrammaticViewChild Strike(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("strike", propertiesJson, children);
    }

    /// <summary>Creates a <c>tt</c> element.</summary>
    public static ProgrammaticViewChild Tt(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("tt", propertiesJson, children);
    }

    /// <summary>Creates a <c>xmp</c> element.</summary>
    public static ProgrammaticViewChild Xmp(
        string propertiesJson = "{}",
        params ProgrammaticViewChild[] children)
    {
        return Elements.Tag("xmp", propertiesJson, children);
    }
}
