;; Generated by utils/generate-programmatic-view-tags.mjs. Do not edit.
(ns angular-ts.view)

(defn- call-view [name & args]
  (.apply (aget (.-view js/angular) name) nil (to-array args)))

(defn tag
  "Creates an HTML element by name."
  [name & args]
  (.apply (aget (.-tags js/angular) name) nil (to-array args)))

(defn tag-ns
  "Creates a namespaced element by name."
  [namespace-uri name & args]
  (.apply (aget ((.-tags js/angular) namespace-uri) name) nil (to-array args)))

(defn event
  ([listener] (call-view "event" listener))
  ([listener options] (call-view "event" listener options)))

(defn attrs [values]
  (call-view "attrs" (clj->js values)))

(defn props [values]
  (call-view "props" (clj->js values)))

(defn each [read key render]
  (call-view "each" read key render))

(defn a
  "Creates a a element."
  [& args]
  (apply tag "a" args))

(defn abbr
  "Creates a abbr element."
  [& args]
  (apply tag "abbr" args))

(defn address
  "Creates a address element."
  [& args]
  (apply tag "address" args))

(defn area
  "Creates a area element."
  [& args]
  (apply tag "area" args))

(defn article
  "Creates a article element."
  [& args]
  (apply tag "article" args))

(defn aside
  "Creates a aside element."
  [& args]
  (apply tag "aside" args))

(defn audio
  "Creates a audio element."
  [& args]
  (apply tag "audio" args))

(defn b
  "Creates a b element."
  [& args]
  (apply tag "b" args))

(defn base
  "Creates a base element."
  [& args]
  (apply tag "base" args))

(defn bdi
  "Creates a bdi element."
  [& args]
  (apply tag "bdi" args))

(defn bdo
  "Creates a bdo element."
  [& args]
  (apply tag "bdo" args))

(defn blockquote
  "Creates a blockquote element."
  [& args]
  (apply tag "blockquote" args))

(defn body
  "Creates a body element."
  [& args]
  (apply tag "body" args))

(defn br
  "Creates a br element."
  [& args]
  (apply tag "br" args))

(defn button
  "Creates a button element."
  [& args]
  (apply tag "button" args))

(defn canvas
  "Creates a canvas element."
  [& args]
  (apply tag "canvas" args))

(defn caption
  "Creates a caption element."
  [& args]
  (apply tag "caption" args))

(defn cite
  "Creates a cite element."
  [& args]
  (apply tag "cite" args))

(defn code
  "Creates a code element."
  [& args]
  (apply tag "code" args))

(defn col
  "Creates a col element."
  [& args]
  (apply tag "col" args))

(defn colgroup
  "Creates a colgroup element."
  [& args]
  (apply tag "colgroup" args))

(defn data
  "Creates a data element."
  [& args]
  (apply tag "data" args))

(defn datalist
  "Creates a datalist element."
  [& args]
  (apply tag "datalist" args))

(defn dd
  "Creates a dd element."
  [& args]
  (apply tag "dd" args))

(defn del
  "Creates a del element."
  [& args]
  (apply tag "del" args))

(defn details
  "Creates a details element."
  [& args]
  (apply tag "details" args))

(defn dfn
  "Creates a dfn element."
  [& args]
  (apply tag "dfn" args))

(defn dialog
  "Creates a dialog element."
  [& args]
  (apply tag "dialog" args))

(defn div
  "Creates a div element."
  [& args]
  (apply tag "div" args))

(defn dl
  "Creates a dl element."
  [& args]
  (apply tag "dl" args))

(defn dt
  "Creates a dt element."
  [& args]
  (apply tag "dt" args))

(defn em
  "Creates a em element."
  [& args]
  (apply tag "em" args))

(defn embed
  "Creates a embed element."
  [& args]
  (apply tag "embed" args))

(defn fieldset
  "Creates a fieldset element."
  [& args]
  (apply tag "fieldset" args))

(defn figcaption
  "Creates a figcaption element."
  [& args]
  (apply tag "figcaption" args))

(defn figure
  "Creates a figure element."
  [& args]
  (apply tag "figure" args))

(defn footer
  "Creates a footer element."
  [& args]
  (apply tag "footer" args))

(defn form
  "Creates a form element."
  [& args]
  (apply tag "form" args))

(defn h1
  "Creates a h1 element."
  [& args]
  (apply tag "h1" args))

(defn h2
  "Creates a h2 element."
  [& args]
  (apply tag "h2" args))

(defn h3
  "Creates a h3 element."
  [& args]
  (apply tag "h3" args))

(defn h4
  "Creates a h4 element."
  [& args]
  (apply tag "h4" args))

(defn h5
  "Creates a h5 element."
  [& args]
  (apply tag "h5" args))

(defn h6
  "Creates a h6 element."
  [& args]
  (apply tag "h6" args))

(defn head
  "Creates a head element."
  [& args]
  (apply tag "head" args))

(defn header
  "Creates a header element."
  [& args]
  (apply tag "header" args))

(defn hgroup
  "Creates a hgroup element."
  [& args]
  (apply tag "hgroup" args))

(defn hr
  "Creates a hr element."
  [& args]
  (apply tag "hr" args))

(defn html
  "Creates a html element."
  [& args]
  (apply tag "html" args))

(defn i
  "Creates a i element."
  [& args]
  (apply tag "i" args))

(defn iframe
  "Creates a iframe element."
  [& args]
  (apply tag "iframe" args))

(defn img
  "Creates a img element."
  [& args]
  (apply tag "img" args))

(defn input
  "Creates a input element."
  [& args]
  (apply tag "input" args))

(defn ins
  "Creates a ins element."
  [& args]
  (apply tag "ins" args))

(defn kbd
  "Creates a kbd element."
  [& args]
  (apply tag "kbd" args))

(defn label
  "Creates a label element."
  [& args]
  (apply tag "label" args))

(defn legend
  "Creates a legend element."
  [& args]
  (apply tag "legend" args))

(defn li
  "Creates a li element."
  [& args]
  (apply tag "li" args))

(defn link
  "Creates a link element."
  [& args]
  (apply tag "link" args))

(defn main
  "Creates a main element."
  [& args]
  (apply tag "main" args))

(defn map-tag
  "Creates a map element."
  [& args]
  (apply tag "map" args))

(defn mark
  "Creates a mark element."
  [& args]
  (apply tag "mark" args))

(defn menu
  "Creates a menu element."
  [& args]
  (apply tag "menu" args))

(defn meta-tag
  "Creates a meta element."
  [& args]
  (apply tag "meta" args))

(defn meter
  "Creates a meter element."
  [& args]
  (apply tag "meter" args))

(defn nav
  "Creates a nav element."
  [& args]
  (apply tag "nav" args))

(defn noscript
  "Creates a noscript element."
  [& args]
  (apply tag "noscript" args))

(defn object
  "Creates a object element."
  [& args]
  (apply tag "object" args))

(defn ol
  "Creates a ol element."
  [& args]
  (apply tag "ol" args))

(defn optgroup
  "Creates a optgroup element."
  [& args]
  (apply tag "optgroup" args))

(defn option
  "Creates a option element."
  [& args]
  (apply tag "option" args))

(defn output
  "Creates a output element."
  [& args]
  (apply tag "output" args))

(defn p
  "Creates a p element."
  [& args]
  (apply tag "p" args))

(defn picture
  "Creates a picture element."
  [& args]
  (apply tag "picture" args))

(defn pre
  "Creates a pre element."
  [& args]
  (apply tag "pre" args))

(defn progress
  "Creates a progress element."
  [& args]
  (apply tag "progress" args))

(defn q
  "Creates a q element."
  [& args]
  (apply tag "q" args))

(defn rp
  "Creates a rp element."
  [& args]
  (apply tag "rp" args))

(defn rt
  "Creates a rt element."
  [& args]
  (apply tag "rt" args))

(defn ruby
  "Creates a ruby element."
  [& args]
  (apply tag "ruby" args))

(defn s
  "Creates a s element."
  [& args]
  (apply tag "s" args))

(defn samp
  "Creates a samp element."
  [& args]
  (apply tag "samp" args))

(defn script
  "Creates a script element."
  [& args]
  (apply tag "script" args))

(defn search
  "Creates a search element."
  [& args]
  (apply tag "search" args))

(defn section
  "Creates a section element."
  [& args]
  (apply tag "section" args))

(defn select
  "Creates a select element."
  [& args]
  (apply tag "select" args))

(defn slot
  "Creates a slot element."
  [& args]
  (apply tag "slot" args))

(defn small
  "Creates a small element."
  [& args]
  (apply tag "small" args))

(defn source
  "Creates a source element."
  [& args]
  (apply tag "source" args))

(defn span
  "Creates a span element."
  [& args]
  (apply tag "span" args))

(defn strong
  "Creates a strong element."
  [& args]
  (apply tag "strong" args))

(defn style
  "Creates a style element."
  [& args]
  (apply tag "style" args))

(defn sub
  "Creates a sub element."
  [& args]
  (apply tag "sub" args))

(defn summary
  "Creates a summary element."
  [& args]
  (apply tag "summary" args))

(defn sup
  "Creates a sup element."
  [& args]
  (apply tag "sup" args))

(defn table
  "Creates a table element."
  [& args]
  (apply tag "table" args))

(defn tbody
  "Creates a tbody element."
  [& args]
  (apply tag "tbody" args))

(defn td
  "Creates a td element."
  [& args]
  (apply tag "td" args))

(defn template
  "Creates a template element."
  [& args]
  (apply tag "template" args))

(defn textarea
  "Creates a textarea element."
  [& args]
  (apply tag "textarea" args))

(defn tfoot
  "Creates a tfoot element."
  [& args]
  (apply tag "tfoot" args))

(defn th
  "Creates a th element."
  [& args]
  (apply tag "th" args))

(defn thead
  "Creates a thead element."
  [& args]
  (apply tag "thead" args))

(defn time-tag
  "Creates a time element."
  [& args]
  (apply tag "time" args))

(defn title
  "Creates a title element."
  [& args]
  (apply tag "title" args))

(defn tr
  "Creates a tr element."
  [& args]
  (apply tag "tr" args))

(defn track
  "Creates a track element."
  [& args]
  (apply tag "track" args))

(defn u
  "Creates a u element."
  [& args]
  (apply tag "u" args))

(defn ul
  "Creates a ul element."
  [& args]
  (apply tag "ul" args))

(defn varTag
  "Creates a var element."
  [& args]
  (apply tag "var" args))

(defn video
  "Creates a video element."
  [& args]
  (apply tag "video" args))

(defn wbr
  "Creates a wbr element."
  [& args]
  (apply tag "wbr" args))

(defn acronym
  "Creates a acronym element."
  [& args]
  (apply tag "acronym" args))

(defn applet
  "Creates a applet element."
  [& args]
  (apply tag "applet" args))

(defn basefont
  "Creates a basefont element."
  [& args]
  (apply tag "basefont" args))

(defn bgsound
  "Creates a bgsound element."
  [& args]
  (apply tag "bgsound" args))

(defn big
  "Creates a big element."
  [& args]
  (apply tag "big" args))

(defn blink
  "Creates a blink element."
  [& args]
  (apply tag "blink" args))

(defn center
  "Creates a center element."
  [& args]
  (apply tag "center" args))

(defn dir
  "Creates a dir element."
  [& args]
  (apply tag "dir" args))

(defn font
  "Creates a font element."
  [& args]
  (apply tag "font" args))

(defn frame
  "Creates a frame element."
  [& args]
  (apply tag "frame" args))

(defn frameset
  "Creates a frameset element."
  [& args]
  (apply tag "frameset" args))

(defn isindex
  "Creates a isindex element."
  [& args]
  (apply tag "isindex" args))

(defn keygen
  "Creates a keygen element."
  [& args]
  (apply tag "keygen" args))

(defn listing
  "Creates a listing element."
  [& args]
  (apply tag "listing" args))

(defn marquee
  "Creates a marquee element."
  [& args]
  (apply tag "marquee" args))

(defn menuitem
  "Creates a menuitem element."
  [& args]
  (apply tag "menuitem" args))

(defn multicol
  "Creates a multicol element."
  [& args]
  (apply tag "multicol" args))

(defn nextid
  "Creates a nextid element."
  [& args]
  (apply tag "nextid" args))

(defn nobr
  "Creates a nobr element."
  [& args]
  (apply tag "nobr" args))

(defn noembed
  "Creates a noembed element."
  [& args]
  (apply tag "noembed" args))

(defn noframes
  "Creates a noframes element."
  [& args]
  (apply tag "noframes" args))

(defn param
  "Creates a param element."
  [& args]
  (apply tag "param" args))

(defn plaintext
  "Creates a plaintext element."
  [& args]
  (apply tag "plaintext" args))

(defn rb
  "Creates a rb element."
  [& args]
  (apply tag "rb" args))

(defn rtc
  "Creates a rtc element."
  [& args]
  (apply tag "rtc" args))

(defn spacer
  "Creates a spacer element."
  [& args]
  (apply tag "spacer" args))

(defn strike
  "Creates a strike element."
  [& args]
  (apply tag "strike" args))

(defn tt
  "Creates a tt element."
  [& args]
  (apply tag "tt" args))

(defn xmp
  "Creates a xmp element."
  [& args]
  (apply tag "xmp" args))
