export declare const VALID_CLASS = "ng-valid";
export declare const INVALID_CLASS = "ng-invalid";
export declare const PRISTINE_CLASS = "ng-pristine";
export declare const DIRTY_CLASS = "ng-dirty";
export declare const UNTOUCHED_CLASS = "ng-untouched";
export declare const TOUCHED_CLASS = "ng-touched";
export declare const EMPTY_CLASS = "ng-empty";
export declare const NOT_EMPTY_CLASS = "ng-not-empty";
export declare const PREFIX_REGEXP: RegExp;
export declare const SPECIAL_CHARS_REGEXP: RegExp;
export declare const ALIASED_ATTR: Record<string, string>;
