// Generated by utils/generate-programmatic-view-tags.mjs. Do not edit.
@external("angular_ts", "view_tag")
declare function hostViewTag(
  namespacePtr: usize,
  namespaceLen: i32,
  namePtr: usize,
  nameLen: i32,
  propertiesPtr: usize,
  propertiesLen: i32,
  childrenPtr: usize,
  childrenLen: i32,
): u32;

@external("angular_ts", "view_text")
declare function hostViewText(valuePtr: usize, valueLen: i32): u32;

@external("angular_ts", "view_release")
declare function hostViewRelease(handle: u32): u32;

export type ProgrammaticViewChild = u32;
export type ProgrammaticViewProperties = string;

export class ProgrammaticViewTags {
  constructor(public namespaceUri: string = "") {}

  withNamespace(namespaceUri: string): ProgrammaticViewTags {
    return new ProgrammaticViewTags(namespaceUri);
  }

  tag(
    name: string,
    propertiesJson: ProgrammaticViewProperties = "{}",
    children: Array<ProgrammaticViewChild> = [],
  ): ProgrammaticViewChild {
    const namespaceBuffer = String.UTF8.encode(this.namespaceUri);
    const nameBuffer = String.UTF8.encode(name);
    const propertiesBuffer = String.UTF8.encode(propertiesJson);

    return hostViewTag(
      changetype<usize>(namespaceBuffer),
      namespaceBuffer.byteLength,
      changetype<usize>(nameBuffer),
      nameBuffer.byteLength,
      changetype<usize>(propertiesBuffer),
      propertiesBuffer.byteLength,
      children.dataStart,
      children.length,
    );
  }
}

export const tags = new ProgrammaticViewTags();

export function text(value: string): ProgrammaticViewChild {
  const buffer = String.UTF8.encode(value);
  return hostViewText(changetype<usize>(buffer), buffer.byteLength);
}

export function releaseView(child: ProgrammaticViewChild): bool {
  return hostViewRelease(child) != 0;
}

/** Creates a `a` element. */
export function a(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("a", propertiesJson, children);
}

/** Creates a `abbr` element. */
export function abbr(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("abbr", propertiesJson, children);
}

/** Creates a `address` element. */
export function address(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("address", propertiesJson, children);
}

/** Creates a `area` element. */
export function area(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("area", propertiesJson, children);
}

/** Creates a `article` element. */
export function article(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("article", propertiesJson, children);
}

/** Creates a `aside` element. */
export function aside(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("aside", propertiesJson, children);
}

/** Creates a `audio` element. */
export function audio(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("audio", propertiesJson, children);
}

/** Creates a `b` element. */
export function b(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("b", propertiesJson, children);
}

/** Creates a `base` element. */
export function base(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("base", propertiesJson, children);
}

/** Creates a `bdi` element. */
export function bdi(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("bdi", propertiesJson, children);
}

/** Creates a `bdo` element. */
export function bdo(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("bdo", propertiesJson, children);
}

/** Creates a `blockquote` element. */
export function blockquote(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("blockquote", propertiesJson, children);
}

/** Creates a `body` element. */
export function body(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("body", propertiesJson, children);
}

/** Creates a `br` element. */
export function br(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("br", propertiesJson, children);
}

/** Creates a `button` element. */
export function button(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("button", propertiesJson, children);
}

/** Creates a `canvas` element. */
export function canvas(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("canvas", propertiesJson, children);
}

/** Creates a `caption` element. */
export function caption(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("caption", propertiesJson, children);
}

/** Creates a `cite` element. */
export function cite(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("cite", propertiesJson, children);
}

/** Creates a `code` element. */
export function code(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("code", propertiesJson, children);
}

/** Creates a `col` element. */
export function col(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("col", propertiesJson, children);
}

/** Creates a `colgroup` element. */
export function colgroup(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("colgroup", propertiesJson, children);
}

/** Creates a `data` element. */
export function data(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("data", propertiesJson, children);
}

/** Creates a `datalist` element. */
export function datalist(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("datalist", propertiesJson, children);
}

/** Creates a `dd` element. */
export function dd(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("dd", propertiesJson, children);
}

/** Creates a `del` element. */
export function del(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("del", propertiesJson, children);
}

/** Creates a `details` element. */
export function details(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("details", propertiesJson, children);
}

/** Creates a `dfn` element. */
export function dfn(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("dfn", propertiesJson, children);
}

/** Creates a `dialog` element. */
export function dialog(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("dialog", propertiesJson, children);
}

/** Creates a `div` element. */
export function div(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("div", propertiesJson, children);
}

/** Creates a `dl` element. */
export function dl(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("dl", propertiesJson, children);
}

/** Creates a `dt` element. */
export function dt(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("dt", propertiesJson, children);
}

/** Creates a `em` element. */
export function em(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("em", propertiesJson, children);
}

/** Creates a `embed` element. */
export function embed(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("embed", propertiesJson, children);
}

/** Creates a `fieldset` element. */
export function fieldset(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("fieldset", propertiesJson, children);
}

/** Creates a `figcaption` element. */
export function figcaption(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("figcaption", propertiesJson, children);
}

/** Creates a `figure` element. */
export function figure(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("figure", propertiesJson, children);
}

/** Creates a `footer` element. */
export function footer(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("footer", propertiesJson, children);
}

/** Creates a `form` element. */
export function form(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("form", propertiesJson, children);
}

/** Creates a `h1` element. */
export function h1(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("h1", propertiesJson, children);
}

/** Creates a `h2` element. */
export function h2(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("h2", propertiesJson, children);
}

/** Creates a `h3` element. */
export function h3(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("h3", propertiesJson, children);
}

/** Creates a `h4` element. */
export function h4(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("h4", propertiesJson, children);
}

/** Creates a `h5` element. */
export function h5(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("h5", propertiesJson, children);
}

/** Creates a `h6` element. */
export function h6(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("h6", propertiesJson, children);
}

/** Creates a `head` element. */
export function head(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("head", propertiesJson, children);
}

/** Creates a `header` element. */
export function header(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("header", propertiesJson, children);
}

/** Creates a `hgroup` element. */
export function hgroup(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("hgroup", propertiesJson, children);
}

/** Creates a `hr` element. */
export function hr(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("hr", propertiesJson, children);
}

/** Creates a `html` element. */
export function html(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("html", propertiesJson, children);
}

/** Creates a `i` element. */
export function i(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("i", propertiesJson, children);
}

/** Creates a `iframe` element. */
export function iframe(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("iframe", propertiesJson, children);
}

/** Creates a `img` element. */
export function img(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("img", propertiesJson, children);
}

/** Creates a `input` element. */
export function input(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("input", propertiesJson, children);
}

/** Creates a `ins` element. */
export function ins(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("ins", propertiesJson, children);
}

/** Creates a `kbd` element. */
export function kbd(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("kbd", propertiesJson, children);
}

/** Creates a `label` element. */
export function label(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("label", propertiesJson, children);
}

/** Creates a `legend` element. */
export function legend(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("legend", propertiesJson, children);
}

/** Creates a `li` element. */
export function li(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("li", propertiesJson, children);
}

/** Creates a `link` element. */
export function link(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("link", propertiesJson, children);
}

/** Creates a `main` element. */
export function main(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("main", propertiesJson, children);
}

/** Creates a `map` element. */
export function map(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("map", propertiesJson, children);
}

/** Creates a `mark` element. */
export function mark(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("mark", propertiesJson, children);
}

/** Creates a `menu` element. */
export function menu(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("menu", propertiesJson, children);
}

/** Creates a `meta` element. */
export function meta(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("meta", propertiesJson, children);
}

/** Creates a `meter` element. */
export function meter(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("meter", propertiesJson, children);
}

/** Creates a `nav` element. */
export function nav(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("nav", propertiesJson, children);
}

/** Creates a `noscript` element. */
export function noscript(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("noscript", propertiesJson, children);
}

/** Creates a `object` element. */
export function object(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("object", propertiesJson, children);
}

/** Creates a `ol` element. */
export function ol(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("ol", propertiesJson, children);
}

/** Creates a `optgroup` element. */
export function optgroup(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("optgroup", propertiesJson, children);
}

/** Creates a `option` element. */
export function option(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("option", propertiesJson, children);
}

/** Creates a `output` element. */
export function output(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("output", propertiesJson, children);
}

/** Creates a `p` element. */
export function p(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("p", propertiesJson, children);
}

/** Creates a `picture` element. */
export function picture(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("picture", propertiesJson, children);
}

/** Creates a `pre` element. */
export function pre(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("pre", propertiesJson, children);
}

/** Creates a `progress` element. */
export function progress(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("progress", propertiesJson, children);
}

/** Creates a `q` element. */
export function q(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("q", propertiesJson, children);
}

/** Creates a `rp` element. */
export function rp(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("rp", propertiesJson, children);
}

/** Creates a `rt` element. */
export function rt(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("rt", propertiesJson, children);
}

/** Creates a `ruby` element. */
export function ruby(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("ruby", propertiesJson, children);
}

/** Creates a `s` element. */
export function s(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("s", propertiesJson, children);
}

/** Creates a `samp` element. */
export function samp(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("samp", propertiesJson, children);
}

/** Creates a `script` element. */
export function script(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("script", propertiesJson, children);
}

/** Creates a `search` element. */
export function search(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("search", propertiesJson, children);
}

/** Creates a `section` element. */
export function section(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("section", propertiesJson, children);
}

/** Creates a `select` element. */
export function select(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("select", propertiesJson, children);
}

/** Creates a `slot` element. */
export function slot(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("slot", propertiesJson, children);
}

/** Creates a `small` element. */
export function small(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("small", propertiesJson, children);
}

/** Creates a `source` element. */
export function source(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("source", propertiesJson, children);
}

/** Creates a `span` element. */
export function span(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("span", propertiesJson, children);
}

/** Creates a `strong` element. */
export function strong(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("strong", propertiesJson, children);
}

/** Creates a `style` element. */
export function style(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("style", propertiesJson, children);
}

/** Creates a `sub` element. */
export function sub(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("sub", propertiesJson, children);
}

/** Creates a `summary` element. */
export function summary(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("summary", propertiesJson, children);
}

/** Creates a `sup` element. */
export function sup(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("sup", propertiesJson, children);
}

/** Creates a `table` element. */
export function table(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("table", propertiesJson, children);
}

/** Creates a `tbody` element. */
export function tbody(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("tbody", propertiesJson, children);
}

/** Creates a `td` element. */
export function td(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("td", propertiesJson, children);
}

/** Creates a `template` element. */
export function template(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("template", propertiesJson, children);
}

/** Creates a `textarea` element. */
export function textarea(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("textarea", propertiesJson, children);
}

/** Creates a `tfoot` element. */
export function tfoot(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("tfoot", propertiesJson, children);
}

/** Creates a `th` element. */
export function th(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("th", propertiesJson, children);
}

/** Creates a `thead` element. */
export function thead(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("thead", propertiesJson, children);
}

/** Creates a `time` element. */
export function time(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("time", propertiesJson, children);
}

/** Creates a `title` element. */
export function title(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("title", propertiesJson, children);
}

/** Creates a `tr` element. */
export function tr(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("tr", propertiesJson, children);
}

/** Creates a `track` element. */
export function track(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("track", propertiesJson, children);
}

/** Creates a `u` element. */
export function u(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("u", propertiesJson, children);
}

/** Creates a `ul` element. */
export function ul(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("ul", propertiesJson, children);
}

/** Creates a `var` element. */
export function varTag(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("var", propertiesJson, children);
}

/** Creates a `video` element. */
export function video(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("video", propertiesJson, children);
}

/** Creates a `wbr` element. */
export function wbr(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("wbr", propertiesJson, children);
}

/** Creates a `acronym` element. */
export function acronym(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("acronym", propertiesJson, children);
}

/** Creates a `applet` element. */
export function applet(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("applet", propertiesJson, children);
}

/** Creates a `basefont` element. */
export function basefont(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("basefont", propertiesJson, children);
}

/** Creates a `bgsound` element. */
export function bgsound(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("bgsound", propertiesJson, children);
}

/** Creates a `big` element. */
export function big(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("big", propertiesJson, children);
}

/** Creates a `blink` element. */
export function blink(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("blink", propertiesJson, children);
}

/** Creates a `center` element. */
export function center(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("center", propertiesJson, children);
}

/** Creates a `dir` element. */
export function dir(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("dir", propertiesJson, children);
}

/** Creates a `font` element. */
export function font(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("font", propertiesJson, children);
}

/** Creates a `frame` element. */
export function frame(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("frame", propertiesJson, children);
}

/** Creates a `frameset` element. */
export function frameset(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("frameset", propertiesJson, children);
}

/** Creates a `isindex` element. */
export function isindex(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("isindex", propertiesJson, children);
}

/** Creates a `keygen` element. */
export function keygen(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("keygen", propertiesJson, children);
}

/** Creates a `listing` element. */
export function listing(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("listing", propertiesJson, children);
}

/** Creates a `marquee` element. */
export function marquee(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("marquee", propertiesJson, children);
}

/** Creates a `menuitem` element. */
export function menuitem(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("menuitem", propertiesJson, children);
}

/** Creates a `multicol` element. */
export function multicol(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("multicol", propertiesJson, children);
}

/** Creates a `nextid` element. */
export function nextid(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("nextid", propertiesJson, children);
}

/** Creates a `nobr` element. */
export function nobr(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("nobr", propertiesJson, children);
}

/** Creates a `noembed` element. */
export function noembed(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("noembed", propertiesJson, children);
}

/** Creates a `noframes` element. */
export function noframes(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("noframes", propertiesJson, children);
}

/** Creates a `param` element. */
export function param(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("param", propertiesJson, children);
}

/** Creates a `plaintext` element. */
export function plaintext(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("plaintext", propertiesJson, children);
}

/** Creates a `rb` element. */
export function rb(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("rb", propertiesJson, children);
}

/** Creates a `rtc` element. */
export function rtc(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("rtc", propertiesJson, children);
}

/** Creates a `spacer` element. */
export function spacer(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("spacer", propertiesJson, children);
}

/** Creates a `strike` element. */
export function strike(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("strike", propertiesJson, children);
}

/** Creates a `tt` element. */
export function tt(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("tt", propertiesJson, children);
}

/** Creates a `xmp` element. */
export function xmp(
  propertiesJson: string = "{}",
  children: Array<ProgrammaticViewChild> = [],
): ProgrammaticViewChild {
  return tags.tag("xmp", propertiesJson, children);
}
