// Generated by integrations/android/scripts/generate-native-capabilities.mjs.
// Do not edit directly.

export const nativeCapabilities = {
  platform: {
    name: "platform",
    artifact: "navigation",
    availability: "required",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [],
  },
  permissions: {
    name: "permissions",
    artifact: "navigation",
    availability: "required",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
      {
        name: "request",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  clipboard: {
    name: "clipboard",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "read",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "write",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  sharing: {
    name: "sharing",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "share",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  intents: {
    name: "intents",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "open",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  haptics: {
    name: "haptics",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "perform",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  connectivity: {
    name: "connectivity",
    artifact: "navigation",
    availability: "required",
    minSdk: 28,
    permission: "android.permission.ACCESS_NETWORK_STATE",
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "watch",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "unwatch",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [
      {
        name: "change",
        payload: "JSON",
      },
    ],
  },
  lifecycle: {
    name: "lifecycle",
    artifact: "navigation",
    availability: "required",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "watch",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "unwatch",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [
      {
        name: "change",
        payload: "JSON",
      },
    ],
  },
  window: {
    name: "window",
    artifact: "navigation",
    availability: "required",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "watch",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "unwatch",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [
      {
        name: "change",
        payload: "JSON",
      },
    ],
  },
  notifications: {
    name: "notifications",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: "android.permission.POST_NOTIFICATIONS",
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "open-settings",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [],
  },
  geolocation: {
    name: "geolocation",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: "android.permission.ACCESS_FINE_LOCATION",
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "current",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  biometrics: {
    name: "biometrics",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [],
  },
  camera: {
    name: "camera",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: "android.permission.CAMERA",
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "capture",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  files: {
    name: "files",
    artifact: "navigation",
    availability: "device",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "open",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
    ],
    events: [],
  },
  credentials: {
    name: "credentials",
    artifact: "credentials",
    availability: "optional",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "get",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
      {
        name: "create-password",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
      {
        name: "create-passkey",
        mode: "async",
        parameters: "JSON",
        result: "JSON",
      },
      {
        name: "clear",
        mode: "async",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [],
  },
  media: {
    name: "media",
    artifact: "media",
    availability: "optional",
    minSdk: 28,
    permission: null,
    methods: [
      {
        name: "status",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "load",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
      {
        name: "play",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "pause",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "stop",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
      {
        name: "seek",
        mode: "sync",
        parameters: "JSON",
        result: "JSON",
      },
      {
        name: "release",
        mode: "sync",
        parameters: "VOID",
        result: "JSON",
      },
    ],
    events: [],
  },
} as const;
export interface NativeCapabilityMethodMap {
  readonly platform: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly permissions: {
    readonly status: { readonly parameters: unknown; readonly result: unknown };
    readonly request: {
      readonly parameters: unknown;
      readonly result: unknown;
    };
  };
  readonly clipboard: {
    readonly read: { readonly parameters: undefined; readonly result: unknown };
    readonly write: { readonly parameters: unknown; readonly result: unknown };
  };
  readonly sharing: {
    readonly share: { readonly parameters: unknown; readonly result: unknown };
  };
  readonly intents: {
    readonly open: { readonly parameters: unknown; readonly result: unknown };
  };
  readonly haptics: {
    readonly perform: {
      readonly parameters: unknown;
      readonly result: unknown;
    };
  };
  readonly connectivity: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly watch: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly unwatch: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly lifecycle: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly watch: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly unwatch: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly window: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly watch: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly unwatch: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly notifications: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly "open-settings": {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly geolocation: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly current: {
      readonly parameters: unknown;
      readonly result: unknown;
    };
  };
  readonly biometrics: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly camera: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly capture: {
      readonly parameters: unknown;
      readonly result: unknown;
    };
  };
  readonly files: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly open: { readonly parameters: unknown; readonly result: unknown };
  };
  readonly credentials: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly get: { readonly parameters: unknown; readonly result: unknown };
    readonly "create-password": {
      readonly parameters: unknown;
      readonly result: unknown;
    };
    readonly "create-passkey": {
      readonly parameters: unknown;
      readonly result: unknown;
    };
    readonly clear: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
  readonly media: {
    readonly status: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly load: { readonly parameters: unknown; readonly result: unknown };
    readonly play: { readonly parameters: undefined; readonly result: unknown };
    readonly pause: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
    readonly stop: { readonly parameters: undefined; readonly result: unknown };
    readonly seek: { readonly parameters: unknown; readonly result: unknown };
    readonly release: {
      readonly parameters: undefined;
      readonly result: unknown;
    };
  };
}
export interface NativeCapabilityEventMap {
  readonly platform: Readonly<Record<never, never>>;
  readonly permissions: Readonly<Record<never, never>>;
  readonly clipboard: Readonly<Record<never, never>>;
  readonly sharing: Readonly<Record<never, never>>;
  readonly intents: Readonly<Record<never, never>>;
  readonly haptics: Readonly<Record<never, never>>;
  readonly connectivity: {
    readonly change: unknown;
  };
  readonly lifecycle: {
    readonly change: unknown;
  };
  readonly window: {
    readonly change: unknown;
  };
  readonly notifications: Readonly<Record<never, never>>;
  readonly geolocation: Readonly<Record<never, never>>;
  readonly biometrics: Readonly<Record<never, never>>;
  readonly camera: Readonly<Record<never, never>>;
  readonly files: Readonly<Record<never, never>>;
  readonly credentials: Readonly<Record<never, never>>;
  readonly media: Readonly<Record<never, never>>;
}
export type NativeCapabilityName = keyof NativeCapabilityMethodMap;
export type NativeCapabilityMethodName<Name extends NativeCapabilityName> =
  keyof NativeCapabilityMethodMap[Name];
export type NativeCapabilityMethodContract<
  Name extends NativeCapabilityName,
  Method extends NativeCapabilityMethodName<Name>,
> = NativeCapabilityMethodMap[Name][Method];
export type NativeCapabilityParameters<
  Name extends NativeCapabilityName,
  Method extends NativeCapabilityMethodName<Name>,
> =
  NativeCapabilityMethodContract<Name, Method> extends {
    readonly parameters: infer Parameters;
  }
    ? Parameters
    : never;
export type NativeCapabilityResult<
  Name extends NativeCapabilityName,
  Method extends NativeCapabilityMethodName<Name>,
> =
  NativeCapabilityMethodContract<Name, Method> extends {
    readonly result: infer Result;
  }
    ? Result
    : never;
export type NativeCapabilityEventName<Name extends NativeCapabilityName> =
  keyof NativeCapabilityEventMap[Name];
export type NativeCapabilityEventPayload<
  Name extends NativeCapabilityName,
  Event extends NativeCapabilityEventName<Name>,
> = NativeCapabilityEventMap[Name][Event];
