import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import ts from "typescript";

const root = path.resolve(import.meta.dirname, "../../..");
const interfacePath = path.join(root, "@types/interface.d.ts");
const outputPath = path.join(
  root,
  "integrations/gleam/src/angular_ts/injection_tokens.gleam",
);

const typeMap = new Map(
  Object.entries({
    $angular: "namespace.AngularService",
    $attrs: "namespace.Attributes",
    $scope: "namespace.Scope",
    $element: "namespace.RootElementService",
    $anchorScroll: "namespace.AnchorScrollService",
    $animate: "namespace.AnimateService",
    $aria: "namespace.AriaService",
    $compile: "namespace.CompileService",
    $cookie: "namespace.CookieService",
    $controller: "namespace.ControllerService",
    $document: "namespace.DocumentService",
    $eventBus: "namespace.PubSubService",
    $exceptionHandler: "namespace.ExceptionHandlerService",
    $filter: "namespace.FilterService",
    $http: "namespace.HttpService",
    $httpParamSerializer: "namespace.HttpParamSerializerSerService",
    $interpolate: "namespace.InterpolateService",
    $location: "namespace.LocationService",
    $log: "namespace.LogService",
    $parse: "namespace.ParseService",
    $rest: "namespace.RestFactory",
    $rootScope: "namespace.RootScopeService",
    $rootElement: "namespace.RootElementService",
    $sce: "namespace.SceService",
    $sceDelegate: "namespace.SceDelegateService",
    $state: "namespace.StateService",
    $stateRegistry: "namespace.StateRegistryService",
    $sse: "namespace.SseService",
    $templateCache: "namespace.TemplateCacheService",
    $templateRequest: "namespace.TemplateRequestService",
    $transitions: "namespace.TransitionService",
    $window: "namespace.WindowService",
    $websocket: "namespace.WebSocketService",
    $worker: "namespace.WorkerConnection",
    $wasm: "namespace.WasmService",
    $provide: "namespace.ProvideService",
    $injector: "namespace.InjectorService",
    $angularProvider: "namespace.AngularServiceProvider",
    $anchorScrollProvider: "namespace.AnchorScrollProvider",
    $animateProvider: "namespace.AnimateProvider",
    $ariaProvider: "namespace.AriaService",
    $cookieProvider: "namespace.CookieService",
    $eventBusProvider: "namespace.PubSubProvider",
    $exceptionHandlerProvider: "namespace.ExceptionHandlerProvider",
    $filterProvider: "namespace.FilterProvider",
    $httpParamSerializerProvider: "namespace.HttpParamSerializerProvider",
    $interpolateProvider: "namespace.InterpolateProvider",
    $locationProvider: "namespace.LocationProvider",
    $sceProvider: "namespace.SceProvider",
    $sceDelegateProvider: "namespace.SceDelegateProvider",
    $sseProvider: "namespace.SseService",
    $stateProvider: "namespace.StateService",
    $stateRegistryProvider: "namespace.StateRegistryService",
    $transitionsProvider: "namespace.TransitionService",
    $websocketProvider: "namespace.WebSocketService",
    $workerProvider: "namespace.WorkerConnection",
    $wasmProvider: "namespace.WasmService",
    $controllerProvider: "namespace.ControllerService",
  }),
);

function extractPublicInjectionTokens(sourceText) {
  const sourceFile = ts.createSourceFile(
    interfacePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );

  const tokens = [];

  function visit(node) {
    if (ts.isVariableStatement(node)) {
      for (const declaration of node.declarationList.declarations) {
        if (
          declaration.name.getText(sourceFile) === "PublicInjectionTokens" &&
          declaration.type &&
          ts.isTypeLiteralNode(declaration.type)
        ) {
          for (const member of declaration.type.members) {
            if (ts.isPropertySignature(member) && member.type) {
              tokens.push({
                property: member.name.getText(sourceFile),
                value: member.type.getText(sourceFile).replaceAll('"', ""),
              });
            }
          }
        }
      }
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return tokens;
}

function toFunctionName(property) {
  const name = property.replace(/^\$/, "");
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^A-Za-z0-9_]/g, "_")
    .toLowerCase();
}

function render(tokens) {
  const lines = [
    "//// Generated by integrations/gleam/tool/generate_injection_tokens.mjs.",
    "//// Do not edit by hand.",
    "////",
    "//// Source: @types/interface.d.ts PublicInjectionTokens.",
    "",
    "import angular_ts/namespace",
    "import angular_ts/token.{type Token}",
    "import angular_ts/unsafe as js",
    "",
  ];

  for (const { property, value } of tokens) {
    const fnName = toFunctionName(property);
    const typeName = typeMap.get(property) ?? "js.JsValue";
    const signature = `pub fn ${fnName}() -> Token(${typeName}) {`;
    if (signature.length > 88) {
      lines.push(`pub fn ${fnName}() -> Token(`);
      lines.push(`  ${typeName},`);
      lines.push(") {");
    } else {
      lines.push(signature);
    }
    lines.push(`  token.new("${value}")`);
    lines.push("}");
    lines.push("");
  }

  if (lines.at(-1) === "") lines.pop();

  return `${lines.join("\n")}\n`;
}

const output = render(
  extractPublicInjectionTokens(fs.readFileSync(interfacePath, "utf8")),
);
const check = process.argv.includes("--check");

if (check) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";

  if (current !== output) {
    console.error(
      "Gleam injection tokens are stale. Run `make -C integrations/gleam generate-injection-tokens`.",
    );
    process.exit(1);
  }
} else {
  fs.writeFileSync(outputPath, output);
}
