import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import ts from "typescript";

const root = path.resolve(import.meta.dirname, "../../..");
const namespacePath = path.join(root, "@types/namespace.d.ts");
const outputPath = path.join(
  root,
  "integrations/gleam/src/angular_ts/namespace.gleam",
);

function extractNamespaceTypes(sourceText) {
  const sourceFile = ts.createSourceFile(
    namespacePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );

  const types = [];

  function visit(node, inNgNamespace = false) {
    if (ts.isModuleDeclaration(node)) {
      const name = node.name;
      const nextInNgNamespace =
        inNgNamespace ||
        (ts.isIdentifier(name) && name.escapedText.toString() === "ng");

      if (node.body) visit(node.body, nextInNgNamespace);
      return;
    }

    if (inNgNamespace && ts.isTypeAliasDeclaration(node)) {
      types.push({
        name: node.name.escapedText.toString(),
        parameters: node.typeParameters?.map((parameter) =>
          parameter.name.escapedText.toString(),
        ) ?? [],
      });
      return;
    }

    ts.forEachChild(node, (child) => visit(child, inNgNamespace));
  }

  visit(sourceFile);
  return types;
}

function gleamTypeParameters(parameters) {
  return parameters.map((_, index) => String.fromCharCode("a".charCodeAt(0) + index));
}

function renderNamespaceModule(types) {
  const lines = [
    "//// Generated by integrations/gleam/tool/generate_ng_namespace.mjs.",
    "//// Do not edit by hand.",
    "////",
    "//// Source: @types/namespace.d.ts public `ng` namespace type aliases.",
    "",
  ];

  for (const type of types) {
    const parameters = gleamTypeParameters(type.parameters);
    const suffix = parameters.length > 0 ? `(${parameters.join(", ")})` : "";
    lines.push(`pub type ${type.name}${suffix}`);
    lines.push("");
  }

  if (lines.at(-1) === "") lines.pop();

  return `${lines.join("\n")}\n`;
}

const sourceText = fs.readFileSync(namespacePath, "utf8");
const output = renderNamespaceModule(extractNamespaceTypes(sourceText));
const check = process.argv.includes("--check");

if (check) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";

  if (current !== output) {
    console.error(
      "Gleam namespace types are stale. Run `make -C integrations/gleam generate-namespace`.",
    );
    process.exit(1);
  }
} else {
  fs.writeFileSync(outputPath, output);
}
