(ns angular-ts.facade-compile
  (:require [angular-ts.core :as ng]))

(defn compile-facade-surface
  "Compile every public fluent facade call shape without executing registrations."
  [^js/ng.NgModule app
   ^js/ng.Injectable annotated
   ^js/ng.DirectiveFactory directive-factory
   ^js/ng.Component component-options
   ^js/ng.EventBusService event-bus
   ^js/ng.AppComponentOptions app-component-options
   ^js/ng.ScopeElementConstructor element-class
   factory]
  [(ng/injectable ["dependency"] factory)
   (ng/module "existing")
   (ng/module "created" ["dependency"])
   (ng/value app "value" #js {})
   (ng/constant app "constant" "value")
   (ng/config app #js {})
   (ng/run app annotated)
   (ng/run app ["dependency"] factory)
   (ng/component app "component" component-options)
   (ng/controller app "controller" annotated)
   (ng/controller app "controllerWithDeps" ["dependency"] factory)
   (ng/directive app "directive" directive-factory)
   (ng/directive app "directiveWithDeps" ["dependency"] factory)
   (ng/factory app "factory" annotated)
   (ng/factory app "factoryWithDeps" ["dependency"] factory)
   (ng/service app "service" annotated)
   (ng/service app "serviceWithDeps" ["dependency"] factory)
   (ng/provider app "provider" annotated)
   (ng/provider app "providerWithDeps" ["dependency"] factory)
   (ng/decorator app "decorator" annotated)
   (ng/decorator app "decoratorWithDeps" ["dependency"] factory)
   (ng/animation app "animation" annotated)
   (ng/animation app "animationWithDeps" ["dependency"] factory)
   (ng/filter app "filter" annotated)
   (ng/filter app "filterWithDeps" ["dependency"] factory)
   (ng/model app "model" #js {})
   (ng/model app "modelWithDeps" ["dependency"] factory)
   (ng/machine app "machine" #js {})
   (ng/machine app "machineWithDeps" ["dependency"] factory)
   (ng/workflow app "workflow" #js {})
   (ng/workflow app "workflowWithDeps" ["dependency"] factory)
   (ng/workflow-supervisor app "supervisor" #js {})
   (ng/workflow-supervisor app "supervisorWithDeps" ["dependency"] factory)
   (ng/router app #js {:states #js []})
   (ng/lazy-state app "lazy" factory)
   (ng/wasm app "wasm" #js {:url "module.wasm"})
   (ng/wasm app "wasmWithDeps" ["dependency"] factory)
   (ng/worker app "worker" "worker.js")
   (ng/worker app "configuredWorker" "worker.js" #js {})
   (ng/service-worker app "service-worker.js")
   (ng/service-worker app "service-worker.js" #js {})
   (ng/store app "store" factory "local")
   (ng/store app "configuredStore" factory "local" #js {})
   (ng/rest app "rest" "/api/items")
   (ng/rest app "entityRest" "/api/items" factory)
   (ng/rest app "configuredRest" "/api/items" factory #js {})
   (ng/sse app "events" "/events")
   (ng/sse app "configuredEvents" "/events" #js {})
   (ng/websocket app "socket" "wss://example.test")
   (ng/websocket app "configuredSocket" "wss://example.test" #js {})
   (ng/web-transport app "transport" "https://example.test")
   (ng/web-transport app "configuredTransport" "https://example.test" #js {})
   (ng/app-component app "app-shell" app-component-options)
   (ng/web-component app "scope-element" element-class)
   (ng/publish event-bus "topic")
   (ng/publish event-bus "topic" #js {})
   (ng/publish event-bus "topic" #js {} #js {})])
