export interface NativeElementDescriptor {
  readonly name: string;
  readonly primitive: string;
  readonly properties?: Readonly<Record<string, string>>;
  readonly events?: readonly string[];
  readonly methods?: readonly string[];
  readonly children?: readonly string[];
}

export interface CompiledNativeElement {
  readonly source: string;
  readonly registration: Readonly<{
    name: string;
    properties: readonly string[];
    events: readonly string[];
    methods: readonly string[];
  }>;
}

export function compileNativeElement(
  descriptor: NativeElementDescriptor,
): CompiledNativeElement {
  if (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)+$/u.test(descriptor.name)) {
    throw new TypeError("Custom native element names must contain a hyphen");
  }
  if (!/^[A-Z][A-Za-z0-9]*$/u.test(descriptor.primitive)) {
    throw new TypeError("ArkUI primitive must be a public identifier");
  }
  const properties = sortedUnique(Object.keys(descriptor.properties ?? {}), "property");
  const events = sortedUnique(descriptor.events ?? [], "event");
  const methods = sortedUnique(descriptor.methods ?? [], "method");
  const registration = { name: descriptor.name, properties, events, methods };
  return {
    registration,
    source: [
      "// Generated by AngularTS Native. Do not edit.",
      `export const nativeElementName = ${JSON.stringify(descriptor.name)};`,
      `export const arkUIPrimitive = ${JSON.stringify(descriptor.primitive)};`,
      `export const nativeElementRegistration = ${JSON.stringify(registration)} as const;`,
      "",
    ].join("\n"),
  };
}

function sortedUnique(values: readonly string[], kind: string): readonly string[] {
  for (const value of values) {
    if (!/^[A-Za-z][A-Za-z0-9]*$/u.test(value)) throw new TypeError(`Invalid ${kind}: ${value}`);
  }
  const sorted = [...values].sort();
  if (new Set(sorted).size !== sorted.length) throw new TypeError(`Duplicate ${kind}`);
  return sorted;
}
