/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __ng_component_ScopeProbe_bridgeMetadata: () => [number, number];
export const __ng_component_ScopeProbe_fieldBridgeMetadata: () => [number, number];
export const __ng_component_scopeprobe_applyCountFromScope: (a: number, b: number) => void;
export const __ng_component_scopeprobe_increment: (a: number) => void;
export const __ng_component_scopeprobe_new: (a: number) => number;
export const __ng_manifest: () => [number, number];
export const __wbg___ng_component_scopeprobe_free: (a: number, b: number) => void;
export const __wbg_get___ng_component_scopeprobe_count: (a: number) => number;
export const __wbg_get___ng_component_scopeprobe_seenCount: (a: number) => number;
export const __wbg_get___ng_component_scopeprobe_source: (a: number) => [number, number];
export const __wbg_set___ng_component_scopeprobe_count: (a: number, b: number) => void;
export const __wbg_set___ng_component_scopeprobe_seenCount: (a: number, b: number) => void;
export const __wbg_set___ng_component_scopeprobe_source: (a: number, b: number, c: number) => void;
export const __wbg_wasmscope_free: (a: number, b: number) => void;
export const ng_abi_alloc: (a: number) => number;
export const ng_abi_free: (a: number, b: number) => void;
export const ng_abi_version: () => number;
export const ng_scope_on_transaction: (a: number, b: number, c: number) => void;
export const wasmscope_named: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmscope_new: (a: number, b: number, c: number) => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
