/** Public WebAssembly service and language-binding surface. */
export { WasmAbi, WasmAbiError, WasmError } from "./wasm.ts";
export type {
  WasmAbiExports,
  WasmAbiErrorCode,
  WasmBinding,
  WasmBindingOptions,
  WasmCompileOptions,
  WasmErrorCode,
  WasmErrorStage,
  WasmLoadOptions,
  WasmResource,
  WasmResourceStatus,
  WasmScope,
  WasmScopeAbi,
  WasmScopeAbiImportObject,
  WasmScopeAbiImports,
  WasmScopeBindingOptions,
  WasmScopeOptions,
  WasmScopeReference,
  WasmScopeTransaction,
  WasmScopeTransactionUpdate,
  WasmScopeUpdate,
  WasmScopeWatchOptions,
  WasmScopeWriteOptions,
  WasmService,
  WasmSource,
  WasmTarget,
} from "./wasm.ts";
