package angularwasm

import (
	"fmt"
	"strings"
)

// ControllerBridgeConfig controls generated Go source for a browser controller bridge.
type ControllerBridgeConfig struct {
	PackageName string
	AppType     string
	Controller  Registration
}

// GenerateControllerBridge emits Go source that exports one controller object
// to the generated AngularTS bootstrap and wires scope sync/watch metadata.
func GenerateControllerBridge(config ControllerBridgeConfig) (string, error) {
	if config.PackageName == "" {
		return "", fmt.Errorf("angular.ts wasm: bridge package name is required")
	}
	if config.AppType == "" {
		return "", fmt.Errorf("angular.ts wasm: bridge app type is required")
	}
	if config.Controller.Kind != RegistrationKindController {
		return "", fmt.Errorf("angular.ts wasm: bridge registration must be a controller")
	}
	if err := config.Controller.Validate(); err != nil {
		return "", err
	}

	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	out.WriteString("//go:build js && wasm\n\n")
	out.WriteString("package ")
	out.WriteString(config.PackageName)
	out.WriteString("\n\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"syscall/js\"\n\n")
	out.WriteString("\tangularwasm \"angular.ts/wasm/go\"\n")
	out.WriteString(")\n\n")
	out.WriteString("var angularTsGoBridgeFunctions []js.Func\n\n")
	out.WriteString("func registerController(app *")
	out.WriteString(config.AppType)
	out.WriteString(") {\n")
	out.WriteString("\tapi := js.Global().Get(\"Object\").New()\n\n")
	writeControllerMethod(&out, "bind", true)
	for _, method := range config.Controller.Methods {
		writeControllerMethod(&out, method, true)
	}
	writeControllerMethod(&out, "unbind", false)
	out.WriteString("\n\tjs.Global().Set(")
	writeGoString(&out, config.Controller.ExportName)
	out.WriteString(", api)\n")
	out.WriteString("}\n\n")
	out.WriteString("func angularTsGoSetFunc(target js.Value, name string, fn func(js.Value, []js.Value) any) {\n")
	out.WriteString("\twrapped := js.FuncOf(fn)\n")
	out.WriteString("\tangularTsGoBridgeFunctions = append(angularTsGoBridgeFunctions, wrapped)\n")
	out.WriteString("\ttarget.Set(name, wrapped)\n")
	out.WriteString("}\n\n")
	writeBindScope(&out, config)
	writeUnbindScope(&out, config)
	writeSync(&out, config)
	writeSyncAfterAsync(&out, config)

	return out.String(), nil
}

func writeControllerMethod(out *strings.Builder, method string, sync bool) {
	out.WriteString("\tangularTsGoSetFunc(api, ")
	writeGoString(out, method)
	out.WriteString(", func(this js.Value, args []js.Value) any {\n")
	out.WriteString("\t\tresult := app.")
	out.WriteString(method)
	out.WriteString("(this, args)\n")
	if sync {
		out.WriteString("\t\tapp.sync()\n")
		out.WriteString("\t\tapp.syncAfterAsync(result)\n")
	}
	out.WriteString("\t\treturn result\n")
	out.WriteString("\t})\n")
}

func writeBindScope(out *strings.Builder, config ControllerBridgeConfig) {
	out.WriteString("func (app *")
	out.WriteString(config.AppType)
	out.WriteString(") bindScope(scopeName string) {\n")
	out.WriteString("\tapp.scope = angularwasm.BrowserNamed(scopeName)\n")
	for _, watch := range config.Controller.Watches {
		out.WriteString("\tapp.watch = angularwasm.WatchValue[")
		out.WriteString(watch.GoType)
		out.WriteString("](\n")
		out.WriteString("\t\tapp.scope,\n")
		out.WriteString("\t\t")
		writeGoString(out, watch.Path)
		out.WriteString(",\n")
		out.WriteString("\t\tfunc(value ")
		out.WriteString(watch.GoType)
		out.WriteString(") {\n")
		out.WriteString("\t\t\tapp.")
		out.WriteString(watch.Handler)
		out.WriteString("(value)\n")
		out.WriteString("\t\t\tapp.sync()\n")
		out.WriteString("\t\t},\n")
		out.WriteString("\t)\n")
	}
	out.WriteString("}\n\n")
}

func writeUnbindScope(out *strings.Builder, config ControllerBridgeConfig) {
	out.WriteString("func (app *")
	out.WriteString(config.AppType)
	out.WriteString(") unbindScope() {\n")
	if len(config.Controller.Watches) == 0 {
		out.WriteString("}\n\n")
		return
	}
	out.WriteString("\tapp.watch.Unwatch()\n")
	out.WriteString("}\n\n")
}

func writeSync(out *strings.Builder, config ControllerBridgeConfig) {
	out.WriteString("func (app *")
	out.WriteString(config.AppType)
	out.WriteString(") sync() {\n")
	out.WriteString("\t_ = angularwasm.SyncScope(\n")
	out.WriteString("\t\tapp.scope,\n")
	for _, field := range config.Controller.Fields {
		out.WriteString("\t\tangularwasm.ValueAt(")
		writeGoString(out, field.Name)
		out.WriteString(", app.")
		goName := field.GoName
		if goName == "" {
			goName = field.Name
		}
		out.WriteString(goName)
		out.WriteString("),\n")
	}
	out.WriteString("\t)\n")
	out.WriteString("}\n")
}

func writeSyncAfterAsync(out *strings.Builder, config ControllerBridgeConfig) {
	out.WriteString("\nfunc (app *")
	out.WriteString(config.AppType)
	out.WriteString(") syncAfterAsync(result any) {\n")
	out.WriteString("\tpromise, ok := result.(js.Value)\n")
	out.WriteString("\tif !ok || !promise.Truthy() {\n")
	out.WriteString("\t\treturn\n")
	out.WriteString("\t}\n\n")
	out.WriteString("\tif promise.Get(\"then\").Type() != js.TypeFunction {\n")
	out.WriteString("\t\treturn\n")
	out.WriteString("\t}\n\n")
	out.WriteString("\tsync := js.FuncOf(func(this js.Value, args []js.Value) any {\n")
	out.WriteString("\t\tapp.sync()\n")
	out.WriteString("\t\treturn nil\n")
	out.WriteString("\t})\n")
	out.WriteString("\tangularTsGoBridgeFunctions = append(angularTsGoBridgeFunctions, sync)\n\n")
	out.WriteString("\tif promise.Get(\"finally\").Type() == js.TypeFunction {\n")
	out.WriteString("\t\tpromise.Call(\"finally\", sync)\n")
	out.WriteString("\t\treturn\n")
	out.WriteString("\t}\n\n")
	out.WriteString("\tpromise.Call(\"then\", sync, sync)\n")
	out.WriteString("}\n")
}

func writeGoString(out *strings.Builder, value string) {
	out.WriteString(fmt.Sprintf("%q", value))
}
