package angularwasm

import (
	"strings"
	"testing"
)

func TestGenerateControllerBridge(t *testing.T) {
	module := NewNgModule("goDemo")
	module.Controller(NewController[metadataTodoList](
		"todoList",
		"__ng_controller_TodoList",
	).
		WithMethods("add", "archive").
		WithFields(
			TypedField[[]metadataTodoStore]("items"),
			TypedFieldFor[int]("remainingCount", "remainingCount()"),
		).
		WithWatchRoutes(
			TypedWatchRoute[string]("newTodo", "onNewTodoChanged"),
		))

	source, err := GenerateControllerBridge(ControllerBridgeConfig{
		PackageName: "main",
		AppType:     "TodoApp",
		Controller:  module.Registrations()[0],
	})
	if err != nil {
		t.Fatalf("GenerateControllerBridge returned error: %v", err)
	}

	required := []string{
		"Code generated by go generate; DO NOT EDIT.",
		"var angularTsGoBridgeFunctions []js.Func",
		"func registerController(app *TodoApp)",
		`angularTsGoSetFunc(api, "add"`,
		`angularTsGoSetFunc(api, "unbind"`,
		`js.Global().Set("__ng_controller_TodoList", api)`,
		"func angularTsGoSetFunc(target js.Value, name string, fn func(js.Value, []js.Value) any)",
		"angularTsGoBridgeFunctions = append(angularTsGoBridgeFunctions, wrapped)",
		`angularwasm.ValueAt("items", app.items)`,
		`angularwasm.ValueAt("remainingCount", app.remainingCount())`,
		"angularwasm.WatchValue[string](",
		"app.onNewTodoChanged(value)",
		"app.syncAfterAsync(result)",
		"func (app *TodoApp) syncAfterAsync(result any)",
		"promise.Get(\"then\").Type() != js.TypeFunction",
		"promise.Call(\"finally\", sync)",
		"promise.Call(\"then\", sync, sync)",
	}
	for _, fragment := range required {
		if !strings.Contains(source, fragment) {
			t.Fatalf("generated bridge missing %q:\n%s", fragment, source)
		}
	}
}

func TestGenerateControllerBridgeRejectsNonController(t *testing.T) {
	_, err := GenerateControllerBridge(ControllerBridgeConfig{
		PackageName: "main",
		AppType:     "TodoApp",
		Controller: Registration{
			Kind:       RegistrationKindValue,
			Name:       "appTitle",
			ExportName: "__ng_value_AppTitle",
			GoType:     "string",
		},
	})
	if err == nil {
		t.Fatal("expected non-controller registration error")
	}
}
