// Code generated by utils/generate-programmatic-view-tags.mjs. DO NOT EDIT.
//go:build js && wasm

package angularwasm

// A creates a a element.
func (t ProgrammaticViewTags) A(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("a", properties, children...)
}

// Abbr creates a abbr element.
func (t ProgrammaticViewTags) Abbr(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("abbr", properties, children...)
}

// Address creates a address element.
func (t ProgrammaticViewTags) Address(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("address", properties, children...)
}

// Area creates a area element.
func (t ProgrammaticViewTags) Area(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("area", properties, children...)
}

// Article creates a article element.
func (t ProgrammaticViewTags) Article(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("article", properties, children...)
}

// Aside creates a aside element.
func (t ProgrammaticViewTags) Aside(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("aside", properties, children...)
}

// Audio creates a audio element.
func (t ProgrammaticViewTags) Audio(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("audio", properties, children...)
}

// B creates a b element.
func (t ProgrammaticViewTags) B(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("b", properties, children...)
}

// Base creates a base element.
func (t ProgrammaticViewTags) Base(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("base", properties, children...)
}

// Bdi creates a bdi element.
func (t ProgrammaticViewTags) Bdi(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("bdi", properties, children...)
}

// Bdo creates a bdo element.
func (t ProgrammaticViewTags) Bdo(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("bdo", properties, children...)
}

// Blockquote creates a blockquote element.
func (t ProgrammaticViewTags) Blockquote(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("blockquote", properties, children...)
}

// Body creates a body element.
func (t ProgrammaticViewTags) Body(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("body", properties, children...)
}

// Br creates a br element.
func (t ProgrammaticViewTags) Br(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("br", properties, children...)
}

// Button creates a button element.
func (t ProgrammaticViewTags) Button(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("button", properties, children...)
}

// Canvas creates a canvas element.
func (t ProgrammaticViewTags) Canvas(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("canvas", properties, children...)
}

// Caption creates a caption element.
func (t ProgrammaticViewTags) Caption(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("caption", properties, children...)
}

// Cite creates a cite element.
func (t ProgrammaticViewTags) Cite(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("cite", properties, children...)
}

// Code creates a code element.
func (t ProgrammaticViewTags) Code(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("code", properties, children...)
}

// Col creates a col element.
func (t ProgrammaticViewTags) Col(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("col", properties, children...)
}

// Colgroup creates a colgroup element.
func (t ProgrammaticViewTags) Colgroup(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("colgroup", properties, children...)
}

// Data creates a data element.
func (t ProgrammaticViewTags) Data(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("data", properties, children...)
}

// Datalist creates a datalist element.
func (t ProgrammaticViewTags) Datalist(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("datalist", properties, children...)
}

// Dd creates a dd element.
func (t ProgrammaticViewTags) Dd(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("dd", properties, children...)
}

// Del creates a del element.
func (t ProgrammaticViewTags) Del(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("del", properties, children...)
}

// Details creates a details element.
func (t ProgrammaticViewTags) Details(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("details", properties, children...)
}

// Dfn creates a dfn element.
func (t ProgrammaticViewTags) Dfn(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("dfn", properties, children...)
}

// Dialog creates a dialog element.
func (t ProgrammaticViewTags) Dialog(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("dialog", properties, children...)
}

// Div creates a div element.
func (t ProgrammaticViewTags) Div(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("div", properties, children...)
}

// Dl creates a dl element.
func (t ProgrammaticViewTags) Dl(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("dl", properties, children...)
}

// Dt creates a dt element.
func (t ProgrammaticViewTags) Dt(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("dt", properties, children...)
}

// Em creates a em element.
func (t ProgrammaticViewTags) Em(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("em", properties, children...)
}

// Embed creates a embed element.
func (t ProgrammaticViewTags) Embed(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("embed", properties, children...)
}

// Fieldset creates a fieldset element.
func (t ProgrammaticViewTags) Fieldset(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("fieldset", properties, children...)
}

// Figcaption creates a figcaption element.
func (t ProgrammaticViewTags) Figcaption(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("figcaption", properties, children...)
}

// Figure creates a figure element.
func (t ProgrammaticViewTags) Figure(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("figure", properties, children...)
}

// Footer creates a footer element.
func (t ProgrammaticViewTags) Footer(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("footer", properties, children...)
}

// Form creates a form element.
func (t ProgrammaticViewTags) Form(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("form", properties, children...)
}

// H1 creates a h1 element.
func (t ProgrammaticViewTags) H1(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("h1", properties, children...)
}

// H2 creates a h2 element.
func (t ProgrammaticViewTags) H2(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("h2", properties, children...)
}

// H3 creates a h3 element.
func (t ProgrammaticViewTags) H3(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("h3", properties, children...)
}

// H4 creates a h4 element.
func (t ProgrammaticViewTags) H4(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("h4", properties, children...)
}

// H5 creates a h5 element.
func (t ProgrammaticViewTags) H5(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("h5", properties, children...)
}

// H6 creates a h6 element.
func (t ProgrammaticViewTags) H6(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("h6", properties, children...)
}

// Head creates a head element.
func (t ProgrammaticViewTags) Head(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("head", properties, children...)
}

// Header creates a header element.
func (t ProgrammaticViewTags) Header(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("header", properties, children...)
}

// Hgroup creates a hgroup element.
func (t ProgrammaticViewTags) Hgroup(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("hgroup", properties, children...)
}

// Hr creates a hr element.
func (t ProgrammaticViewTags) Hr(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("hr", properties, children...)
}

// Html creates a html element.
func (t ProgrammaticViewTags) Html(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("html", properties, children...)
}

// I creates a i element.
func (t ProgrammaticViewTags) I(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("i", properties, children...)
}

// Iframe creates a iframe element.
func (t ProgrammaticViewTags) Iframe(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("iframe", properties, children...)
}

// Img creates a img element.
func (t ProgrammaticViewTags) Img(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("img", properties, children...)
}

// Input creates a input element.
func (t ProgrammaticViewTags) Input(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("input", properties, children...)
}

// Ins creates a ins element.
func (t ProgrammaticViewTags) Ins(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("ins", properties, children...)
}

// Kbd creates a kbd element.
func (t ProgrammaticViewTags) Kbd(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("kbd", properties, children...)
}

// Label creates a label element.
func (t ProgrammaticViewTags) Label(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("label", properties, children...)
}

// Legend creates a legend element.
func (t ProgrammaticViewTags) Legend(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("legend", properties, children...)
}

// Li creates a li element.
func (t ProgrammaticViewTags) Li(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("li", properties, children...)
}

// Link creates a link element.
func (t ProgrammaticViewTags) Link(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("link", properties, children...)
}

// Main creates a main element.
func (t ProgrammaticViewTags) Main(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("main", properties, children...)
}

// Map creates a map element.
func (t ProgrammaticViewTags) Map(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("map", properties, children...)
}

// Mark creates a mark element.
func (t ProgrammaticViewTags) Mark(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("mark", properties, children...)
}

// Menu creates a menu element.
func (t ProgrammaticViewTags) Menu(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("menu", properties, children...)
}

// Meta creates a meta element.
func (t ProgrammaticViewTags) Meta(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("meta", properties, children...)
}

// Meter creates a meter element.
func (t ProgrammaticViewTags) Meter(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("meter", properties, children...)
}

// Nav creates a nav element.
func (t ProgrammaticViewTags) Nav(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("nav", properties, children...)
}

// Noscript creates a noscript element.
func (t ProgrammaticViewTags) Noscript(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("noscript", properties, children...)
}

// Object creates a object element.
func (t ProgrammaticViewTags) Object(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("object", properties, children...)
}

// Ol creates a ol element.
func (t ProgrammaticViewTags) Ol(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("ol", properties, children...)
}

// Optgroup creates a optgroup element.
func (t ProgrammaticViewTags) Optgroup(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("optgroup", properties, children...)
}

// Option creates a option element.
func (t ProgrammaticViewTags) Option(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("option", properties, children...)
}

// Output creates a output element.
func (t ProgrammaticViewTags) Output(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("output", properties, children...)
}

// P creates a p element.
func (t ProgrammaticViewTags) P(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("p", properties, children...)
}

// Picture creates a picture element.
func (t ProgrammaticViewTags) Picture(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("picture", properties, children...)
}

// Pre creates a pre element.
func (t ProgrammaticViewTags) Pre(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("pre", properties, children...)
}

// Progress creates a progress element.
func (t ProgrammaticViewTags) Progress(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("progress", properties, children...)
}

// Q creates a q element.
func (t ProgrammaticViewTags) Q(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("q", properties, children...)
}

// Rp creates a rp element.
func (t ProgrammaticViewTags) Rp(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("rp", properties, children...)
}

// Rt creates a rt element.
func (t ProgrammaticViewTags) Rt(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("rt", properties, children...)
}

// Ruby creates a ruby element.
func (t ProgrammaticViewTags) Ruby(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("ruby", properties, children...)
}

// S creates a s element.
func (t ProgrammaticViewTags) S(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("s", properties, children...)
}

// Samp creates a samp element.
func (t ProgrammaticViewTags) Samp(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("samp", properties, children...)
}

// Script creates a script element.
func (t ProgrammaticViewTags) Script(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("script", properties, children...)
}

// Search creates a search element.
func (t ProgrammaticViewTags) Search(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("search", properties, children...)
}

// Section creates a section element.
func (t ProgrammaticViewTags) Section(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("section", properties, children...)
}

// Select creates a select element.
func (t ProgrammaticViewTags) Select(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("select", properties, children...)
}

// Slot creates a slot element.
func (t ProgrammaticViewTags) Slot(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("slot", properties, children...)
}

// Small creates a small element.
func (t ProgrammaticViewTags) Small(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("small", properties, children...)
}

// Source creates a source element.
func (t ProgrammaticViewTags) Source(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("source", properties, children...)
}

// Span creates a span element.
func (t ProgrammaticViewTags) Span(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("span", properties, children...)
}

// Strong creates a strong element.
func (t ProgrammaticViewTags) Strong(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("strong", properties, children...)
}

// Style creates a style element.
func (t ProgrammaticViewTags) Style(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("style", properties, children...)
}

// Sub creates a sub element.
func (t ProgrammaticViewTags) Sub(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("sub", properties, children...)
}

// Summary creates a summary element.
func (t ProgrammaticViewTags) Summary(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("summary", properties, children...)
}

// Sup creates a sup element.
func (t ProgrammaticViewTags) Sup(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("sup", properties, children...)
}

// Table creates a table element.
func (t ProgrammaticViewTags) Table(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("table", properties, children...)
}

// Tbody creates a tbody element.
func (t ProgrammaticViewTags) Tbody(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("tbody", properties, children...)
}

// Td creates a td element.
func (t ProgrammaticViewTags) Td(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("td", properties, children...)
}

// Template creates a template element.
func (t ProgrammaticViewTags) Template(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("template", properties, children...)
}

// Textarea creates a textarea element.
func (t ProgrammaticViewTags) Textarea(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("textarea", properties, children...)
}

// Tfoot creates a tfoot element.
func (t ProgrammaticViewTags) Tfoot(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("tfoot", properties, children...)
}

// Th creates a th element.
func (t ProgrammaticViewTags) Th(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("th", properties, children...)
}

// Thead creates a thead element.
func (t ProgrammaticViewTags) Thead(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("thead", properties, children...)
}

// Time creates a time element.
func (t ProgrammaticViewTags) Time(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("time", properties, children...)
}

// Title creates a title element.
func (t ProgrammaticViewTags) Title(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("title", properties, children...)
}

// Tr creates a tr element.
func (t ProgrammaticViewTags) Tr(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("tr", properties, children...)
}

// Track creates a track element.
func (t ProgrammaticViewTags) Track(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("track", properties, children...)
}

// U creates a u element.
func (t ProgrammaticViewTags) U(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("u", properties, children...)
}

// Ul creates a ul element.
func (t ProgrammaticViewTags) Ul(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("ul", properties, children...)
}

// Var creates a var element.
func (t ProgrammaticViewTags) Var(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("var", properties, children...)
}

// Video creates a video element.
func (t ProgrammaticViewTags) Video(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("video", properties, children...)
}

// Wbr creates a wbr element.
func (t ProgrammaticViewTags) Wbr(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("wbr", properties, children...)
}

// Acronym creates a acronym element.
func (t ProgrammaticViewTags) Acronym(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("acronym", properties, children...)
}

// Applet creates a applet element.
func (t ProgrammaticViewTags) Applet(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("applet", properties, children...)
}

// Basefont creates a basefont element.
func (t ProgrammaticViewTags) Basefont(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("basefont", properties, children...)
}

// Bgsound creates a bgsound element.
func (t ProgrammaticViewTags) Bgsound(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("bgsound", properties, children...)
}

// Big creates a big element.
func (t ProgrammaticViewTags) Big(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("big", properties, children...)
}

// Blink creates a blink element.
func (t ProgrammaticViewTags) Blink(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("blink", properties, children...)
}

// Center creates a center element.
func (t ProgrammaticViewTags) Center(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("center", properties, children...)
}

// Dir creates a dir element.
func (t ProgrammaticViewTags) Dir(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("dir", properties, children...)
}

// Font creates a font element.
func (t ProgrammaticViewTags) Font(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("font", properties, children...)
}

// Frame creates a frame element.
func (t ProgrammaticViewTags) Frame(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("frame", properties, children...)
}

// Frameset creates a frameset element.
func (t ProgrammaticViewTags) Frameset(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("frameset", properties, children...)
}

// Isindex creates a isindex element.
func (t ProgrammaticViewTags) Isindex(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("isindex", properties, children...)
}

// Keygen creates a keygen element.
func (t ProgrammaticViewTags) Keygen(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("keygen", properties, children...)
}

// Listing creates a listing element.
func (t ProgrammaticViewTags) Listing(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("listing", properties, children...)
}

// Marquee creates a marquee element.
func (t ProgrammaticViewTags) Marquee(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("marquee", properties, children...)
}

// Menuitem creates a menuitem element.
func (t ProgrammaticViewTags) Menuitem(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("menuitem", properties, children...)
}

// Multicol creates a multicol element.
func (t ProgrammaticViewTags) Multicol(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("multicol", properties, children...)
}

// Nextid creates a nextid element.
func (t ProgrammaticViewTags) Nextid(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("nextid", properties, children...)
}

// Nobr creates a nobr element.
func (t ProgrammaticViewTags) Nobr(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("nobr", properties, children...)
}

// Noembed creates a noembed element.
func (t ProgrammaticViewTags) Noembed(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("noembed", properties, children...)
}

// Noframes creates a noframes element.
func (t ProgrammaticViewTags) Noframes(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("noframes", properties, children...)
}

// Param creates a param element.
func (t ProgrammaticViewTags) Param(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("param", properties, children...)
}

// Plaintext creates a plaintext element.
func (t ProgrammaticViewTags) Plaintext(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("plaintext", properties, children...)
}

// Rb creates a rb element.
func (t ProgrammaticViewTags) Rb(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("rb", properties, children...)
}

// Rtc creates a rtc element.
func (t ProgrammaticViewTags) Rtc(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("rtc", properties, children...)
}

// Spacer creates a spacer element.
func (t ProgrammaticViewTags) Spacer(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("spacer", properties, children...)
}

// Strike creates a strike element.
func (t ProgrammaticViewTags) Strike(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("strike", properties, children...)
}

// Tt creates a tt element.
func (t ProgrammaticViewTags) Tt(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("tt", properties, children...)
}

// Xmp creates a xmp element.
func (t ProgrammaticViewTags) Xmp(
	properties ProgrammaticViewProperties,
	children ...ProgrammaticViewChild,
) ProgrammaticViewChild {
	return t.Tag("xmp", properties, children...)
}
