// Generated by utils/generate-programmatic-view-tags.mjs. Do not edit.
package org.angular.ts.view;

import elemental2.dom.HTMLElement;
import jsinterop.annotations.JsMethod;

/** Direct, typed entry points for AngularTS HTML tag factories. */
public final class Tags {
  private Tags() {}

  /** Creates a {@code a} element. */
  @JsMethod(namespace = "angular.tags", name = "a")
  public static native HTMLElement a(Object... arguments);

  /** Creates a {@code abbr} element. */
  @JsMethod(namespace = "angular.tags", name = "abbr")
  public static native HTMLElement abbr(Object... arguments);

  /** Creates a {@code address} element. */
  @JsMethod(namespace = "angular.tags", name = "address")
  public static native HTMLElement address(Object... arguments);

  /** Creates a {@code area} element. */
  @JsMethod(namespace = "angular.tags", name = "area")
  public static native HTMLElement area(Object... arguments);

  /** Creates a {@code article} element. */
  @JsMethod(namespace = "angular.tags", name = "article")
  public static native HTMLElement article(Object... arguments);

  /** Creates a {@code aside} element. */
  @JsMethod(namespace = "angular.tags", name = "aside")
  public static native HTMLElement aside(Object... arguments);

  /** Creates a {@code audio} element. */
  @JsMethod(namespace = "angular.tags", name = "audio")
  public static native HTMLElement audio(Object... arguments);

  /** Creates a {@code b} element. */
  @JsMethod(namespace = "angular.tags", name = "b")
  public static native HTMLElement b(Object... arguments);

  /** Creates a {@code base} element. */
  @JsMethod(namespace = "angular.tags", name = "base")
  public static native HTMLElement base(Object... arguments);

  /** Creates a {@code bdi} element. */
  @JsMethod(namespace = "angular.tags", name = "bdi")
  public static native HTMLElement bdi(Object... arguments);

  /** Creates a {@code bdo} element. */
  @JsMethod(namespace = "angular.tags", name = "bdo")
  public static native HTMLElement bdo(Object... arguments);

  /** Creates a {@code blockquote} element. */
  @JsMethod(namespace = "angular.tags", name = "blockquote")
  public static native HTMLElement blockquote(Object... arguments);

  /** Creates a {@code body} element. */
  @JsMethod(namespace = "angular.tags", name = "body")
  public static native HTMLElement body(Object... arguments);

  /** Creates a {@code br} element. */
  @JsMethod(namespace = "angular.tags", name = "br")
  public static native HTMLElement br(Object... arguments);

  /** Creates a {@code button} element. */
  @JsMethod(namespace = "angular.tags", name = "button")
  public static native HTMLElement button(Object... arguments);

  /** Creates a {@code canvas} element. */
  @JsMethod(namespace = "angular.tags", name = "canvas")
  public static native HTMLElement canvas(Object... arguments);

  /** Creates a {@code caption} element. */
  @JsMethod(namespace = "angular.tags", name = "caption")
  public static native HTMLElement caption(Object... arguments);

  /** Creates a {@code cite} element. */
  @JsMethod(namespace = "angular.tags", name = "cite")
  public static native HTMLElement cite(Object... arguments);

  /** Creates a {@code code} element. */
  @JsMethod(namespace = "angular.tags", name = "code")
  public static native HTMLElement code(Object... arguments);

  /** Creates a {@code col} element. */
  @JsMethod(namespace = "angular.tags", name = "col")
  public static native HTMLElement col(Object... arguments);

  /** Creates a {@code colgroup} element. */
  @JsMethod(namespace = "angular.tags", name = "colgroup")
  public static native HTMLElement colgroup(Object... arguments);

  /** Creates a {@code data} element. */
  @JsMethod(namespace = "angular.tags", name = "data")
  public static native HTMLElement data(Object... arguments);

  /** Creates a {@code datalist} element. */
  @JsMethod(namespace = "angular.tags", name = "datalist")
  public static native HTMLElement datalist(Object... arguments);

  /** Creates a {@code dd} element. */
  @JsMethod(namespace = "angular.tags", name = "dd")
  public static native HTMLElement dd(Object... arguments);

  /** Creates a {@code del} element. */
  @JsMethod(namespace = "angular.tags", name = "del")
  public static native HTMLElement del(Object... arguments);

  /** Creates a {@code details} element. */
  @JsMethod(namespace = "angular.tags", name = "details")
  public static native HTMLElement details(Object... arguments);

  /** Creates a {@code dfn} element. */
  @JsMethod(namespace = "angular.tags", name = "dfn")
  public static native HTMLElement dfn(Object... arguments);

  /** Creates a {@code dialog} element. */
  @JsMethod(namespace = "angular.tags", name = "dialog")
  public static native HTMLElement dialog(Object... arguments);

  /** Creates a {@code div} element. */
  @JsMethod(namespace = "angular.tags", name = "div")
  public static native HTMLElement div(Object... arguments);

  /** Creates a {@code dl} element. */
  @JsMethod(namespace = "angular.tags", name = "dl")
  public static native HTMLElement dl(Object... arguments);

  /** Creates a {@code dt} element. */
  @JsMethod(namespace = "angular.tags", name = "dt")
  public static native HTMLElement dt(Object... arguments);

  /** Creates a {@code em} element. */
  @JsMethod(namespace = "angular.tags", name = "em")
  public static native HTMLElement em(Object... arguments);

  /** Creates a {@code embed} element. */
  @JsMethod(namespace = "angular.tags", name = "embed")
  public static native HTMLElement embed(Object... arguments);

  /** Creates a {@code fieldset} element. */
  @JsMethod(namespace = "angular.tags", name = "fieldset")
  public static native HTMLElement fieldset(Object... arguments);

  /** Creates a {@code figcaption} element. */
  @JsMethod(namespace = "angular.tags", name = "figcaption")
  public static native HTMLElement figcaption(Object... arguments);

  /** Creates a {@code figure} element. */
  @JsMethod(namespace = "angular.tags", name = "figure")
  public static native HTMLElement figure(Object... arguments);

  /** Creates a {@code footer} element. */
  @JsMethod(namespace = "angular.tags", name = "footer")
  public static native HTMLElement footer(Object... arguments);

  /** Creates a {@code form} element. */
  @JsMethod(namespace = "angular.tags", name = "form")
  public static native HTMLElement form(Object... arguments);

  /** Creates a {@code h1} element. */
  @JsMethod(namespace = "angular.tags", name = "h1")
  public static native HTMLElement h1(Object... arguments);

  /** Creates a {@code h2} element. */
  @JsMethod(namespace = "angular.tags", name = "h2")
  public static native HTMLElement h2(Object... arguments);

  /** Creates a {@code h3} element. */
  @JsMethod(namespace = "angular.tags", name = "h3")
  public static native HTMLElement h3(Object... arguments);

  /** Creates a {@code h4} element. */
  @JsMethod(namespace = "angular.tags", name = "h4")
  public static native HTMLElement h4(Object... arguments);

  /** Creates a {@code h5} element. */
  @JsMethod(namespace = "angular.tags", name = "h5")
  public static native HTMLElement h5(Object... arguments);

  /** Creates a {@code h6} element. */
  @JsMethod(namespace = "angular.tags", name = "h6")
  public static native HTMLElement h6(Object... arguments);

  /** Creates a {@code head} element. */
  @JsMethod(namespace = "angular.tags", name = "head")
  public static native HTMLElement head(Object... arguments);

  /** Creates a {@code header} element. */
  @JsMethod(namespace = "angular.tags", name = "header")
  public static native HTMLElement header(Object... arguments);

  /** Creates a {@code hgroup} element. */
  @JsMethod(namespace = "angular.tags", name = "hgroup")
  public static native HTMLElement hgroup(Object... arguments);

  /** Creates a {@code hr} element. */
  @JsMethod(namespace = "angular.tags", name = "hr")
  public static native HTMLElement hr(Object... arguments);

  /** Creates a {@code html} element. */
  @JsMethod(namespace = "angular.tags", name = "html")
  public static native HTMLElement html(Object... arguments);

  /** Creates a {@code i} element. */
  @JsMethod(namespace = "angular.tags", name = "i")
  public static native HTMLElement i(Object... arguments);

  /** Creates a {@code iframe} element. */
  @JsMethod(namespace = "angular.tags", name = "iframe")
  public static native HTMLElement iframe(Object... arguments);

  /** Creates a {@code img} element. */
  @JsMethod(namespace = "angular.tags", name = "img")
  public static native HTMLElement img(Object... arguments);

  /** Creates a {@code input} element. */
  @JsMethod(namespace = "angular.tags", name = "input")
  public static native HTMLElement input(Object... arguments);

  /** Creates a {@code ins} element. */
  @JsMethod(namespace = "angular.tags", name = "ins")
  public static native HTMLElement ins(Object... arguments);

  /** Creates a {@code kbd} element. */
  @JsMethod(namespace = "angular.tags", name = "kbd")
  public static native HTMLElement kbd(Object... arguments);

  /** Creates a {@code label} element. */
  @JsMethod(namespace = "angular.tags", name = "label")
  public static native HTMLElement label(Object... arguments);

  /** Creates a {@code legend} element. */
  @JsMethod(namespace = "angular.tags", name = "legend")
  public static native HTMLElement legend(Object... arguments);

  /** Creates a {@code li} element. */
  @JsMethod(namespace = "angular.tags", name = "li")
  public static native HTMLElement li(Object... arguments);

  /** Creates a {@code link} element. */
  @JsMethod(namespace = "angular.tags", name = "link")
  public static native HTMLElement link(Object... arguments);

  /** Creates a {@code main} element. */
  @JsMethod(namespace = "angular.tags", name = "main")
  public static native HTMLElement main(Object... arguments);

  /** Creates a {@code map} element. */
  @JsMethod(namespace = "angular.tags", name = "map")
  public static native HTMLElement map(Object... arguments);

  /** Creates a {@code mark} element. */
  @JsMethod(namespace = "angular.tags", name = "mark")
  public static native HTMLElement mark(Object... arguments);

  /** Creates a {@code menu} element. */
  @JsMethod(namespace = "angular.tags", name = "menu")
  public static native HTMLElement menu(Object... arguments);

  /** Creates a {@code meta} element. */
  @JsMethod(namespace = "angular.tags", name = "meta")
  public static native HTMLElement meta(Object... arguments);

  /** Creates a {@code meter} element. */
  @JsMethod(namespace = "angular.tags", name = "meter")
  public static native HTMLElement meter(Object... arguments);

  /** Creates a {@code nav} element. */
  @JsMethod(namespace = "angular.tags", name = "nav")
  public static native HTMLElement nav(Object... arguments);

  /** Creates a {@code noscript} element. */
  @JsMethod(namespace = "angular.tags", name = "noscript")
  public static native HTMLElement noscript(Object... arguments);

  /** Creates a {@code object} element. */
  @JsMethod(namespace = "angular.tags", name = "object")
  public static native HTMLElement object(Object... arguments);

  /** Creates a {@code ol} element. */
  @JsMethod(namespace = "angular.tags", name = "ol")
  public static native HTMLElement ol(Object... arguments);

  /** Creates a {@code optgroup} element. */
  @JsMethod(namespace = "angular.tags", name = "optgroup")
  public static native HTMLElement optgroup(Object... arguments);

  /** Creates a {@code option} element. */
  @JsMethod(namespace = "angular.tags", name = "option")
  public static native HTMLElement option(Object... arguments);

  /** Creates a {@code output} element. */
  @JsMethod(namespace = "angular.tags", name = "output")
  public static native HTMLElement output(Object... arguments);

  /** Creates a {@code p} element. */
  @JsMethod(namespace = "angular.tags", name = "p")
  public static native HTMLElement p(Object... arguments);

  /** Creates a {@code picture} element. */
  @JsMethod(namespace = "angular.tags", name = "picture")
  public static native HTMLElement picture(Object... arguments);

  /** Creates a {@code pre} element. */
  @JsMethod(namespace = "angular.tags", name = "pre")
  public static native HTMLElement pre(Object... arguments);

  /** Creates a {@code progress} element. */
  @JsMethod(namespace = "angular.tags", name = "progress")
  public static native HTMLElement progress(Object... arguments);

  /** Creates a {@code q} element. */
  @JsMethod(namespace = "angular.tags", name = "q")
  public static native HTMLElement q(Object... arguments);

  /** Creates a {@code rp} element. */
  @JsMethod(namespace = "angular.tags", name = "rp")
  public static native HTMLElement rp(Object... arguments);

  /** Creates a {@code rt} element. */
  @JsMethod(namespace = "angular.tags", name = "rt")
  public static native HTMLElement rt(Object... arguments);

  /** Creates a {@code ruby} element. */
  @JsMethod(namespace = "angular.tags", name = "ruby")
  public static native HTMLElement ruby(Object... arguments);

  /** Creates a {@code s} element. */
  @JsMethod(namespace = "angular.tags", name = "s")
  public static native HTMLElement s(Object... arguments);

  /** Creates a {@code samp} element. */
  @JsMethod(namespace = "angular.tags", name = "samp")
  public static native HTMLElement samp(Object... arguments);

  /** Creates a {@code script} element. */
  @JsMethod(namespace = "angular.tags", name = "script")
  public static native HTMLElement script(Object... arguments);

  /** Creates a {@code search} element. */
  @JsMethod(namespace = "angular.tags", name = "search")
  public static native HTMLElement search(Object... arguments);

  /** Creates a {@code section} element. */
  @JsMethod(namespace = "angular.tags", name = "section")
  public static native HTMLElement section(Object... arguments);

  /** Creates a {@code select} element. */
  @JsMethod(namespace = "angular.tags", name = "select")
  public static native HTMLElement select(Object... arguments);

  /** Creates a {@code slot} element. */
  @JsMethod(namespace = "angular.tags", name = "slot")
  public static native HTMLElement slot(Object... arguments);

  /** Creates a {@code small} element. */
  @JsMethod(namespace = "angular.tags", name = "small")
  public static native HTMLElement small(Object... arguments);

  /** Creates a {@code source} element. */
  @JsMethod(namespace = "angular.tags", name = "source")
  public static native HTMLElement source(Object... arguments);

  /** Creates a {@code span} element. */
  @JsMethod(namespace = "angular.tags", name = "span")
  public static native HTMLElement span(Object... arguments);

  /** Creates a {@code strong} element. */
  @JsMethod(namespace = "angular.tags", name = "strong")
  public static native HTMLElement strong(Object... arguments);

  /** Creates a {@code style} element. */
  @JsMethod(namespace = "angular.tags", name = "style")
  public static native HTMLElement style(Object... arguments);

  /** Creates a {@code sub} element. */
  @JsMethod(namespace = "angular.tags", name = "sub")
  public static native HTMLElement sub(Object... arguments);

  /** Creates a {@code summary} element. */
  @JsMethod(namespace = "angular.tags", name = "summary")
  public static native HTMLElement summary(Object... arguments);

  /** Creates a {@code sup} element. */
  @JsMethod(namespace = "angular.tags", name = "sup")
  public static native HTMLElement sup(Object... arguments);

  /** Creates a {@code table} element. */
  @JsMethod(namespace = "angular.tags", name = "table")
  public static native HTMLElement table(Object... arguments);

  /** Creates a {@code tbody} element. */
  @JsMethod(namespace = "angular.tags", name = "tbody")
  public static native HTMLElement tbody(Object... arguments);

  /** Creates a {@code td} element. */
  @JsMethod(namespace = "angular.tags", name = "td")
  public static native HTMLElement td(Object... arguments);

  /** Creates a {@code template} element. */
  @JsMethod(namespace = "angular.tags", name = "template")
  public static native HTMLElement template(Object... arguments);

  /** Creates a {@code textarea} element. */
  @JsMethod(namespace = "angular.tags", name = "textarea")
  public static native HTMLElement textarea(Object... arguments);

  /** Creates a {@code tfoot} element. */
  @JsMethod(namespace = "angular.tags", name = "tfoot")
  public static native HTMLElement tfoot(Object... arguments);

  /** Creates a {@code th} element. */
  @JsMethod(namespace = "angular.tags", name = "th")
  public static native HTMLElement th(Object... arguments);

  /** Creates a {@code thead} element. */
  @JsMethod(namespace = "angular.tags", name = "thead")
  public static native HTMLElement thead(Object... arguments);

  /** Creates a {@code time} element. */
  @JsMethod(namespace = "angular.tags", name = "time")
  public static native HTMLElement time(Object... arguments);

  /** Creates a {@code title} element. */
  @JsMethod(namespace = "angular.tags", name = "title")
  public static native HTMLElement title(Object... arguments);

  /** Creates a {@code tr} element. */
  @JsMethod(namespace = "angular.tags", name = "tr")
  public static native HTMLElement tr(Object... arguments);

  /** Creates a {@code track} element. */
  @JsMethod(namespace = "angular.tags", name = "track")
  public static native HTMLElement track(Object... arguments);

  /** Creates a {@code u} element. */
  @JsMethod(namespace = "angular.tags", name = "u")
  public static native HTMLElement u(Object... arguments);

  /** Creates a {@code ul} element. */
  @JsMethod(namespace = "angular.tags", name = "ul")
  public static native HTMLElement ul(Object... arguments);

  /** Creates a {@code var} element. */
  @JsMethod(namespace = "angular.tags", name = "var")
  public static native HTMLElement varTag(Object... arguments);

  /** Creates a {@code video} element. */
  @JsMethod(namespace = "angular.tags", name = "video")
  public static native HTMLElement video(Object... arguments);

  /** Creates a {@code wbr} element. */
  @JsMethod(namespace = "angular.tags", name = "wbr")
  public static native HTMLElement wbr(Object... arguments);

  /** Creates a {@code acronym} element. */
  @JsMethod(namespace = "angular.tags", name = "acronym")
  public static native HTMLElement acronym(Object... arguments);

  /** Creates a {@code applet} element. */
  @JsMethod(namespace = "angular.tags", name = "applet")
  public static native HTMLElement applet(Object... arguments);

  /** Creates a {@code basefont} element. */
  @JsMethod(namespace = "angular.tags", name = "basefont")
  public static native HTMLElement basefont(Object... arguments);

  /** Creates a {@code bgsound} element. */
  @JsMethod(namespace = "angular.tags", name = "bgsound")
  public static native HTMLElement bgsound(Object... arguments);

  /** Creates a {@code big} element. */
  @JsMethod(namespace = "angular.tags", name = "big")
  public static native HTMLElement big(Object... arguments);

  /** Creates a {@code blink} element. */
  @JsMethod(namespace = "angular.tags", name = "blink")
  public static native HTMLElement blink(Object... arguments);

  /** Creates a {@code center} element. */
  @JsMethod(namespace = "angular.tags", name = "center")
  public static native HTMLElement center(Object... arguments);

  /** Creates a {@code dir} element. */
  @JsMethod(namespace = "angular.tags", name = "dir")
  public static native HTMLElement dir(Object... arguments);

  /** Creates a {@code font} element. */
  @JsMethod(namespace = "angular.tags", name = "font")
  public static native HTMLElement font(Object... arguments);

  /** Creates a {@code frame} element. */
  @JsMethod(namespace = "angular.tags", name = "frame")
  public static native HTMLElement frame(Object... arguments);

  /** Creates a {@code frameset} element. */
  @JsMethod(namespace = "angular.tags", name = "frameset")
  public static native HTMLElement frameset(Object... arguments);

  /** Creates a {@code isindex} element. */
  @JsMethod(namespace = "angular.tags", name = "isindex")
  public static native HTMLElement isindex(Object... arguments);

  /** Creates a {@code keygen} element. */
  @JsMethod(namespace = "angular.tags", name = "keygen")
  public static native HTMLElement keygen(Object... arguments);

  /** Creates a {@code listing} element. */
  @JsMethod(namespace = "angular.tags", name = "listing")
  public static native HTMLElement listing(Object... arguments);

  /** Creates a {@code marquee} element. */
  @JsMethod(namespace = "angular.tags", name = "marquee")
  public static native HTMLElement marquee(Object... arguments);

  /** Creates a {@code menuitem} element. */
  @JsMethod(namespace = "angular.tags", name = "menuitem")
  public static native HTMLElement menuitem(Object... arguments);

  /** Creates a {@code multicol} element. */
  @JsMethod(namespace = "angular.tags", name = "multicol")
  public static native HTMLElement multicol(Object... arguments);

  /** Creates a {@code nextid} element. */
  @JsMethod(namespace = "angular.tags", name = "nextid")
  public static native HTMLElement nextid(Object... arguments);

  /** Creates a {@code nobr} element. */
  @JsMethod(namespace = "angular.tags", name = "nobr")
  public static native HTMLElement nobr(Object... arguments);

  /** Creates a {@code noembed} element. */
  @JsMethod(namespace = "angular.tags", name = "noembed")
  public static native HTMLElement noembed(Object... arguments);

  /** Creates a {@code noframes} element. */
  @JsMethod(namespace = "angular.tags", name = "noframes")
  public static native HTMLElement noframes(Object... arguments);

  /** Creates a {@code param} element. */
  @JsMethod(namespace = "angular.tags", name = "param")
  public static native HTMLElement param(Object... arguments);

  /** Creates a {@code plaintext} element. */
  @JsMethod(namespace = "angular.tags", name = "plaintext")
  public static native HTMLElement plaintext(Object... arguments);

  /** Creates a {@code rb} element. */
  @JsMethod(namespace = "angular.tags", name = "rb")
  public static native HTMLElement rb(Object... arguments);

  /** Creates a {@code rtc} element. */
  @JsMethod(namespace = "angular.tags", name = "rtc")
  public static native HTMLElement rtc(Object... arguments);

  /** Creates a {@code spacer} element. */
  @JsMethod(namespace = "angular.tags", name = "spacer")
  public static native HTMLElement spacer(Object... arguments);

  /** Creates a {@code strike} element. */
  @JsMethod(namespace = "angular.tags", name = "strike")
  public static native HTMLElement strike(Object... arguments);

  /** Creates a {@code tt} element. */
  @JsMethod(namespace = "angular.tags", name = "tt")
  public static native HTMLElement tt(Object... arguments);

  /** Creates a {@code xmp} element. */
  @JsMethod(namespace = "angular.tags", name = "xmp")
  public static native HTMLElement xmp(Object... arguments);
}
