package main

import (
	"os"

	angularwasm "angular.ts/wasm/go"
)

type goTodoController struct{}

func main() {
	module := angularwasm.NewNgModule("goWasmTodo")
	controller := angularwasm.NewController[goTodoController](
		"goTodoController",
		"__ng_controller_GoTodoController",
	).
		WithScopeName("goTodo:main").
		WithMethods("add", "toggle", "archive").
		WithFields(
			angularwasm.TypedField[[]Todo]("items"),
			angularwasm.TypedField[int]("remainingCount"),
			angularwasm.TypedField[string]("newTodo"),
			angularwasm.TypedField[string]("titleSeen"),
		).
		WithWatchRoutes(
			angularwasm.TypedWatchRoute[string]("newTodo", "onNewTodoChanged"),
		)
	module.Controller(controller)

	if err := angularwasm.WriteManifestFile(module, "angular-ts.json"); err != nil {
		panic(err)
	}

	if err := angularwasm.WriteBootstrapFile(angularwasm.BootstrapConfig{
		Manifest:             module,
		GoWasmScopeAbiImport: "../go-wasm-scope-abi.js",
		WasmExecImport:       "../wasm_exec.js",
		WasmPath:             "../main.wasm",
		Bootstrap:            true,
	}, ".angular-ts/bootstrap.js"); err != nil {
		panic(err)
	}

	if err := os.WriteFile("scope_sync_gen.go", []byte(scopeSyncSource), 0o644); err != nil {
		panic(err)
	}
}

type Todo struct {
	Task string
	Done bool
}

const scopeSyncSource = `// Code generated by go generate; DO NOT EDIT.
//go:build js && wasm

package main

import (
	"syscall/js"

	angularwasm "angular.ts/wasm/go"
)

func registerController(app *TodoApp) {
	api := js.Global().Get("Object").New()

	setFunc(api, "bind", func(this js.Value, args []js.Value) any {
		result := app.bind(this, args)
		app.sync()
		return result
	})
	setFunc(api, "add", func(this js.Value, args []js.Value) any {
		result := app.add(this, args)
		app.sync()
		return result
	})
	setFunc(api, "toggle", func(this js.Value, args []js.Value) any {
		result := app.toggle(this, args)
		app.sync()
		return result
	})
	setFunc(api, "archive", func(this js.Value, args []js.Value) any {
		result := app.archive(this, args)
		app.sync()
		return result
	})
	setFunc(api, "unbind", app.unbind)

	js.Global().Set("__ng_controller_GoTodoController", api)
}

func (app *TodoApp) bindScope(scopeName string) {
	app.scope = angularwasm.BrowserNamed(scopeName)
	app.watch = angularwasm.WatchValue[string](
		app.scope,
		"newTodo",
		func(value string) {
			app.onNewTodoChanged(value)
			app.sync()
		},
	)
}

func (app *TodoApp) unbindScope() {
	app.watch.Unwatch()
}

func (app *TodoApp) sync() {
	_ = angularwasm.SyncScope(
		app.scope,
		angularwasm.ValueAt("items", app.items),
		angularwasm.ValueAt("remainingCount", app.remainingCount()),
		angularwasm.ValueAt("newTodo", app.newTodo),
		angularwasm.ValueAt("titleSeen", app.titleSeen),
	)
}
`
