#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import ts from "typescript";

const dartReservedWords = new Set([
  "abstract",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "covariant",
  "default",
  "deferred",
  "do",
  "dynamic",
  "else",
  "enum",
  "export",
  "extends",
  "extension",
  "external",
  "factory",
  "false",
  "final",
  "finally",
  "for",
  "Function",
  "get",
  "hide",
  "if",
  "implements",
  "import",
  "in",
  "interface",
  "is",
  "late",
  "library",
  "mixin",
  "new",
  "null",
  "on",
  "operator",
  "part",
  "required",
  "rethrow",
  "return",
  "sealed",
  "set",
  "show",
  "static",
  "super",
  "switch",
  "sync",
  "this",
  "throw",
  "true",
  "try",
  "type",
  "typedef",
  "var",
  "void",
  "when",
  "with",
  "while",
  "yield"
]);

const generatedHeader = `// Generated by integrations/dart/tool/generate_dart_bindings.mjs.
// Do not edit by hand.

import 'dart:js_interop';
import 'dart:js_interop_unsafe';

import 'package:web/web.dart';

import '../facade.dart';
import '../unsafe.dart' as unsafe;

const Object _undefinedArgument = Object();

Object? _callFunction(JSFunction function, List<JSAny?> args) {
  return switch (args.length) {
    0 => function.callAsFunction(null),
    1 => function.callAsFunction(null, args[0]),
    2 => function.callAsFunction(null, args[0], args[1]),
    3 => function.callAsFunction(null, args[0], args[1], args[2]),
    4 => function.callAsFunction(null, args[0], args[1], args[2], args[3]),
    _ => throw UnsupportedError(
        'Generated function calls support up to 4 arguments',
      ),
  };
}

bool? _toDartBool(JSAny? value) {
  return value == null ? null : (value as JSBoolean).toDart;
}

String? _toDartString(JSAny? value) {
  return value == null ? null : (value as JSString).toDart;
}

num? _toDartNumber(JSAny? value) {
  return value == null ? null : (value as JSNumber).toDartDouble;
}

int? _toDartInt(JSAny? value) {
  return value == null ? null : (value as JSNumber).toDartInt;
}

/// Base class for generated raw AngularTS JS facades.
base class GeneratedNgFacade extends AngularTsJsFacade {
  /// Creates a generated raw AngularTS JS facade.
  const GeneratedNgFacade(super.raw);
}
`;

export function generateBindings({
  repoRoot = resolve(dirname(new URL(import.meta.url).pathname), "../../.."),
  namespacePath = "@" + "types/namespace.d.ts",
  overridesPath = "integrations/dart/tool/generator-overrides.json"
} = {}) {
  const { checker, overrides, sourceFile } = loadBindingInputs({
    repoRoot,
    namespacePath,
    overridesPath
  });
  const targets = collectBindingTargets(checker, sourceFile, overrides);
  const classes = [];

  for (const target of targets) {
    classes.push(
      renderClass(
        checker,
        overrides,
        target.typeName,
        target.type,
        target.generatedProperties,
        target.callSignatures
      )
    );
  }

  return `${generatedHeader}\n${classes.join("\n\n")}\n`;
}

export function collectBindingMetadata({
  repoRoot = resolve(dirname(new URL(import.meta.url).pathname), "../../.."),
  namespacePath = "@" + "types/namespace.d.ts",
  overridesPath = "integrations/dart/tool/generator-overrides.json"
} = {}) {
  const { checker, overrides, sourceFile } = loadBindingInputs({
    repoRoot,
    namespacePath,
    overridesPath
  });

  return collectBindingTargets(checker, sourceFile, overrides).map((target) => {
    const members = target.publicProperties.map((property) => ({
      name: property.name,
      status: skipStatus(overrides, target.typeName, property.name) ?? "generated"
    }));

    if (target.callSignatures.length > 0) {
      members.unshift({
        name: "call",
        status: skipStatus(overrides, target.typeName, "call") ?? "generated"
      });
    }

    return {
      typeName: target.typeName,
      members
    };
  });
}

export function collectReferencedTypeNames({
  repoRoot = resolve(dirname(new URL(import.meta.url).pathname), "../../.."),
  namespacePath = "@" + "types/namespace.d.ts",
  overridesPath = "integrations/dart/tool/generator-overrides.json"
} = {}) {
  const { checker, overrides, sourceFile } = loadBindingInputs({
    repoRoot,
    namespacePath,
    overridesPath
  });
  const names = new Set();

  for (const target of collectBindingTargets(checker, sourceFile, overrides)) {
    for (const signature of target.callSignatures) {
      collectSignatureTypeNames(checker, names, signature);
    }

    for (const property of target.publicProperties) {
      const declaration = property.valueDeclaration ?? property.declarations?.[0];
      const propertyType = checker.getTypeOfSymbolAtLocation(property, declaration);
      const signatures = callSignaturesOfType(checker, propertyType);

      collectTypeNames(checker, names, propertyType);

      for (const signature of signatures) {
        collectSignatureTypeNames(checker, names, signature);
      }
    }
  }

  return names;
}

function loadBindingInputs({ repoRoot, namespacePath, overridesPath }) {
  const sourcePath = resolve(repoRoot, namespacePath);
  const overrides = JSON.parse(readFileSync(resolve(repoRoot, overridesPath), "utf8"));
  const program = ts.createProgram([sourcePath], {
    allowJs: false,
    declaration: true,
    noEmit: true,
    skipLibCheck: true,
    strictNullChecks: true,
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler
  });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(sourcePath);

  if (!sourceFile) {
    throw new Error(`Unable to load ${sourcePath}`);
  }

  return { checker, overrides, sourceFile };
}

function collectBindingTargets(checker, sourceFile, overrides) {
  const targets = [];

  for (const alias of collectNgTypeAliases(sourceFile)) {
    const typeName = alias.name.text;
    const type = checker.getTypeFromTypeNode(alias.type);
    const callSignatures = callSignaturesOfType(checker, type);
    const publicProperties = checker
      .getPropertiesOfType(type)
      .filter((property) => !isNativeProperty(property))
      .filter((property) => !property.name.startsWith("__@"));
    const generatedProperties = publicProperties.filter(
      (property) => !isSkipped(overrides, typeName, property.name)
    );

    if (
      isPrimitiveLike(type) ||
      isNativeType(type) ||
      checker.isArrayType(type) ||
      checker.isTupleType(type)
    ) {
      continue;
    }

    targets.push({
      callSignatures,
      generatedProperties,
      publicProperties,
      type,
      typeName
    });
  }

  return targets;
}

function collectSignatureTypeNames(checker, names, signature) {
  collectTypeNames(checker, names, signature.getReturnType());

  for (const parameter of signature.parameters) {
    const declaration = parameter.valueDeclaration ?? parameter.declarations?.[0];

    if (declaration) {
      collectTypeNames(
        checker,
        names,
        checker.getTypeOfSymbolAtLocation(parameter, declaration)
      );
    }
  }
}

function collectTypeNames(checker, names, type) {
  const typeName = checker.typeToString(type);
  if (typeName) names.add(typeName);

  const symbolName = type.getSymbol()?.getName();
  if (symbolName) names.add(symbolName);

  const aliasName = type.aliasSymbol?.getName();
  if (aliasName) names.add(aliasName);

  if (type.isUnion()) {
    for (const member of type.types) {
      collectTypeNames(checker, names, member);
    }
  }
}

function collectNgTypeAliases(sourceFile) {
  const aliases = [];

  function visit(node, inNgNamespace = false) {
    const isNgNamespace =
      ts.isModuleDeclaration(node) &&
      ts.isIdentifier(node.name) &&
      node.name.text === "ng";

    if (inNgNamespace && ts.isTypeAliasDeclaration(node)) {
      aliases.push(node);
    }

    ts.forEachChild(node, (child) => visit(child, inNgNamespace || isNgNamespace));
  }

  visit(sourceFile);

  return aliases.sort((a, b) => a.name.text.localeCompare(b.name.text));
}

function isPrimitiveLike(type) {
  const flags = type.flags;

  return Boolean(
    flags &
      (ts.TypeFlags.StringLike |
        ts.TypeFlags.NumberLike |
        ts.TypeFlags.BooleanLike |
        ts.TypeFlags.BigIntLike |
        ts.TypeFlags.ESSymbolLike |
        ts.TypeFlags.Null |
        ts.TypeFlags.Undefined |
        ts.TypeFlags.Void)
  );
}

function isNativeType(type) {
  return isNativeDeclarations(type.getSymbol()?.declarations);
}

function isNativeProperty(property) {
  return isNativeDeclarations(property.declarations);
}

function isNativeDeclarations(declarations = []) {
  return (
    declarations.length > 0 &&
    declarations.every((declaration) => {
      const fileName = declaration.getSourceFile().fileName.replace(/\\/g, "/");
      return /\/node_modules\/typescript\/lib\/lib\.[^/]+\.d\.ts$/.test(fileName);
    })
  );
}

function callSignaturesOfType(checker, type) {
  const signatures = checker.getSignaturesOfType(type, ts.SignatureKind.Call);

  if (signatures.length > 0 || !type.isUnion()) return signatures;

  return nonNullableUnionMembers(type).flatMap((member) =>
    checker.getSignaturesOfType(member, ts.SignatureKind.Call)
  );
}

function renderClass(checker, overrides, typeName, type, properties, callSignatures) {
  const className = `GeneratedNg${typeName}`;
  const members = [];
  const usedNames = new Set();

  for (const signature of isSkipped(overrides, typeName, "call")
    ? []
    : callSignatures.slice(0, 1)) {
    usedNames.add("call");
    members.push(renderCallSignature(signature));
  }

  for (const property of properties) {
    const memberName = property.name;
    const declaration = property.valueDeclaration ?? property.declarations?.[0];
    const propertyType = checker.getTypeOfSymbolAtLocation(property, declaration);
    const signatures = callSignaturesOfType(checker, propertyType);
    const signature = signatures.find(Boolean);
    const dartName = uniqueMemberName(
      usedNames,
      memberDartName(overrides, typeName, memberName)
    );

    if (
      signature &&
      (isMethodDeclaration(declaration) ||
        matches(overrides.callableProperties, `${typeName}.${memberName}`))
    ) {
      members.push(
        renderMethod(checker, overrides, typeName, memberName, dartName, signatures)
      );
      continue;
    }

    members.push(
      renderGetter(checker, overrides, typeName, memberName, dartName, propertyType)
    );

    const setterType = writableScalarType(checker, overrides, propertyType);
    if (isWritableProperty(declaration) && setterType) {
      members.push(renderSetter(memberName, dartName, setterType));
    }
  }

  const body = members.length === 0 ? "" : `\n\n${members.join("\n\n")}`;

  return `/// Generated raw facade for ng.${typeName}.
base class ${className} extends GeneratedNgFacade {
  /// Creates a generated raw facade for ng.${typeName}.
  const ${className}(super.raw);${body}
}`;
}

function isMethodDeclaration(declaration) {
  return Boolean(
    declaration &&
      (ts.isMethodSignature(declaration) ||
        ts.isMethodDeclaration(declaration) ||
        ts.isMethodSignature(declaration.parent))
  );
}

function isWritableProperty(declaration) {
  return Boolean(
    declaration &&
      !declaration.modifiers?.some(
        (modifier) => modifier.kind === ts.SyntaxKind.ReadonlyKeyword
      )
  );
}

function renderCallSignature(signature) {
  return `${renderSignature("Object?", "call", signatureModel(null, {}, [signature]), {
    callExpression: (argsList) => {
      return `_callFunction(raw as JSFunction, ${argsList || "const <JSAny?>[]"})`;
    }
  })}`;
}

function renderMethod(checker, overrides, typeName, jsName, dartName, signatures) {
  const model = signatureModel(checker, overrides, signatures);
  const returnType = memberReturnType(
    overrides,
    typeName,
    jsName,
    model.returnType
  );

  return renderSignature(returnType, dartName, model, {
    callExpression: (argsList) => {
      const args = argsList || "const <JSAny?>[]";
      return convertExpression(
        returnType,
        `raw.callMethodVarArgs('${escapeDartString(jsName)}'.toJS, ${args})`
      );
    }
  });
}

function signatureModel(checker, overrides, signatures) {
  const signature = signatures
    .slice()
    .sort((a, b) => b.parameters.length - a.parameters.length)[0];
  const minArgumentCount = Math.min(
    ...signatures.map((candidate) => candidate.minArgumentCount)
  );
  const returnTypes =
    checker &&
    new Set(
      signatures.map((candidate) =>
        inferredReturnType(candidate.getReturnType(), checker, overrides)
      )
    );
  const returnType =
    returnTypes && returnTypes.size === 1 ? [...returnTypes][0] : "Object?";
  const parameters = signature.parameters.flatMap((parameter, index) => {
    const declaration = parameter.valueDeclaration ?? parameter.declarations?.[0];

    if (declaration?.dotDotDotToken) {
      return Array.from({ length: 4 }, (_, restIndex) => ({
        name: `arg${index + restIndex}`,
        optional: true,
        type: "Object?"
      }));
    }

    const optional = index >= minArgumentCount;

    return {
      name: `arg${index}`,
      optional,
      type:
        checker && declaration && !optional
          ? parameterDartType(
              checker,
              overrides,
              checker.getTypeOfSymbolAtLocation(parameter, declaration)
            )
          : "Object?"
    };
  });

  return { parameters, returnType };
}

function renderSignature(returnType, name, model, { callExpression }) {
  const parameters = model.parameters;
  const required = parameters.filter((parameter) => !parameter.optional);
  const optional = parameters.filter((parameter) => parameter.optional);
  const declaration = [
    ...required.map((parameter) => `${parameter.type} ${parameter.name}`),
    optional.length
      ? `[${optional.map((parameter) => `${parameter.type} ${parameter.name} = _undefinedArgument`).join(", ")}]`
      : null
  ]
    .filter(Boolean)
    .join(", ");
  const argsBuilder = renderArgsBuilder(parameters);
  const argsList = parameters.length === 0 ? "" : "args";

  const invocation = callExpression(argsList);
  const returnStatement =
    returnType === "void" ? `  ${invocation};` : `  return ${invocation};`;

  return `/// Invokes the generated ${name} member.
${returnType} ${name}(${declaration}) {
${argsBuilder}
${returnStatement}
}`;
}

function renderArgsBuilder(parameters) {
  if (parameters.length === 0) return "";

  const lines = ["  final args = <JSAny?>[];"];

  for (const parameter of parameters) {
    if (parameter.optional) {
      lines.push(
        `  if (!identical(${parameter.name}, _undefinedArgument)) args.add(unsafe.dartToJs(${parameter.name}));`
      );
    } else {
      lines.push(`  args.add(unsafe.dartToJs(${parameter.name}));`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function parameterDartType(checker, overrides, type) {
  if (type.getCallSignatures().length > 0) return "JSFunction";

  const direct = directTypeOverride(checker, overrides, type);
  if (direct) return direct;

  const primitive = primitiveParameterType(checker, overrides, type);
  return primitive ?? "Object?";
}

function primitiveParameterType(checker, overrides, type) {
  const members = nonNullableUnionMembers(type);

  if (members) {
    const memberTypes = members.map((member) =>
      primitiveParameterType(checker, overrides, member) ??
      directTypeOverride(checker, overrides, member)
    );
    if (memberTypes.includes(null)) return null;

    const uniqueTypes = new Set(memberTypes);

    if (uniqueTypes.size !== 1) return null;

    const [memberType] = uniqueTypes;
    return unionHasNullish(type) ? nullableDartType(memberType) : memberType;
  }

  if (type.flags & ts.TypeFlags.StringLike) return "String";
  if (type.flags & ts.TypeFlags.BooleanLike) return "bool";
  if (type.flags & ts.TypeFlags.NumberLike) return "num";

  return null;
}

function renderGetter(checker, overrides, typeName, jsName, dartName, propertyType) {
  const returnType = memberReturnType(
    overrides,
    typeName,
    jsName,
    inferredReturnType(propertyType, checker, overrides)
  );

  return `/// Reads the generated ${dartName} property.
${returnType} get ${dartName} => ${convertExpression(
    returnType,
    `raw.getProperty('${escapeDartString(jsName)}'.toJS)`
  )};`;
}

function renderSetter(jsName, dartName, valueType) {
  return `/// Writes the generated ${dartName} property.
set ${dartName}(${valueType} value) {
  raw.setProperty('${escapeDartString(jsName)}'.toJS, unsafe.dartToJs(value));
}`;
}

function writableScalarType(checker, overrides, propertyType) {
  const valueType = inferredReturnType(propertyType, checker, overrides);

  return /^(?:String|bool|num|int)\??$/.test(valueType) ? valueType : null;
}

function memberReturnType(overrides, typeName, memberName, inferredType) {
  return overrides.returnTypes?.[`${typeName}.${memberName}`] ?? inferredType;
}

function directTypeOverride(checker, overrides, type) {
  if (!checker) return null;

  const typeName = checker.typeToString(type);
  const symbolName = type.getSymbol()?.getName();
  const aliasName = type.aliasSymbol?.getName();

  return (
    overrides.types?.[typeName] ??
    overrides.types?.[symbolName] ??
    overrides.types?.[aliasName] ??
    null
  );
}

function inferredReturnType(type, checker, overrides) {
  if (promiseReturnType(type, checker)) return "JSPromise<JSAny?>";

  const direct = directTypeOverride(checker, overrides, type);
  if (direct) return direct;

  const primitive = primitiveReturnType(checker, overrides, type);
  return primitive ?? "Object?";
}

function promiseReturnType(type, checker) {
  const members = nonNullableUnionMembers(type);

  if (members) {
    return members.length > 0 && members.every((member) => promiseReturnType(member, checker));
  }

  const symbolName = type.getSymbol()?.getName();
  const aliasName = type.aliasSymbol?.getName();

  if (
    ["Promise", "PromiseLike", "HttpPromise", "TransitionPromise"].includes(symbolName) ||
    ["Promise", "PromiseLike", "HttpPromise", "TransitionPromise"].includes(aliasName)
  ) {
    return true;
  }

  const typeName = checker.typeToString(type);
  if (/^(Promise|PromiseLike|HttpPromise|TransitionPromise)(<|$)/.test(typeName)) {
    return true;
  }

  return (
    type.getBaseTypes?.()?.some((baseType) => promiseReturnType(baseType, checker)) ??
    false
  );
}

function primitiveReturnType(checker, overrides, type) {
  const members = nonNullableUnionMembers(type);

  if (members) {
    const memberTypes = members.map((member) =>
      primitiveReturnType(checker, overrides, member) ??
      directTypeOverride(checker, overrides, member)
    );
    if (memberTypes.includes(null)) return null;

    const uniqueTypes = new Set(memberTypes);

    if (uniqueTypes.size !== 1) return null;

    const [memberType] = uniqueTypes;
    return unionHasNullish(type) && memberType !== "void"
      ? nullableDartType(memberType)
      : memberType;
  }

  if (type.flags & ts.TypeFlags.StringLike) return "String";
  if (type.flags & ts.TypeFlags.BooleanLike) return "bool";
  if (type.flags & ts.TypeFlags.NumberLike) return "num";
  if (type.flags & ts.TypeFlags.Void) return "void";

  return null;
}

function nullableDartType(typeName) {
  return typeName.endsWith("?") ? typeName : `${typeName}?`;
}

function unionHasNullish(type) {
  return type.isUnion() && type.types.some((member) => isNullishType(member));
}

function nonNullableUnionMembers(type) {
  if (!type.isUnion()) return null;

  return type.types.filter((member) => !isNullishType(member));
}

function isNullishType(type) {
  return Boolean(
    type.flags & (ts.TypeFlags.Null | ts.TypeFlags.Undefined | ts.TypeFlags.Void)
  );
}

function convertExpression(returnType, expression) {
  switch (returnType) {
    case "JSPromise<JSAny?>":
      return `${expression} as JSPromise<JSAny?>`;
    case "bool":
      return `_toDartBool(${expression})!`;
    case "bool?":
      return `_toDartBool(${expression})`;
    case "String":
      return `_toDartString(${expression})!`;
    case "String?":
      return `_toDartString(${expression})`;
    case "num":
      return `_toDartNumber(${expression})!`;
    case "num?":
      return `_toDartNumber(${expression})`;
    case "int":
      return `_toDartInt(${expression})!`;
    case "int?":
      return `_toDartInt(${expression})`;
    case "Object?":
      return `unsafe.jsToDart<Object?>(${expression})`;
    default:
      return `unsafe.jsToDart<${returnType}>(${expression})`;
  }
}

function memberDartName(overrides, typeName, memberName) {
  const override = overrides.renames?.[`${typeName}.${memberName}`];
  if (override) return override;

  const clean = toLowerCamelName(memberName);
  let safeName = clean;

  if (safeName === "raw") safeName = "rawValue";
  if (safeName === "toString") safeName = "toStringMember";

  if (!dartReservedWords.has(safeName)) return safeName;

  return `${safeName}Member`;
}

function toLowerCamelName(memberName) {
  const clean = memberName.replace(/[^A-Za-z0-9_$]/g, "_");

  if (!clean) return "member";
  if (clean.startsWith("$")) return clean;

  const shouldCamelize = clean.includes("_") || /^[A-Z0-9_]+$/.test(clean);

  if (!shouldCamelize) {
    return /^[0-9]/.test(clean) ? `member${clean}` : clean;
  }

  const parts = clean.split("_").filter(Boolean);
  const camel = parts
    .map((part, index) => {
      const lower = part.toLowerCase();
      return index === 0 ? lower : `${lower[0].toUpperCase()}${lower.slice(1)}`;
    })
    .join("");

  return /^[0-9]/.test(camel) ? `member${camel}` : camel;
}

function uniqueMemberName(usedNames, name) {
  let uniqueName = name;
  let suffix = 2;

  while (usedNames.has(uniqueName)) {
    uniqueName = `${name}${suffix}`;
    suffix += 1;
  }

  usedNames.add(uniqueName);

  return uniqueName;
}

function isSkipped(overrides, typeName, memberName) {
  return skipStatus(overrides, typeName, memberName) !== null;
}

function skipStatus(overrides, typeName, memberName) {
  const key = `${typeName}.${memberName}`;

  if (matches(overrides.manual, key)) return "manual";
  if (matches(overrides.unsupported, key)) return "unsupported";

  return null;
}

function matches(patterns = [], key) {
  const [typeName] = key.split(".");

  return patterns.some((pattern) => pattern === key || pattern === `${typeName}.*`);
}

function escapeDartString(value) {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$");
}

function main() {
  const repoRoot = resolve(dirname(new URL(import.meta.url).pathname), "../../..");
  const outputPath = resolve(repoRoot, "integrations/dart/lib/src/generated/ng_facades.dart");
  const output = generateBindings({ repoRoot });

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, output);
  console.log(`Generated ${outputPath}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
