// Generated by utils/generate-programmatic-view-tags.mjs. Do not edit.
package angular.ts

import org.w3c.dom.Element

/** Creates a `a` element. */
public fun a(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "a",
    properties,
    *children,
)

/** Creates a `abbr` element. */
public fun abbr(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "abbr",
    properties,
    *children,
)

/** Creates a `address` element. */
public fun address(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "address",
    properties,
    *children,
)

/** Creates a `area` element. */
public fun area(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "area",
    properties,
    *children,
)

/** Creates a `article` element. */
public fun article(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "article",
    properties,
    *children,
)

/** Creates a `aside` element. */
public fun aside(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "aside",
    properties,
    *children,
)

/** Creates a `audio` element. */
public fun audio(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "audio",
    properties,
    *children,
)

/** Creates a `b` element. */
public fun b(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "b",
    properties,
    *children,
)

/** Creates a `base` element. */
public fun base(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "base",
    properties,
    *children,
)

/** Creates a `bdi` element. */
public fun bdi(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "bdi",
    properties,
    *children,
)

/** Creates a `bdo` element. */
public fun bdo(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "bdo",
    properties,
    *children,
)

/** Creates a `blockquote` element. */
public fun blockquote(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "blockquote",
    properties,
    *children,
)

/** Creates a `body` element. */
public fun body(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "body",
    properties,
    *children,
)

/** Creates a `br` element. */
public fun br(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "br",
    properties,
    *children,
)

/** Creates a `button` element. */
public fun button(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "button",
    properties,
    *children,
)

/** Creates a `canvas` element. */
public fun canvas(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "canvas",
    properties,
    *children,
)

/** Creates a `caption` element. */
public fun caption(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "caption",
    properties,
    *children,
)

/** Creates a `cite` element. */
public fun cite(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "cite",
    properties,
    *children,
)

/** Creates a `code` element. */
public fun code(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "code",
    properties,
    *children,
)

/** Creates a `col` element. */
public fun col(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "col",
    properties,
    *children,
)

/** Creates a `colgroup` element. */
public fun colgroup(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "colgroup",
    properties,
    *children,
)

/** Creates a `data` element. */
public fun data(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "data",
    properties,
    *children,
)

/** Creates a `datalist` element. */
public fun datalist(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "datalist",
    properties,
    *children,
)

/** Creates a `dd` element. */
public fun dd(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "dd",
    properties,
    *children,
)

/** Creates a `del` element. */
public fun del(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "del",
    properties,
    *children,
)

/** Creates a `details` element. */
public fun details(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "details",
    properties,
    *children,
)

/** Creates a `dfn` element. */
public fun dfn(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "dfn",
    properties,
    *children,
)

/** Creates a `dialog` element. */
public fun dialog(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "dialog",
    properties,
    *children,
)

/** Creates a `div` element. */
public fun div(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "div",
    properties,
    *children,
)

/** Creates a `dl` element. */
public fun dl(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "dl",
    properties,
    *children,
)

/** Creates a `dt` element. */
public fun dt(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "dt",
    properties,
    *children,
)

/** Creates a `em` element. */
public fun em(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "em",
    properties,
    *children,
)

/** Creates a `embed` element. */
public fun embed(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "embed",
    properties,
    *children,
)

/** Creates a `fieldset` element. */
public fun fieldset(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "fieldset",
    properties,
    *children,
)

/** Creates a `figcaption` element. */
public fun figcaption(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "figcaption",
    properties,
    *children,
)

/** Creates a `figure` element. */
public fun figure(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "figure",
    properties,
    *children,
)

/** Creates a `footer` element. */
public fun footer(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "footer",
    properties,
    *children,
)

/** Creates a `form` element. */
public fun form(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "form",
    properties,
    *children,
)

/** Creates a `h1` element. */
public fun h1(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "h1",
    properties,
    *children,
)

/** Creates a `h2` element. */
public fun h2(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "h2",
    properties,
    *children,
)

/** Creates a `h3` element. */
public fun h3(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "h3",
    properties,
    *children,
)

/** Creates a `h4` element. */
public fun h4(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "h4",
    properties,
    *children,
)

/** Creates a `h5` element. */
public fun h5(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "h5",
    properties,
    *children,
)

/** Creates a `h6` element. */
public fun h6(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "h6",
    properties,
    *children,
)

/** Creates a `head` element. */
public fun head(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "head",
    properties,
    *children,
)

/** Creates a `header` element. */
public fun header(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "header",
    properties,
    *children,
)

/** Creates a `hgroup` element. */
public fun hgroup(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "hgroup",
    properties,
    *children,
)

/** Creates a `hr` element. */
public fun hr(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "hr",
    properties,
    *children,
)

/** Creates a `html` element. */
public fun html(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "html",
    properties,
    *children,
)

/** Creates a `i` element. */
public fun i(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "i",
    properties,
    *children,
)

/** Creates a `iframe` element. */
public fun iframe(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "iframe",
    properties,
    *children,
)

/** Creates a `img` element. */
public fun img(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "img",
    properties,
    *children,
)

/** Creates a `input` element. */
public fun input(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "input",
    properties,
    *children,
)

/** Creates a `ins` element. */
public fun ins(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "ins",
    properties,
    *children,
)

/** Creates a `kbd` element. */
public fun kbd(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "kbd",
    properties,
    *children,
)

/** Creates a `label` element. */
public fun label(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "label",
    properties,
    *children,
)

/** Creates a `legend` element. */
public fun legend(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "legend",
    properties,
    *children,
)

/** Creates a `li` element. */
public fun li(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "li",
    properties,
    *children,
)

/** Creates a `link` element. */
public fun link(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "link",
    properties,
    *children,
)

/** Creates a `main` element. */
public fun main(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "main",
    properties,
    *children,
)

/** Creates a `map` element. */
public fun map(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "map",
    properties,
    *children,
)

/** Creates a `mark` element. */
public fun mark(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "mark",
    properties,
    *children,
)

/** Creates a `menu` element. */
public fun menu(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "menu",
    properties,
    *children,
)

/** Creates a `meta` element. */
public fun meta(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "meta",
    properties,
    *children,
)

/** Creates a `meter` element. */
public fun meter(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "meter",
    properties,
    *children,
)

/** Creates a `nav` element. */
public fun nav(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "nav",
    properties,
    *children,
)

/** Creates a `noscript` element. */
public fun noscript(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "noscript",
    properties,
    *children,
)

/** Creates a `object` element. */
public fun objectTag(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "object",
    properties,
    *children,
)

/** Creates a `ol` element. */
public fun ol(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "ol",
    properties,
    *children,
)

/** Creates a `optgroup` element. */
public fun optgroup(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "optgroup",
    properties,
    *children,
)

/** Creates a `option` element. */
public fun option(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "option",
    properties,
    *children,
)

/** Creates a `output` element. */
public fun output(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "output",
    properties,
    *children,
)

/** Creates a `p` element. */
public fun p(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "p",
    properties,
    *children,
)

/** Creates a `picture` element. */
public fun picture(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "picture",
    properties,
    *children,
)

/** Creates a `pre` element. */
public fun pre(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "pre",
    properties,
    *children,
)

/** Creates a `progress` element. */
public fun progress(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "progress",
    properties,
    *children,
)

/** Creates a `q` element. */
public fun q(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "q",
    properties,
    *children,
)

/** Creates a `rp` element. */
public fun rp(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "rp",
    properties,
    *children,
)

/** Creates a `rt` element. */
public fun rt(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "rt",
    properties,
    *children,
)

/** Creates a `ruby` element. */
public fun ruby(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "ruby",
    properties,
    *children,
)

/** Creates a `s` element. */
public fun s(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "s",
    properties,
    *children,
)

/** Creates a `samp` element. */
public fun samp(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "samp",
    properties,
    *children,
)

/** Creates a `script` element. */
public fun script(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "script",
    properties,
    *children,
)

/** Creates a `search` element. */
public fun search(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "search",
    properties,
    *children,
)

/** Creates a `section` element. */
public fun section(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "section",
    properties,
    *children,
)

/** Creates a `select` element. */
public fun select(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "select",
    properties,
    *children,
)

/** Creates a `slot` element. */
public fun slot(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "slot",
    properties,
    *children,
)

/** Creates a `small` element. */
public fun small(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "small",
    properties,
    *children,
)

/** Creates a `source` element. */
public fun source(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "source",
    properties,
    *children,
)

/** Creates a `span` element. */
public fun span(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "span",
    properties,
    *children,
)

/** Creates a `strong` element. */
public fun strong(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "strong",
    properties,
    *children,
)

/** Creates a `style` element. */
public fun style(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "style",
    properties,
    *children,
)

/** Creates a `sub` element. */
public fun sub(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "sub",
    properties,
    *children,
)

/** Creates a `summary` element. */
public fun summary(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "summary",
    properties,
    *children,
)

/** Creates a `sup` element. */
public fun sup(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "sup",
    properties,
    *children,
)

/** Creates a `table` element. */
public fun table(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "table",
    properties,
    *children,
)

/** Creates a `tbody` element. */
public fun tbody(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "tbody",
    properties,
    *children,
)

/** Creates a `td` element. */
public fun td(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "td",
    properties,
    *children,
)

/** Creates a `template` element. */
public fun template(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "template",
    properties,
    *children,
)

/** Creates a `textarea` element. */
public fun textarea(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "textarea",
    properties,
    *children,
)

/** Creates a `tfoot` element. */
public fun tfoot(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "tfoot",
    properties,
    *children,
)

/** Creates a `th` element. */
public fun th(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "th",
    properties,
    *children,
)

/** Creates a `thead` element. */
public fun thead(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "thead",
    properties,
    *children,
)

/** Creates a `time` element. */
public fun time(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "time",
    properties,
    *children,
)

/** Creates a `title` element. */
public fun title(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "title",
    properties,
    *children,
)

/** Creates a `tr` element. */
public fun tr(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "tr",
    properties,
    *children,
)

/** Creates a `track` element. */
public fun track(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "track",
    properties,
    *children,
)

/** Creates a `u` element. */
public fun u(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "u",
    properties,
    *children,
)

/** Creates a `ul` element. */
public fun ul(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "ul",
    properties,
    *children,
)

/** Creates a `var` element. */
public fun varTag(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "var",
    properties,
    *children,
)

/** Creates a `video` element. */
public fun video(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "video",
    properties,
    *children,
)

/** Creates a `wbr` element. */
public fun wbr(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "wbr",
    properties,
    *children,
)

/** Creates a `acronym` element. */
public fun acronym(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "acronym",
    properties,
    *children,
)

/** Creates a `applet` element. */
public fun applet(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "applet",
    properties,
    *children,
)

/** Creates a `basefont` element. */
public fun basefont(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "basefont",
    properties,
    *children,
)

/** Creates a `bgsound` element. */
public fun bgsound(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "bgsound",
    properties,
    *children,
)

/** Creates a `big` element. */
public fun big(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "big",
    properties,
    *children,
)

/** Creates a `blink` element. */
public fun blink(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "blink",
    properties,
    *children,
)

/** Creates a `center` element. */
public fun center(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "center",
    properties,
    *children,
)

/** Creates a `dir` element. */
public fun dir(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "dir",
    properties,
    *children,
)

/** Creates a `font` element. */
public fun font(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "font",
    properties,
    *children,
)

/** Creates a `frame` element. */
public fun frame(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "frame",
    properties,
    *children,
)

/** Creates a `frameset` element. */
public fun frameset(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "frameset",
    properties,
    *children,
)

/** Creates a `isindex` element. */
public fun isindex(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "isindex",
    properties,
    *children,
)

/** Creates a `keygen` element. */
public fun keygen(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "keygen",
    properties,
    *children,
)

/** Creates a `listing` element. */
public fun listing(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "listing",
    properties,
    *children,
)

/** Creates a `marquee` element. */
public fun marquee(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "marquee",
    properties,
    *children,
)

/** Creates a `menuitem` element. */
public fun menuitem(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "menuitem",
    properties,
    *children,
)

/** Creates a `multicol` element. */
public fun multicol(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "multicol",
    properties,
    *children,
)

/** Creates a `nextid` element. */
public fun nextid(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "nextid",
    properties,
    *children,
)

/** Creates a `nobr` element. */
public fun nobr(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "nobr",
    properties,
    *children,
)

/** Creates a `noembed` element. */
public fun noembed(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "noembed",
    properties,
    *children,
)

/** Creates a `noframes` element. */
public fun noframes(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "noframes",
    properties,
    *children,
)

/** Creates a `param` element. */
public fun param(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "param",
    properties,
    *children,
)

/** Creates a `plaintext` element. */
public fun plaintext(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "plaintext",
    properties,
    *children,
)

/** Creates a `rb` element. */
public fun rb(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "rb",
    properties,
    *children,
)

/** Creates a `rtc` element. */
public fun rtc(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "rtc",
    properties,
    *children,
)

/** Creates a `spacer` element. */
public fun spacer(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "spacer",
    properties,
    *children,
)

/** Creates a `strike` element. */
public fun strike(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "strike",
    properties,
    *children,
)

/** Creates a `tt` element. */
public fun tt(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "tt",
    properties,
    *children,
)

/** Creates a `xmp` element. */
public fun xmp(
    properties: Map<String, Any?> = emptyMap(),
    vararg children: Any?,
): Element = ProgrammaticTags(angularRuntime.view.tags).tag(
    "xmp",
    properties,
    *children,
)
