package angular.ts

object Tokens:
  val anchorScroll: Token[AnchorScrollService] = AngularTS.token("$anchorScroll")
  val animate: Token[AnimateService] = AngularTS.token("$animate")
  val aria: Token[AriaService] = AngularTS.token("$aria")
  val compile: Token[CompileService] = AngularTS.token("$compile")
  val controller: Token[ControllerService] = AngularTS.token("$controller")
  val document: Token[org.scalajs.dom.Document] = AngularTS.token("$document")
  val element: Token[org.scalajs.dom.Element] = AngularTS.token("$element")
  val exceptionHandler: Token[ExceptionHandlerService] =
    AngularTS.token("$exceptionHandler")
  val filter: Token[FilterService] = AngularTS.token("$filter")
  val http: Token[HttpService] = AngularTS.token("$http")
  val httpParamSerializer: Token[HttpParamSerializerService] =
    AngularTS.token("$httpParamSerializer")
  val interpolate: Token[InterpolateService] = AngularTS.token("$interpolate")
  val parse: Token[ParseService] = AngularTS.token("$parse")
  val rootScope: Token[Scope] = AngularTS.token("$rootScope")
  val rootElement: Token[org.scalajs.dom.Element] = AngularTS.token("$rootElement")
  val scope: Token[Scope] = AngularTS.token("$scope")
  val templateCache: Token[TemplateCacheService] = AngularTS.token("$templateCache")
  val templateRequest: Token[TemplateRequestService] =
    AngularTS.token("$templateRequest")
  val window: Token[org.scalajs.dom.Window] = AngularTS.token("$window")
  val log: Token[LogService] = AngularTS.token("$log")
  val location: Token[LocationService] = AngularTS.token("$location")
  val cookie: Token[CookieService] = AngularTS.token("$cookie")
  val eventBus: Token[PubSubService] = AngularTS.token("$eventBus")
  val machine: Token[MachineService] = AngularTS.token("$machine")
  val rest: Token[RestFactory] = AngularTS.token("$rest")
  val security: Token[SecurityPolicyService] = AngularTS.token("$security")
  val serviceWorker: Token[ServiceWorkerService] = AngularTS.token("$serviceWorker")
  val sce: Token[SceService] = AngularTS.token("$sce")
  val sceDelegate: Token[SceDelegateService] = AngularTS.token("$sceDelegate")
  val stream: Token[StreamService] = AngularTS.token("$stream")
  val sse: Token[SseService] = AngularTS.token("$sse")
  val state: Token[StateService] = AngularTS.token("$state")
  val transitions: Token[TransitionService] = AngularTS.token("$transitions")
  val view: Token[ViewService] = AngularTS.token("$view")
  val wasm: Token[WasmService] = AngularTS.token("$wasm")
  val websocket: Token[WebSocketService] = AngularTS.token("$websocket")
  val webTransport: Token[WebTransportService] = AngularTS.token("$webTransport")
  val webComponent: Token[WebComponentService] = AngularTS.token("$webComponent")
  val worker: Token[WorkerService] = AngularTS.token("$worker")
  val workflow: Token[WorkflowService] = AngularTS.token("$workflow")
