#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

const repoRoot = path.resolve(import.meta.dirname, "../../..");
const namespacePath = path.join(repoRoot, "@types/namespace.d.ts");
const typesRoot = path.join(repoRoot, "@types");
const outputPath = path.join(
  repoRoot,
  "integrations/kotlin/src/jsMain/kotlin/angular/ts/generated/NgFacades.kt",
);
const overridesPath = path.join(
  repoRoot,
  "integrations/kotlin/tool/generator-overrides.json",
);

const kotlinReservedWords = new Set([
  "as",
  "break",
  "class",
  "continue",
  "do",
  "else",
  "false",
  "for",
  "fun",
  "if",
  "in",
  "interface",
  "is",
  "null",
  "object",
  "package",
  "return",
  "super",
  "this",
  "throw",
  "true",
  "try",
  "typealias",
  "typeof",
  "val",
  "var",
  "when",
  "while",
]);

export function generateBindings({
  namespaceFile = namespacePath,
  overridesFile = overridesPath,
} = {}) {
  const overrides = JSON.parse(fs.readFileSync(overridesFile, "utf8"));
  const types = extractNamespaceTypes(namespaceFile, overrides);

  return renderKotlin(types);
}

function extractNamespaceTypes(sourcePath, overrides) {
  const program = ts.createProgram([sourcePath], {
    allowJs: false,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.Latest,
  });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(sourcePath);
  const types = [];

  if (!sourceFile) {
    throw new Error(
      `Unable to read generated namespace declarations at ${sourcePath}. ` +
        "Run `make types` from the repository root first.",
    );
  }

  function visit(node, inNgNamespace = false) {
    if (ts.isModuleDeclaration(node)) {
      const nextInNgNamespace =
        inNgNamespace ||
        (ts.isIdentifier(node.name) && node.name.escapedText.toString() === "ng");

      if (node.body) visit(node.body, nextInNgNamespace);
      return;
    }

    if (inNgNamespace && ts.isTypeAliasDeclaration(node)) {
      const typeName = node.name.escapedText.toString();
      const type = checker.getTypeFromTypeNode(node.type);

      types.push({
        name: typeName,
        typeParameters:
          node.typeParameters?.map((parameter) =>
            safeKotlinIdentifier(parameter.name.escapedText.toString()),
          ) ?? [],
        members: collectMembers(checker, overrides, typeName, type),
      });
      return;
    }

    ts.forEachChild(node, (child) => visit(child, inNgNamespace));
  }

  visit(sourceFile);
  return types;
}

function collectMembers(checker, overrides, typeName, type) {
  const members = [];
  const callableProperties = new Set(overrides.callableProperties ?? []);
  const manual = new Set(overrides.manual ?? []);
  const unsupported = new Set(overrides.unsupported ?? []);

  const callSignature = signatureWithMostParameters(
    checker
      .getSignaturesOfType(type, ts.SignatureKind.Call)
      .filter((signature) => isRepoTypesNode(signature.declaration)),
  );

  if (
    callSignature &&
    !skippedByOverride(typeName, "call", manual, unsupported)
  ) {
    members.push({
      kind: "invoke",
      name: "invoke",
      parameters: signatureParameters(checker, overrides, callSignature),
      returnType: returnType(checker, overrides, typeName, "call", callSignature),
    });
  }

  for (const property of type.getProperties()) {
    const declaration = property.valueDeclaration ?? property.declarations?.[0];

    if (property.name === "__type" || !isRepoTypesNode(declaration)) continue;
    if (!isPublicDeclaration(declaration)) continue;
    if (skippedByOverride(typeName, property.name, manual, unsupported)) continue;

    const propertyType = checker.getTypeOfSymbolAtLocation(property, declaration);
    const signatures = checker.getSignaturesOfType(
      propertyType,
      ts.SignatureKind.Call,
    );
    const signature = signatureWithMostParameters(signatures);
    const forcedCallable = callableProperties.has(`${typeName}.${property.name}`);

    if (ts.isMethodSignature(declaration) || forcedCallable || signature) {
      members.push({
        kind: "function",
        name: renameMember(overrides, typeName, property.name),
        parameters: signature
          ? signatureParameters(checker, overrides, signature)
          : [],
        returnType: signature
          ? returnType(checker, overrides, typeName, property.name, signature)
          : "dynamic",
      });
    } else {
      members.push({
        kind: "property",
        name: renameMember(overrides, typeName, property.name),
        type: kotlinType(checker, overrides, propertyType),
      });
    }
  }

  return members.sort((left, right) => {
    const nameOrder = left.name.localeCompare(right.name);
    if (nameOrder !== 0) return nameOrder;
    return left.kind.localeCompare(right.kind);
  });
}

function renderKotlin(types) {
  const lines = [
    "// Generated by integrations/kotlin/tool/generate_kotlin_bindings.mjs.",
    "// Do not edit by hand.",
    "",
    "@file:Suppress(",
    "    \"NO_EXTERNAL_DECLARATION_IN_NON_EXTERNAL_CLASSIFIER\",",
    "    \"WRONG_EXPORTED_DECLARATION\",",
    "    \"NESTED_CLASS_IN_EXTERNAL_INTERFACE\",",
    ")",
    "",
    "package angular.ts.generated",
    "",
  ];

  for (const type of types) {
    const typeParameters =
      type.typeParameters.length > 0 ? `<${type.typeParameters.join(", ")}>` : "";

    if (type.members.length === 0) {
      lines.push(`public external interface ${safeKotlinIdentifier(type.name)}${typeParameters}`);
      lines.push("");
      continue;
    }

    lines.push(`public external interface ${safeKotlinIdentifier(type.name)}${typeParameters} {`);

    for (const member of type.members) {
      lines.push(`    ${renderMember(member)}`);
    }

    lines.push("}");
    lines.push("");
  }

  if (lines.at(-1) === "") lines.pop();
  return `${lines.join("\n")}\n`;
}

function safeKotlinIdentifier(value) {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(value) && !kotlinReservedWords.has(value)) {
    return value;
  }

  return `\`${value.replaceAll("`", "\\`")}\``;
}

function renderMember(member) {
  if (member.kind === "function" && member.name === "toString" && member.parameters.length === 0) {
    return "public override fun toString(): String";
  }

  if (member.kind === "property") {
    return `public var ${safeKotlinIdentifier(member.name)}: ${member.type}`;
  }

  const parameters = member.parameters
    .map((parameter, index) => renderParameter(parameter, index))
    .join(", ");
  const prefix = member.kind === "invoke" ? "public operator fun" : "public fun";

  return `${prefix} ${safeKotlinIdentifier(member.name)}(${parameters}): ${member.returnType}`;
}

function renderParameter(parameter, index) {
  if (parameter.rest) return `vararg p${index}: ${parameter.restType}`;
  return `p${index}: ${parameter.type} = definedExternally`;
}

function signatureWithMostParameters(signatures) {
  return signatures.reduce((selected, signature) => {
    if (!selected) return signature;
    return signature.parameters.length > selected.parameters.length
      ? signature
      : selected;
  }, undefined);
}

function signatureParameters(checker, overrides, signature) {
  return signature.parameters.map((parameter) => {
    const declaration = parameter.valueDeclaration ?? parameter.declarations?.[0];
    const parameterType = declaration
      ? checker.getTypeOfSymbolAtLocation(parameter, declaration)
      : undefined;

    return {
      rest: Boolean(declaration && ts.isParameter(declaration) && declaration.dotDotDotToken),
      type: parameterType ? kotlinType(checker, overrides, parameterType) : "dynamic",
      restType: parameterType
        ? kotlinArrayElementType(checker, overrides, parameterType)
        : "dynamic",
    };
  });
}

function returnType(checker, overrides, typeName, memberName, signature) {
  const override = overrides.returnTypes?.[`${typeName}.${memberName}`];
  if (override) return override;

  return kotlinType(checker, overrides, checker.getReturnTypeOfSignature(signature));
}

function kotlinType(checker, overrides, type) {
  const typeName = symbolName(type);
  if (typeName && overrides.types?.[typeName]) return overrides.types[typeName];

  if (type.flags & ts.TypeFlags.StringLike) return "String";
  if (type.flags & ts.TypeFlags.BooleanLike) return "Boolean";
  if (type.flags & ts.TypeFlags.NumberLike) return "Double";
  if (type.flags & ts.TypeFlags.Void) return "Unit";
  if (type.flags & ts.TypeFlags.Null) return "Nothing?";
  if (type.flags & ts.TypeFlags.Undefined) return "Nothing?";
  if (type.flags & ts.TypeFlags.Any) return "dynamic";
  if (type.flags & ts.TypeFlags.Unknown) return "dynamic";

  if (type.isUnion()) {
    const nonEmpty = type.types.filter(
      (part) =>
        !(part.flags & ts.TypeFlags.Null) &&
        !(part.flags & ts.TypeFlags.Undefined),
    );

    if (nonEmpty.length === 1) return nullableKotlinType(kotlinType(checker, overrides, nonEmpty[0]));

    return "dynamic";
  }

  const signatures = checker.getSignaturesOfType(type, ts.SignatureKind.Call);
  if (signatures.length > 0) {
    return kotlinFunctionType(checker, overrides, signatureWithMostParameters(signatures));
  }

  if (checker.isArrayType(type) || checker.isTupleType(type)) {
    return `Array<${kotlinArrayElementType(checker, overrides, type)}>`;
  }

  return "dynamic";
}

function nullableKotlinType(type) {
  if (type === "Unit") return "Unit";
  return type.includes("->") ? `(${type})?` : `${type}?`;
}

function kotlinFunctionType(checker, overrides, signature) {
  if (!signature || signature.parameters.length > 5) return "Function<*>";

  const parameters = signature.parameters.map((parameter) => {
    const declaration = parameter.valueDeclaration ?? parameter.declarations?.[0];

    if (declaration && ts.isParameter(declaration) && declaration.dotDotDotToken) {
      return undefined;
    }

    const parameterType = declaration
      ? checker.getTypeOfSymbolAtLocation(parameter, declaration)
      : undefined;

    return parameterType ? kotlinType(checker, overrides, parameterType) : "dynamic";
  });

  if (parameters.some((parameter) => !parameter)) return "Function<*>";

  return `(${parameters.join(", ")}) -> ${kotlinType(
    checker,
    overrides,
    checker.getReturnTypeOfSignature(signature),
  )}`;
}

function kotlinArrayElementType(checker, overrides, type) {
  if (checker.isTupleType(type)) {
    const tupleTypes = checker.getTypeArguments(type);
    if (tupleTypes.length === 1) return kotlinType(checker, overrides, tupleTypes[0]);
    return "dynamic";
  }

  const elementType =
    checker.getElementTypeOfArrayType?.(type) ??
    checker.getTypeArguments(type)?.[0];

  return elementType ? kotlinType(checker, overrides, elementType) : "dynamic";
}

function symbolName(type) {
  return type.aliasSymbol?.getName() ?? type.symbol?.getName();
}

function skippedByOverride(typeName, memberName, ...sets) {
  const key = `${typeName}.${memberName}`;
  const wildcard = `${typeName}.*`;

  return sets.some((set) => set.has(key) || set.has(wildcard));
}

function renameMember(overrides, typeName, memberName) {
  return overrides.renames?.[`${typeName}.${memberName}`] ?? memberName;
}

function isRepoTypesNode(node) {
  return Boolean(
    node &&
      path
        .resolve(node.getSourceFile().fileName)
        .startsWith(`${path.resolve(typesRoot)}${path.sep}`),
  );
}

function isPublicDeclaration(node) {
  return !node.modifiers?.some(
    (modifier) =>
      modifier.kind === ts.SyntaxKind.PrivateKeyword ||
      modifier.kind === ts.SyntaxKind.ProtectedKeyword,
  );
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, generateBindings());
}
