/// Template source used by a Rust-authored AngularTS component.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TemplateSource {
    Inline(&'static str),
    Url(&'static str),
}

/// Component metadata consumed by generated AngularTS glue.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ComponentMetadata {
    selector: &'static str,
    template: TemplateSource,
    injections: &'static [InjectionMetadata],
}

impl ComponentMetadata {
    /// Creates metadata for a component with an inline template.
    pub const fn inline(selector: &'static str, template: &'static str) -> Self {
        Self::inline_with_injections(selector, template, &[])
    }

    /// Creates metadata for a component with an inline template and injections.
    pub const fn inline_with_injections(
        selector: &'static str,
        template: &'static str,
        injections: &'static [InjectionMetadata],
    ) -> Self {
        Self {
            selector,
            template: TemplateSource::Inline(template),
            injections,
        }
    }

    /// Creates metadata for a component with an external template URL.
    pub const fn template_url(selector: &'static str, template_url: &'static str) -> Self {
        Self::template_url_with_injections(selector, template_url, &[])
    }

    /// Creates metadata for a component with an external template URL and injections.
    pub const fn template_url_with_injections(
        selector: &'static str,
        template_url: &'static str,
        injections: &'static [InjectionMetadata],
    ) -> Self {
        Self {
            selector,
            template: TemplateSource::Url(template_url),
            injections,
        }
    }

    pub const fn selector(&self) -> &'static str {
        self.selector
    }

    pub const fn template(&self) -> TemplateSource {
        self.template
    }

    pub const fn injections(&self) -> &'static [InjectionMetadata] {
        self.injections
    }
}

/// Marker trait generated by `#[component]`.
pub trait ComponentController {
    const NAME: &'static str;
    const METADATA: ComponentMetadata;
    const EXPORT_NAME: &'static str;
}

/// Field injection metadata generated from `#[inject]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InjectionMetadata {
    field: &'static str,
    token: &'static str,
    rust_type: &'static str,
}

impl InjectionMetadata {
    pub const fn new(field: &'static str, token: &'static str, rust_type: &'static str) -> Self {
        Self {
            field,
            token,
            rust_type,
        }
    }

    pub const fn field(&self) -> &'static str {
        self.field
    }

    pub const fn token(&self) -> &'static str {
        self.token
    }

    pub const fn rust_type(&self) -> &'static str {
        self.rust_type
    }
}
