// Generated by integrations/android/scripts/generate-native-capabilities.mjs.
// Do not edit directly.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum NativeCapabilityName {
    Navigation,
    Platform,
    Permissions,
    Clipboard,
    Sharing,
    Intents,
    Haptics,
    Connectivity,
    Lifecycle,
    Window,
    Notifications,
    Geolocation,
    Biometrics,
    Camera,
    Files,
    Credentials,
    Media,
}

impl NativeCapabilityName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Navigation => "navigation",
            Self::Platform => "platform",
            Self::Permissions => "permissions",
            Self::Clipboard => "clipboard",
            Self::Sharing => "sharing",
            Self::Intents => "intents",
            Self::Haptics => "haptics",
            Self::Connectivity => "connectivity",
            Self::Lifecycle => "lifecycle",
            Self::Window => "window",
            Self::Notifications => "notifications",
            Self::Geolocation => "geolocation",
            Self::Biometrics => "biometrics",
            Self::Camera => "camera",
            Self::Files => "files",
            Self::Credentials => "credentials",
            Self::Media => "media",
        }
    }

    pub const fn methods(self) -> &'static [&'static str] {
        match self {
            Self::Navigation => &[
                "status",
                "push",
                "replace",
                "pop",
                "modal",
                "deep-link",
                "external",
            ],
            Self::Platform => &["status"],
            Self::Permissions => &["status", "request"],
            Self::Clipboard => &["read", "write"],
            Self::Sharing => &["share"],
            Self::Intents => &["open"],
            Self::Haptics => &["perform"],
            Self::Connectivity => &["status", "watch", "unwatch"],
            Self::Lifecycle => &["status", "watch", "unwatch"],
            Self::Window => &["status", "watch", "unwatch"],
            Self::Notifications => &["status", "open-settings"],
            Self::Geolocation => &["status", "current"],
            Self::Biometrics => &["status"],
            Self::Camera => &["status", "capture"],
            Self::Files => &["status", "open", "upload"],
            Self::Credentials => &[
                "status",
                "get",
                "create-password",
                "create-passkey",
                "clear",
            ],
            Self::Media => &["status", "load", "play", "pause", "stop", "seek", "release"],
        }
    }

    pub const fn events(self) -> &'static [&'static str] {
        match self {
            Self::Navigation => &["change"],
            Self::Platform => &[],
            Self::Permissions => &[],
            Self::Clipboard => &[],
            Self::Sharing => &[],
            Self::Intents => &[],
            Self::Haptics => &[],
            Self::Connectivity => &["change"],
            Self::Lifecycle => &["change"],
            Self::Window => &["change"],
            Self::Notifications => &[],
            Self::Geolocation => &[],
            Self::Biometrics => &[],
            Self::Camera => &[],
            Self::Files => &["progress"],
            Self::Credentials => &[],
            Self::Media => &[],
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NativeCapabilityDescriptor {
    pub name: NativeCapabilityName,
    pub artifact: &'static str,
    pub availability: &'static str,
    pub threading: &'static str,
    pub lifecycle: &'static str,
    pub error_protocol: &'static str,
    pub min_sdk: u32,
    pub permission: Option<&'static str>,
    pub methods: &'static [&'static str],
    pub events: &'static [&'static str],
}

pub mod navigation {
    pub const NAME: &str = "navigation";
    pub const STATUS: &str = "status";
    pub const PUSH: &str = "push";
    pub const REPLACE: &str = "replace";
    pub const POP: &str = "pop";
    pub const MODAL: &str = "modal";
    pub const DEEP_LINK: &str = "deep-link";
    pub const EXTERNAL: &str = "external";
    pub const EVENT_CHANGE: &str = "change";
}

pub mod platform {
    pub const NAME: &str = "platform";
    pub const STATUS: &str = "status";
}

pub mod permissions {
    pub const NAME: &str = "permissions";
    pub const STATUS: &str = "status";
    pub const REQUEST: &str = "request";
}

pub mod clipboard {
    pub const NAME: &str = "clipboard";
    pub const READ: &str = "read";
    pub const WRITE: &str = "write";
}

pub mod sharing {
    pub const NAME: &str = "sharing";
    pub const SHARE: &str = "share";
}

pub mod intents {
    pub const NAME: &str = "intents";
    pub const OPEN: &str = "open";
}

pub mod haptics {
    pub const NAME: &str = "haptics";
    pub const PERFORM: &str = "perform";
}

pub mod connectivity {
    pub const NAME: &str = "connectivity";
    pub const STATUS: &str = "status";
    pub const WATCH: &str = "watch";
    pub const UNWATCH: &str = "unwatch";
    pub const EVENT_CHANGE: &str = "change";
}

pub mod lifecycle {
    pub const NAME: &str = "lifecycle";
    pub const STATUS: &str = "status";
    pub const WATCH: &str = "watch";
    pub const UNWATCH: &str = "unwatch";
    pub const EVENT_CHANGE: &str = "change";
}

pub mod window {
    pub const NAME: &str = "window";
    pub const STATUS: &str = "status";
    pub const WATCH: &str = "watch";
    pub const UNWATCH: &str = "unwatch";
    pub const EVENT_CHANGE: &str = "change";
}

pub mod notifications {
    pub const NAME: &str = "notifications";
    pub const STATUS: &str = "status";
    pub const OPEN_SETTINGS: &str = "open-settings";
}

pub mod geolocation {
    pub const NAME: &str = "geolocation";
    pub const STATUS: &str = "status";
    pub const CURRENT: &str = "current";
}

pub mod biometrics {
    pub const NAME: &str = "biometrics";
    pub const STATUS: &str = "status";
}

pub mod camera {
    pub const NAME: &str = "camera";
    pub const STATUS: &str = "status";
    pub const CAPTURE: &str = "capture";
}

pub mod files {
    pub const NAME: &str = "files";
    pub const STATUS: &str = "status";
    pub const OPEN: &str = "open";
    pub const UPLOAD: &str = "upload";
    pub const EVENT_PROGRESS: &str = "progress";
}

pub mod credentials {
    pub const NAME: &str = "credentials";
    pub const STATUS: &str = "status";
    pub const GET: &str = "get";
    pub const CREATE_PASSWORD: &str = "create-password";
    pub const CREATE_PASSKEY: &str = "create-passkey";
    pub const CLEAR: &str = "clear";
}

pub mod media {
    pub const NAME: &str = "media";
    pub const STATUS: &str = "status";
    pub const LOAD: &str = "load";
    pub const PLAY: &str = "play";
    pub const PAUSE: &str = "pause";
    pub const STOP: &str = "stop";
    pub const SEEK: &str = "seek";
    pub const RELEASE: &str = "release";
}

pub const NATIVE_CAPABILITIES: &[NativeCapabilityDescriptor] = &[
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Navigation,
        artifact: "navigation",
        availability: "required",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &[
            "status",
            "push",
            "replace",
            "pop",
            "modal",
            "deep-link",
            "external",
        ],
        events: &["change"],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Platform,
        artifact: "navigation",
        availability: "required",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Permissions,
        artifact: "navigation",
        availability: "required",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status", "request"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Clipboard,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["read", "write"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Sharing,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["share"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Intents,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["open"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Haptics,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["perform"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Connectivity,
        artifact: "navigation",
        availability: "required",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: Some("android.permission.ACCESS_NETWORK_STATE"),
        methods: &["status", "watch", "unwatch"],
        events: &["change"],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Lifecycle,
        artifact: "navigation",
        availability: "required",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status", "watch", "unwatch"],
        events: &["change"],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Window,
        artifact: "navigation",
        availability: "required",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status", "watch", "unwatch"],
        events: &["change"],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Notifications,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: Some("android.permission.POST_NOTIFICATIONS"),
        methods: &["status", "open-settings"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Geolocation,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: Some("android.permission.ACCESS_FINE_LOCATION"),
        methods: &["status", "current"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Biometrics,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Camera,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: Some("android.permission.CAMERA"),
        methods: &["status", "capture"],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Files,
        artifact: "navigation",
        availability: "device",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status", "open", "upload"],
        events: &["progress"],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Credentials,
        artifact: "credentials",
        availability: "optional",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &[
            "status",
            "get",
            "create-password",
            "create-passkey",
            "clear",
        ],
        events: &[],
    },
    NativeCapabilityDescriptor {
        name: NativeCapabilityName::Media,
        artifact: "media",
        availability: "optional",
        threading: "main",
        lifecycle: "destination",
        error_protocol: "native-bridge-v1",
        min_sdk: 28,
        permission: None,
        methods: &["status", "load", "play", "pause", "stop", "seek", "release"],
        events: &[],
    },
];
