//! Marker facades for AngularTS services.
//!
//! Method-level service coverage will be added as namespace parity expands.

/// Marker trait generated by `#[service]`.
pub trait Service {
    const TOKEN_NAME: &'static str;
    const EXPORT_NAME: &'static str;
}

#[derive(Debug, Clone, Copy)]
pub struct HttpService;

impl Service for HttpService {
    const TOKEN_NAME: &'static str = "$http";
    const EXPORT_NAME: &'static str = "__ng_service_HttpService";
}

#[derive(Debug, Clone, Copy)]
pub struct LogService;

impl Service for LogService {
    const TOKEN_NAME: &'static str = "$log";
    const EXPORT_NAME: &'static str = "__ng_service_LogService";
}

#[derive(Debug, Clone, Copy)]
pub struct ExceptionHandlerService;

impl Service for ExceptionHandlerService {
    const TOKEN_NAME: &'static str = "$exceptionHandler";
    const EXPORT_NAME: &'static str = "__ng_service_ExceptionHandlerService";
}

#[derive(Debug, Clone, Copy)]
pub struct RootScopeService;

impl Service for RootScopeService {
    const TOKEN_NAME: &'static str = "$rootScope";
    const EXPORT_NAME: &'static str = "__ng_service_RootScopeService";
}

#[derive(Debug, Clone, Copy)]
pub struct EventBusService;

impl Service for EventBusService {
    const TOKEN_NAME: &'static str = "$eventBus";
    const EXPORT_NAME: &'static str = "__ng_service_EventBusService";
}

/// Public `ng.PubSubService` facade. `$eventBus` uses this runtime shape.
pub type PubSubService = EventBusService;
