//! Rust facades for selected AngularTS services.
//!
//! These types intentionally expose only the MVP method surface. Browser runtime
//! calls are available on `wasm32` through `wasm-bindgen` extern bindings; host
//! tests use the portable data types and service token metadata.

#[cfg(not(target_arch = "wasm32"))]
use std::collections::HashMap;

/// Marker trait generated by `#[service]`.
pub trait Service {
    const TOKEN_NAME: &'static str;
    const EXPORT_NAME: &'static str;
}

/// Built-in persistent storage backends understood by AngularTS store registration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StorageType {
    Local,
    Session,
    Cookie,
    Custom,
}

impl StorageType {
    /// Returns the storage type string used by AngularTS metadata.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::Session => "session",
            Self::Cookie => "cookie",
            Self::Custom => "custom",
        }
    }
}

/// Rust trait equivalent of the public AngularTS `StorageBackend` interface.
pub trait StorageBackend {
    /// Reads a stored serialized value.
    fn get(&self, key: &str) -> Option<String>;

    /// Stores a serialized value.
    fn set(&mut self, key: &str, value: &str);

    /// Removes a stored value.
    fn remove(&mut self, key: &str);
}

/// In-memory storage backend useful for tests and custom Rust stores.
#[cfg(not(target_arch = "wasm32"))]
#[derive(Debug, Clone, Default)]
pub struct MemoryStorageBackend {
    values: HashMap<String, String>,
}

#[cfg(not(target_arch = "wasm32"))]
impl MemoryStorageBackend {
    /// Creates an empty memory storage backend.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns stored key count.
    pub fn len(&self) -> usize {
        self.values.len()
    }

    /// Returns whether the backend is empty.
    pub fn is_empty(&self) -> bool {
        self.values.is_empty()
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl StorageBackend for MemoryStorageBackend {
    fn get(&self, key: &str) -> Option<String> {
        self.values.get(key).cloned()
    }

    fn set(&mut self, key: &str, value: &str) {
        self.values.insert(key.to_string(), value.to_string());
    }

    fn remove(&mut self, key: &str) {
        self.values.remove(key);
    }
}

/// SameSite policy applied by the browser for a cookie write.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CookieSameSite {
    Lax,
    Strict,
    None,
}

impl CookieSameSite {
    /// Returns the SameSite string used by AngularTS cookie options.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Lax => "Lax",
            Self::Strict => "Strict",
            Self::None => "None",
        }
    }
}

/// Rust representation of AngularTS cookie write options.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct CookieOptions {
    path: Option<String>,
    domain: Option<String>,
    expires: Option<String>,
    secure: bool,
    same_site: Option<CookieSameSite>,
}

impl CookieOptions {
    /// Creates empty cookie options.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns the cookie path, when set.
    pub fn path(&self) -> Option<&str> {
        self.path.as_deref()
    }

    /// Returns the cookie domain, when set.
    pub fn domain(&self) -> Option<&str> {
        self.domain.as_deref()
    }

    /// Returns the cookie expiration value, when set.
    pub fn expires(&self) -> Option<&str> {
        self.expires.as_deref()
    }

    /// Returns whether the cookie should be restricted to HTTPS.
    pub const fn secure(&self) -> bool {
        self.secure
    }

    /// Returns the SameSite policy, when set.
    pub const fn same_site(&self) -> Option<CookieSameSite> {
        self.same_site
    }

    /// Sets the cookie path.
    pub fn with_path(mut self, path: impl Into<String>) -> Self {
        self.path = Some(path.into());
        self
    }

    /// Sets the cookie domain.
    pub fn with_domain(mut self, domain: impl Into<String>) -> Self {
        self.domain = Some(domain.into());
        self
    }

    /// Sets the cookie expiration value.
    pub fn with_expires(mut self, expires: impl Into<String>) -> Self {
        self.expires = Some(expires.into());
        self
    }

    /// Sets whether the cookie should be restricted to HTTPS.
    pub const fn with_secure(mut self, secure: bool) -> Self {
        self.secure = secure;
        self
    }

    /// Sets the SameSite policy.
    pub const fn with_same_site(mut self, same_site: CookieSameSite) -> Self {
        self.same_site = Some(same_site);
        self
    }

    /// Converts this config into the JavaScript object accepted by `$cookie`.
    #[cfg(target_arch = "wasm32")]
    pub fn to_js_value(&self) -> Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue> {
        use js_sys::{Object, Reflect};
        use wasm_bindgen::JsValue;

        let options = Object::new();

        if let Some(path) = &self.path {
            Reflect::set(
                &options,
                &JsValue::from_str("path"),
                &JsValue::from_str(path),
            )?;
        }
        if let Some(domain) = &self.domain {
            Reflect::set(
                &options,
                &JsValue::from_str("domain"),
                &JsValue::from_str(domain),
            )?;
        }
        if let Some(expires) = &self.expires {
            Reflect::set(
                &options,
                &JsValue::from_str("expires"),
                &JsValue::from_str(expires),
            )?;
        }
        if self.secure {
            Reflect::set(
                &options,
                &JsValue::from_str("secure"),
                &JsValue::from_bool(true),
            )?;
        }
        if let Some(same_site) = self.same_site {
            Reflect::set(
                &options,
                &JsValue::from_str("samesite"),
                &JsValue::from_str(same_site.as_str()),
            )?;
        }

        Ok(options.into())
    }
}

/// Rust representation of options for cookie-backed persistent stores.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct CookieStoreOptions {
    cookie: Option<CookieOptions>,
}

impl CookieStoreOptions {
    /// Creates empty cookie store options.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns cookie write options, when configured.
    pub const fn cookie(&self) -> Option<&CookieOptions> {
        self.cookie.as_ref()
    }

    /// Sets cookie write options.
    pub fn with_cookie(mut self, cookie: CookieOptions) -> Self {
        self.cookie = Some(cookie);
        self
    }
}

/// HTTP verb accepted by AngularTS `$http`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HttpMethod {
    Get,
    Post,
    Put,
    Delete,
    Patch,
    Head,
    Options,
}

impl HttpMethod {
    /// Returns the uppercase method string used by AngularTS request configs.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Get => "GET",
            Self::Post => "POST",
            Self::Put => "PUT",
            Self::Delete => "DELETE",
            Self::Patch => "PATCH",
            Self::Head => "HEAD",
            Self::Options => "OPTIONS",
        }
    }
}

/// Final transport status reported by AngularTS `$http`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HttpResponseStatus {
    Complete,
    Error,
    Timeout,
    Abort,
}

impl HttpResponseStatus {
    /// Returns the lowercase status string used by AngularTS responses.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Complete => "complete",
            Self::Error => "error",
            Self::Timeout => "timeout",
            Self::Abort => "abort",
        }
    }

    /// Converts the lowercase status string used by AngularTS responses.
    pub fn from_angular(value: &str) -> Self {
        match value {
            "error" => Self::Error,
            "timeout" => Self::Timeout,
            "abort" => Self::Abort,
            _ => Self::Complete,
        }
    }
}

/// Rust representation of options accepted by AngularTS `$http` shortcut methods.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RequestShortcutConfig {
    headers: Vec<(String, String)>,
    params: Vec<(String, String)>,
    timeout: Option<u32>,
    response_type: Option<String>,
    with_credentials: Option<bool>,
}

impl RequestShortcutConfig {
    /// Creates an empty shortcut request config.
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds or replaces one request header.
    pub fn header(mut self, name: impl Into<String>, value: impl Into<String>) -> Self {
        replace_pair(&mut self.headers, name.into(), value.into());
        self
    }

    /// Adds or replaces one query parameter.
    pub fn param(mut self, name: impl Into<String>, value: impl ToString) -> Self {
        replace_pair(&mut self.params, name.into(), value.to_string());
        self
    }

    /// Sets a millisecond request timeout.
    pub fn timeout_ms(mut self, timeout: u32) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Sets the response body reader hint, such as `json` or `text`.
    pub fn response_type(mut self, response_type: impl Into<String>) -> Self {
        self.response_type = Some(response_type.into());
        self
    }

    /// Sets whether cross-site requests should include credentials.
    pub fn with_credentials(mut self, with_credentials: bool) -> Self {
        self.with_credentials = Some(with_credentials);
        self
    }

    /// Request headers.
    pub fn headers(&self) -> &[(String, String)] {
        &self.headers
    }

    /// Query parameters.
    pub fn params(&self) -> &[(String, String)] {
        &self.params
    }

    /// Optional millisecond timeout.
    pub const fn timeout(&self) -> Option<u32> {
        self.timeout
    }

    /// Optional response body reader hint.
    pub fn response_type_value(&self) -> Option<&str> {
        self.response_type.as_deref()
    }

    /// Optional credentials flag.
    pub const fn credentials(&self) -> Option<bool> {
        self.with_credentials
    }

    /// Converts this config into the JavaScript object accepted by `$http`.
    #[cfg(target_arch = "wasm32")]
    pub fn to_js_value(&self) -> Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue> {
        use js_sys::Object;

        let config = Object::new();
        self.write_to_js_object(&config)?;

        Ok(config.into())
    }

    #[cfg(target_arch = "wasm32")]
    fn write_to_js_object(&self, config: &js_sys::Object) -> Result<(), wasm_bindgen::JsValue> {
        use js_sys::{Object, Reflect};
        use wasm_bindgen::JsValue;

        if !self.headers.is_empty() {
            let headers = Object::new();
            for (name, value) in &self.headers {
                Reflect::set(
                    &headers,
                    &JsValue::from_str(name),
                    &JsValue::from_str(value),
                )?;
            }
            Reflect::set(config, &JsValue::from_str("headers"), &headers)?;
        }

        if !self.params.is_empty() {
            let params = Object::new();
            for (name, value) in &self.params {
                Reflect::set(&params, &JsValue::from_str(name), &JsValue::from_str(value))?;
            }
            Reflect::set(config, &JsValue::from_str("params"), &params)?;
        }

        if let Some(timeout) = self.timeout {
            Reflect::set(
                config,
                &JsValue::from_str("timeout"),
                &JsValue::from_f64(timeout as f64),
            )?;
        }

        if let Some(response_type) = &self.response_type {
            Reflect::set(
                config,
                &JsValue::from_str("responseType"),
                &JsValue::from_str(response_type),
            )?;
        }

        if let Some(with_credentials) = self.with_credentials {
            Reflect::set(
                config,
                &JsValue::from_str("withCredentials"),
                &JsValue::from_bool(with_credentials),
            )?;
        }

        Ok(())
    }
}

/// Minimal Rust representation of an AngularTS `$http` request config.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RequestConfig {
    method: HttpMethod,
    url: String,
    shortcut: RequestShortcutConfig,
}

impl RequestConfig {
    /// Creates a request config for the given HTTP method and URL.
    pub fn new(method: HttpMethod, url: impl Into<String>) -> Self {
        Self {
            method,
            url: url.into(),
            shortcut: RequestShortcutConfig::new(),
        }
    }

    /// Creates a `GET` request config.
    pub fn get(url: impl Into<String>) -> Self {
        Self::new(HttpMethod::Get, url)
    }

    /// Creates a `POST` request config.
    pub fn post(url: impl Into<String>) -> Self {
        Self::new(HttpMethod::Post, url)
    }

    /// Adds or replaces one request header.
    pub fn header(mut self, name: impl Into<String>, value: impl Into<String>) -> Self {
        self.shortcut = self.shortcut.header(name, value);
        self
    }

    /// Adds or replaces one query parameter.
    pub fn param(mut self, name: impl Into<String>, value: impl ToString) -> Self {
        self.shortcut = self.shortcut.param(name, value);
        self
    }

    /// Sets a millisecond request timeout.
    pub fn timeout_ms(mut self, timeout: u32) -> Self {
        self.shortcut = self.shortcut.timeout_ms(timeout);
        self
    }

    /// Sets the response body reader hint, such as `json` or `text`.
    pub fn response_type(mut self, response_type: impl Into<String>) -> Self {
        self.shortcut = self.shortcut.response_type(response_type);
        self
    }

    /// Sets whether cross-site requests should include credentials.
    pub fn with_credentials(mut self, with_credentials: bool) -> Self {
        self.shortcut = self.shortcut.with_credentials(with_credentials);
        self
    }

    /// HTTP method for this request.
    pub const fn method(&self) -> HttpMethod {
        self.method
    }

    /// Request URL.
    pub fn url(&self) -> &str {
        &self.url
    }

    /// Request headers.
    pub fn headers(&self) -> &[(String, String)] {
        self.shortcut.headers()
    }

    /// Query parameters.
    pub fn params(&self) -> &[(String, String)] {
        self.shortcut.params()
    }

    /// Optional millisecond timeout.
    pub const fn timeout(&self) -> Option<u32> {
        self.shortcut.timeout()
    }

    /// Optional response body reader hint.
    pub fn response_type_value(&self) -> Option<&str> {
        self.shortcut.response_type_value()
    }

    /// Optional credentials flag.
    pub const fn credentials(&self) -> Option<bool> {
        self.shortcut.credentials()
    }

    /// Shortcut-method options embedded in this full request config.
    pub const fn shortcut(&self) -> &RequestShortcutConfig {
        &self.shortcut
    }

    /// Converts this config into the JavaScript object accepted by `$http`.
    #[cfg(target_arch = "wasm32")]
    pub fn to_js_value(&self) -> Result<wasm_bindgen::JsValue, wasm_bindgen::JsValue> {
        use js_sys::{Object, Reflect};
        use wasm_bindgen::JsValue;

        let config = Object::new();

        Reflect::set(
            &config,
            &JsValue::from_str("method"),
            &JsValue::from_str(self.method.as_str()),
        )?;
        Reflect::set(
            &config,
            &JsValue::from_str("url"),
            &JsValue::from_str(&self.url),
        )?;

        self.shortcut.write_to_js_object(&config)?;

        Ok(config.into())
    }
}

fn replace_pair(values: &mut Vec<(String, String)>, name: String, value: String) {
    if let Some((_, existing)) = values.iter_mut().find(|(key, _)| key == &name) {
        *existing = value;
    } else {
        values.push((name, value));
    }
}

/// Minimal Rust representation of an AngularTS `$http` response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HttpResponse<T> {
    data: T,
    status: u16,
    status_text: String,
    xhr_status: HttpResponseStatus,
}

impl<T> HttpResponse<T> {
    /// Creates a response object from the core AngularTS response fields.
    pub fn new(
        data: T,
        status: u16,
        status_text: impl Into<String>,
        xhr_status: HttpResponseStatus,
    ) -> Self {
        Self {
            data,
            status,
            status_text: status_text.into(),
            xhr_status,
        }
    }

    /// Parsed response body.
    pub fn data(&self) -> &T {
        &self.data
    }

    /// Numeric HTTP status code.
    pub const fn status(&self) -> u16 {
        self.status
    }

    /// Native status text.
    pub fn status_text(&self) -> &str {
        &self.status_text
    }

    /// Transport completion status.
    pub const fn xhr_status(&self) -> HttpResponseStatus {
        self.xhr_status
    }

    /// Converts a JavaScript AngularTS `$http` response into a typed Rust response.
    #[cfg(target_arch = "wasm32")]
    pub fn from_js_value(value: wasm_bindgen::JsValue) -> Result<Self, wasm_bindgen::JsValue>
    where
        T: serde::de::DeserializeOwned,
    {
        decode_http_response(value)
    }
}

/// Listener callback shape used by the `$eventBus` facade.
pub type EventBusListener<T> = fn(T);

/// Topic-bound event bus facade created by AngularTS module topic registration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TopicService {
    topic: String,
}

impl TopicService {
    /// Creates a topic-bound event facade for the supplied topic prefix.
    pub fn new(topic: impl Into<String>) -> Self {
        Self {
            topic: topic.into(),
        }
    }

    /// Returns the topic prefix used by this facade.
    pub fn topic(&self) -> &str {
        &self.topic
    }

    /// Returns the fully qualified event bus topic for an event name.
    pub fn event_name(&self, event: &str) -> String {
        if event.is_empty() {
            self.topic.clone()
        } else {
            format!("{}:{}", self.topic, event)
        }
    }
}

#[cfg(target_arch = "wasm32")]
fn decode_http_response<T>(
    value: wasm_bindgen::JsValue,
) -> Result<HttpResponse<T>, wasm_bindgen::JsValue>
where
    T: serde::de::DeserializeOwned,
{
    use js_sys::Reflect;
    use wasm_bindgen::JsValue;

    let data = Reflect::get(&value, &JsValue::from_str("data")).and_then(|data| {
        serde_wasm_bindgen::from_value(data).map_err(|error| JsValue::from_str(&error.to_string()))
    })?;
    let status = Reflect::get(&value, &JsValue::from_str("status"))?
        .as_f64()
        .unwrap_or_default() as u16;
    let status_text = Reflect::get(&value, &JsValue::from_str("statusText"))?
        .as_string()
        .unwrap_or_default();
    let xhr_status = Reflect::get(&value, &JsValue::from_str("xhrStatus"))?
        .as_string()
        .as_deref()
        .map(HttpResponseStatus::from_angular)
        .unwrap_or(HttpResponseStatus::Complete);

    Ok(HttpResponse::new(data, status, status_text, xhr_status))
}

#[cfg(not(target_arch = "wasm32"))]
mod host {
    use super::{CookieOptions, Service};
    use std::collections::HashMap;

    #[derive(Debug, Clone, Copy)]
    pub struct HttpService;

    #[derive(Debug, Clone, Copy)]
    pub struct LogService;

    #[derive(Debug, Clone, Copy)]
    pub struct ExceptionHandlerService;

    #[derive(Debug, Clone, Copy)]
    pub struct RootScopeService;

    #[derive(Debug, Clone, Copy)]
    pub struct EventBusService;

    #[derive(Debug, Clone, Default)]
    pub struct CookieService {
        values: HashMap<String, String>,
        defaults: CookieOptions,
    }

    #[derive(Debug, Clone, Default)]
    pub struct TemplateCacheService {
        templates: HashMap<String, String>,
    }

    #[derive(Debug, Clone, Copy)]
    pub struct TemplateRequestService;

    impl CookieService {
        /// Creates an empty cookie service using default write options.
        pub fn new(defaults: CookieOptions) -> Self {
            Self {
                values: HashMap::new(),
                defaults,
            }
        }

        /// Returns the default cookie options.
        pub const fn defaults(&self) -> &CookieOptions {
            &self.defaults
        }

        /// Retrieves a raw cookie value.
        pub fn get(&self, key: &str) -> Option<&str> {
            self.values.get(key).map(String::as_str)
        }

        /// Returns all raw cookies.
        pub fn get_all(&self) -> &HashMap<String, String> {
            &self.values
        }

        /// Sets a raw cookie value.
        pub fn put(&mut self, key: impl Into<String>, value: impl Into<String>) {
            self.values.insert(key.into(), value.into());
        }

        /// Removes a cookie value.
        pub fn remove(&mut self, key: &str) {
            self.values.remove(key);
        }
    }

    impl TemplateCacheService {
        /// Creates an empty template cache.
        pub fn new() -> Self {
            Self::default()
        }

        /// Returns a cached template by URL.
        pub fn get(&self, url: &str) -> Option<&str> {
            self.templates.get(url).map(String::as_str)
        }

        /// Stores a template by URL.
        pub fn set(&mut self, url: impl Into<String>, template: impl Into<String>) {
            self.templates.insert(url.into(), template.into());
        }

        /// Returns whether a template URL is cached.
        pub fn contains(&self, url: &str) -> bool {
            self.templates.contains_key(url)
        }

        /// Removes a cached template by URL.
        pub fn remove(&mut self, url: &str) -> Option<String> {
            self.templates.remove(url)
        }

        /// Returns cached template count.
        pub fn len(&self) -> usize {
            self.templates.len()
        }

        /// Returns whether the cache is empty.
        pub fn is_empty(&self) -> bool {
            self.templates.is_empty()
        }
    }

    impl Service for HttpService {
        const TOKEN_NAME: &'static str = "$http";
        const EXPORT_NAME: &'static str = "__ng_service_HttpService";
    }

    impl Service for LogService {
        const TOKEN_NAME: &'static str = "$log";
        const EXPORT_NAME: &'static str = "__ng_service_LogService";
    }

    impl Service for ExceptionHandlerService {
        const TOKEN_NAME: &'static str = "$exceptionHandler";
        const EXPORT_NAME: &'static str = "__ng_service_ExceptionHandlerService";
    }

    impl Service for RootScopeService {
        const TOKEN_NAME: &'static str = "$rootScope";
        const EXPORT_NAME: &'static str = "__ng_service_RootScopeService";
    }

    impl Service for EventBusService {
        const TOKEN_NAME: &'static str = "$eventBus";
        const EXPORT_NAME: &'static str = "__ng_service_EventBusService";
    }

    impl Service for CookieService {
        const TOKEN_NAME: &'static str = "$cookie";
        const EXPORT_NAME: &'static str = "__ng_service_CookieService";
    }

    impl Service for TemplateCacheService {
        const TOKEN_NAME: &'static str = "$templateCache";
        const EXPORT_NAME: &'static str = "__ng_service_TemplateCacheService";
    }

    impl Service for TemplateRequestService {
        const TOKEN_NAME: &'static str = "$templateRequest";
        const EXPORT_NAME: &'static str = "__ng_service_TemplateRequestService";
    }
}

#[cfg(target_arch = "wasm32")]
mod browser {
    use super::{
        decode_http_response, HttpResponse, RequestConfig, RequestShortcutConfig, Service,
    };
    use js_sys::{Array, Function, Promise, Reflect};
    use serde::{de::DeserializeOwned, Serialize};
    use std::{future::Future, pin::Pin};
    use wasm_bindgen::prelude::*;
    use wasm_bindgen::JsCast;
    use wasm_bindgen_futures::JsFuture;

    #[wasm_bindgen]
    extern "C" {
        /// Browser `$http` service facade.
        #[wasm_bindgen(typescript_type = "ng.HttpService")]
        pub type HttpService;

        #[wasm_bindgen(method, js_name = get)]
        pub fn get(this: &HttpService, url: &str) -> Promise;

        #[wasm_bindgen(method, js_name = get)]
        pub fn get_with_config(this: &HttpService, url: &str, config: &JsValue) -> Promise;

        #[wasm_bindgen(method, js_name = delete)]
        pub fn delete(this: &HttpService, url: &str) -> Promise;

        #[wasm_bindgen(method, js_name = delete)]
        pub fn delete_with_config(this: &HttpService, url: &str, config: &JsValue) -> Promise;

        #[wasm_bindgen(method, js_name = head)]
        pub fn head(this: &HttpService, url: &str) -> Promise;

        #[wasm_bindgen(method, js_name = head)]
        pub fn head_with_config(this: &HttpService, url: &str, config: &JsValue) -> Promise;

        #[wasm_bindgen(method, js_name = post)]
        pub fn post(this: &HttpService, url: &str, data: &JsValue) -> Promise;

        #[wasm_bindgen(method, js_name = post)]
        pub fn post_with_config(
            this: &HttpService,
            url: &str,
            data: &JsValue,
            config: &JsValue,
        ) -> Promise;

        #[wasm_bindgen(method, js_name = put)]
        pub fn put(this: &HttpService, url: &str, data: &JsValue) -> Promise;

        #[wasm_bindgen(method, js_name = put)]
        pub fn put_with_config(
            this: &HttpService,
            url: &str,
            data: &JsValue,
            config: &JsValue,
        ) -> Promise;

        #[wasm_bindgen(method, js_name = patch)]
        pub fn patch(this: &HttpService, url: &str, data: &JsValue) -> Promise;

        #[wasm_bindgen(method, js_name = patch)]
        pub fn patch_with_config(
            this: &HttpService,
            url: &str,
            data: &JsValue,
            config: &JsValue,
        ) -> Promise;

        /// Browser `$log` service facade.
        #[wasm_bindgen(typescript_type = "ng.LogService")]
        pub type LogService;

        #[wasm_bindgen(method, js_name = log)]
        pub fn log(this: &LogService, value: &JsValue);

        #[wasm_bindgen(method, js_name = info)]
        pub fn info(this: &LogService, value: &JsValue);

        #[wasm_bindgen(method, js_name = warn)]
        pub fn warn(this: &LogService, value: &JsValue);

        #[wasm_bindgen(method, js_name = error)]
        pub fn error(this: &LogService, value: &JsValue);

        #[wasm_bindgen(method, js_name = debug)]
        pub fn debug(this: &LogService, value: &JsValue);

        /// Browser `$rootScope` service facade.
        #[wasm_bindgen(typescript_type = "ng.RootScopeService")]
        pub type RootScopeService;

        #[wasm_bindgen(method, js_name = "$new")]
        pub fn new_child(this: &RootScopeService) -> JsValue;

        #[wasm_bindgen(method, js_name = "$flushQueue")]
        pub fn flush_queue(this: &RootScopeService);

        /// Browser `$eventBus` service facade.
        #[wasm_bindgen(typescript_type = "ng.PubSubService")]
        pub type EventBusService;

        #[wasm_bindgen(method, js_name = publish)]
        pub fn publish(this: &EventBusService, topic: &str, value: &JsValue) -> bool;

        #[wasm_bindgen(method, js_name = subscribe)]
        pub fn subscribe(this: &EventBusService, topic: &str, listener: &Function) -> Function;

        #[wasm_bindgen(method, js_name = subscribeOnce)]
        pub fn subscribe_once(this: &EventBusService, topic: &str, listener: &Function)
            -> Function;

        #[wasm_bindgen(method, js_name = getCount)]
        pub fn get_count(this: &EventBusService, topic: &str) -> u32;

        #[wasm_bindgen(method, js_name = reset)]
        pub fn reset(this: &EventBusService);

        #[wasm_bindgen(method, js_name = dispose)]
        pub fn dispose(this: &EventBusService);

        /// Browser `$templateCache` service facade.
        #[wasm_bindgen(typescript_type = "ng.TemplateCacheService")]
        pub type TemplateCacheService;

        #[wasm_bindgen(method, js_name = get)]
        pub fn template_get(this: &TemplateCacheService, url: &str) -> JsValue;

        #[wasm_bindgen(method, js_name = set)]
        pub fn template_set(this: &TemplateCacheService, url: &str, template: &str);

        #[wasm_bindgen(method, js_name = has)]
        pub fn template_has(this: &TemplateCacheService, url: &str) -> bool;

        #[wasm_bindgen(method, js_name = delete)]
        pub fn template_delete(this: &TemplateCacheService, url: &str) -> bool;

        /// Browser `$templateRequest` service facade.
        #[wasm_bindgen(typescript_type = "ng.TemplateRequestService")]
        pub type TemplateRequestService;

        /// Browser `$cookie` service facade.
        #[wasm_bindgen(typescript_type = "ng.CookieService")]
        pub type CookieService;

        #[wasm_bindgen(method, js_name = get)]
        pub fn cookie_get(this: &CookieService, key: &str) -> JsValue;

        #[wasm_bindgen(method, js_name = getAll)]
        pub fn cookie_get_all(this: &CookieService) -> JsValue;

        #[wasm_bindgen(method, js_name = put)]
        pub fn cookie_put(this: &CookieService, key: &str, value: &str, options: &JsValue);

        #[wasm_bindgen(method, js_name = putObject)]
        pub fn cookie_put_object(
            this: &CookieService,
            key: &str,
            value: &JsValue,
            options: &JsValue,
        );

        #[wasm_bindgen(method, js_name = remove)]
        pub fn cookie_remove(this: &CookieService, key: &str, options: &JsValue);
    }

    /// Browser `$exceptionHandler` service facade.
    pub type ExceptionHandlerService = Function;

    /// Ergonomic async helpers for injected AngularTS `$templateRequest` values.
    pub trait TemplateRequestServiceExt {
        /// Fetches a template URL and resolves with template text.
        fn request_template(
            &self,
            url: &str,
        ) -> Pin<Box<dyn Future<Output = Result<String, JsValue>> + '_>>;
    }

    /// Ergonomic async helpers for injected AngularTS `$http` service values.
    pub trait HttpServiceExt {
        /// Sends a full `$http` request config and decodes the response body.
        fn request_json<T>(
            &self,
            config: &RequestConfig,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static;

        /// Sends a `GET` request and decodes the response body.
        fn get_json<T>(
            &self,
            url: &str,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static;

        /// Sends a `GET` request with shortcut options and decodes the response body.
        fn get_json_with<T>(
            &self,
            url: &str,
            config: &RequestShortcutConfig,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static;

        /// Sends a `POST` request with a serializable body and decodes the response body.
        fn post_json<T, B>(
            &self,
            url: &str,
            body: &B,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
            B: Serialize;

        /// Sends a `POST` request with shortcut options and decodes the response body.
        fn post_json_with<T, B>(
            &self,
            url: &str,
            body: &B,
            config: &RequestShortcutConfig,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
            B: Serialize;
    }

    impl HttpServiceExt for JsValue {
        fn request_json<T>(
            &self,
            config: &RequestConfig,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
        {
            let service = self.clone();
            let config = config.clone();

            Box::pin(async move {
                let request = service.unchecked_into::<Function>();
                let value = Reflect::apply(
                    &request,
                    &JsValue::UNDEFINED,
                    &Array::of1(&config.to_js_value()?),
                )?;
                let promise = value.dyn_into::<Promise>()?;

                decode_http_response(JsFuture::from(promise).await?)
            })
        }

        fn get_json<T>(
            &self,
            url: &str,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
        {
            let service = self.clone();
            let url = url.to_string();

            Box::pin(async move {
                let service = service.unchecked_ref::<HttpService>();

                decode_http_response(JsFuture::from(service.get(&url)).await?)
            })
        }

        fn get_json_with<T>(
            &self,
            url: &str,
            config: &RequestShortcutConfig,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
        {
            let service = self.clone();
            let url = url.to_string();
            let config = config.to_js_value();

            Box::pin(async move {
                let config = config?;
                let service = service.unchecked_ref::<HttpService>();

                decode_http_response(JsFuture::from(service.get_with_config(&url, &config)).await?)
            })
        }

        fn post_json<T, B>(
            &self,
            url: &str,
            body: &B,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
            B: Serialize,
        {
            let service = self.clone();
            let url = url.to_string();
            let body = serde_wasm_bindgen::to_value(body)
                .map_err(|error| JsValue::from_str(&error.to_string()));

            Box::pin(async move {
                let body = body?;
                let service = service.unchecked_ref::<HttpService>();

                decode_http_response(JsFuture::from(service.post(&url, &body)).await?)
            })
        }

        fn post_json_with<T, B>(
            &self,
            url: &str,
            body: &B,
            config: &RequestShortcutConfig,
        ) -> Pin<Box<dyn Future<Output = Result<HttpResponse<T>, JsValue>> + '_>>
        where
            T: DeserializeOwned + 'static,
            B: Serialize,
        {
            let service = self.clone();
            let url = url.to_string();
            let body = serde_wasm_bindgen::to_value(body)
                .map_err(|error| JsValue::from_str(&error.to_string()));
            let config = config.to_js_value();

            Box::pin(async move {
                let body = body?;
                let config = config?;
                let service = service.unchecked_ref::<HttpService>();

                decode_http_response(
                    JsFuture::from(service.post_with_config(&url, &body, &config)).await?,
                )
            })
        }
    }

    impl TemplateRequestServiceExt for JsValue {
        fn request_template(
            &self,
            url: &str,
        ) -> Pin<Box<dyn Future<Output = Result<String, JsValue>> + '_>> {
            let service = self.clone();
            let url = url.to_string();

            Box::pin(async move {
                let request = service.unchecked_into::<Function>();
                let value = Reflect::apply(
                    &request,
                    &JsValue::UNDEFINED,
                    &Array::of1(&JsValue::from_str(&url)),
                )?;
                let promise = value.dyn_into::<Promise>()?;

                Ok(JsFuture::from(promise)
                    .await?
                    .as_string()
                    .unwrap_or_default())
            })
        }
    }

    impl TemplateRequestService {
        /// Fetches a template URL and resolves with template text.
        pub async fn request_template(&self, url: &str) -> Result<String, JsValue> {
            let request: &Function = self.unchecked_ref();
            let value = Reflect::apply(
                request,
                &JsValue::UNDEFINED,
                &Array::of1(&JsValue::from_str(url)),
            )?;
            let promise = value.dyn_into::<Promise>()?;

            Ok(JsFuture::from(promise)
                .await?
                .as_string()
                .unwrap_or_default())
        }
    }

    impl HttpService {
        /// Sends a full `$http` request config and decodes the response body.
        pub async fn request_json<T>(
            &self,
            config: &RequestConfig,
        ) -> Result<HttpResponse<T>, JsValue>
        where
            T: DeserializeOwned,
        {
            let service: &JsValue = self.as_ref();
            let request = service.clone().unchecked_into::<Function>();
            let value = Reflect::apply(
                &request,
                &JsValue::UNDEFINED,
                &Array::of1(&config.to_js_value()?),
            )?;
            let promise = value.dyn_into::<Promise>()?;
            decode_http_response(JsFuture::from(promise).await?)
        }

        /// Sends a `GET` request and decodes the response body.
        pub async fn get_json<T>(&self, url: &str) -> Result<HttpResponse<T>, JsValue>
        where
            T: DeserializeOwned,
        {
            decode_http_response(JsFuture::from(self.get(url)).await?)
        }

        /// Sends a `GET` request with shortcut options and decodes the response body.
        pub async fn get_json_with<T>(
            &self,
            url: &str,
            config: &RequestShortcutConfig,
        ) -> Result<HttpResponse<T>, JsValue>
        where
            T: DeserializeOwned,
        {
            decode_http_response(
                JsFuture::from(self.get_with_config(url, &config.to_js_value()?)).await?,
            )
        }

        /// Sends a `POST` request with a serializable body and decodes the response body.
        pub async fn post_json<T, B>(&self, url: &str, body: &B) -> Result<HttpResponse<T>, JsValue>
        where
            T: DeserializeOwned,
            B: Serialize,
        {
            let body = serde_wasm_bindgen::to_value(body)
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            decode_http_response(JsFuture::from(self.post(url, &body)).await?)
        }

        /// Sends a `POST` request with shortcut options and decodes the response body.
        pub async fn post_json_with<T, B>(
            &self,
            url: &str,
            body: &B,
            config: &RequestShortcutConfig,
        ) -> Result<HttpResponse<T>, JsValue>
        where
            T: DeserializeOwned,
            B: Serialize,
        {
            let body = serde_wasm_bindgen::to_value(body)
                .map_err(|error| JsValue::from_str(&error.to_string()))?;
            decode_http_response(
                JsFuture::from(self.post_with_config(url, &body, &config.to_js_value()?)).await?,
            )
        }
    }

    impl super::TopicService {
        /// Publishes one value under this topic facade.
        pub fn publish(&self, event_bus: &EventBusService, event: &str, value: &JsValue) -> bool {
            event_bus.publish(&self.event_name(event), value)
        }

        /// Subscribes to one event under this topic facade.
        pub fn subscribe(
            &self,
            event_bus: &EventBusService,
            event: &str,
            listener: &Function,
        ) -> Function {
            event_bus.subscribe(&self.event_name(event), listener)
        }

        /// Subscribes once to one event under this topic facade.
        pub fn subscribe_once(
            &self,
            event_bus: &EventBusService,
            event: &str,
            listener: &Function,
        ) -> Function {
            event_bus.subscribe_once(&self.event_name(event), listener)
        }

        /// Returns subscriber count for one event under this topic facade.
        pub fn get_count(&self, event_bus: &EventBusService, event: &str) -> u32 {
            event_bus.get_count(&self.event_name(event))
        }
    }

    impl Service for HttpService {
        const TOKEN_NAME: &'static str = "$http";
        const EXPORT_NAME: &'static str = "__ng_service_HttpService";
    }

    impl Service for LogService {
        const TOKEN_NAME: &'static str = "$log";
        const EXPORT_NAME: &'static str = "__ng_service_LogService";
    }

    impl Service for ExceptionHandlerService {
        const TOKEN_NAME: &'static str = "$exceptionHandler";
        const EXPORT_NAME: &'static str = "__ng_service_ExceptionHandlerService";
    }

    impl Service for RootScopeService {
        const TOKEN_NAME: &'static str = "$rootScope";
        const EXPORT_NAME: &'static str = "__ng_service_RootScopeService";
    }

    impl Service for EventBusService {
        const TOKEN_NAME: &'static str = "$eventBus";
        const EXPORT_NAME: &'static str = "__ng_service_EventBusService";
    }

    impl Service for CookieService {
        const TOKEN_NAME: &'static str = "$cookie";
        const EXPORT_NAME: &'static str = "__ng_service_CookieService";
    }

    impl Service for TemplateCacheService {
        const TOKEN_NAME: &'static str = "$templateCache";
        const EXPORT_NAME: &'static str = "__ng_service_TemplateCacheService";
    }

    impl Service for TemplateRequestService {
        const TOKEN_NAME: &'static str = "$templateRequest";
        const EXPORT_NAME: &'static str = "__ng_service_TemplateRequestService";
    }
}

#[cfg(target_arch = "wasm32")]
pub use browser::{
    CookieService, EventBusService, ExceptionHandlerService, HttpService, HttpServiceExt,
    LogService, RootScopeService, TemplateCacheService, TemplateRequestService,
    TemplateRequestServiceExt,
};
#[cfg(not(target_arch = "wasm32"))]
pub use host::{
    CookieService, EventBusService, ExceptionHandlerService, HttpService, LogService,
    RootScopeService, TemplateCacheService, TemplateRequestService,
};

/// Public `ng.PubSubService` facade. `$eventBus` uses this runtime shape.
pub type PubSubService = EventBusService;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mvp_services_use_published_injection_tokens() {
        assert_eq!(HttpService::TOKEN_NAME, "$http");
        assert_eq!(LogService::TOKEN_NAME, "$log");
        assert_eq!(ExceptionHandlerService::TOKEN_NAME, "$exceptionHandler");
        assert_eq!(RootScopeService::TOKEN_NAME, "$rootScope");
        assert_eq!(EventBusService::TOKEN_NAME, "$eventBus");
        assert_eq!(CookieService::TOKEN_NAME, "$cookie");
        assert_eq!(TemplateCacheService::TOKEN_NAME, "$templateCache");
        assert_eq!(TemplateRequestService::TOKEN_NAME, "$templateRequest");
    }

    #[test]
    fn http_request_config_preserves_method_and_url() {
        let get = RequestConfig::get("/api/todos")
            .header("Accept", "application/json")
            .param("owner", "Rust")
            .timeout_ms(1500)
            .response_type("json")
            .with_credentials(true);
        let post = RequestConfig::post("/api/todos");

        assert_eq!(get.method(), HttpMethod::Get);
        assert_eq!(get.method().as_str(), "GET");
        assert_eq!(get.url(), "/api/todos");
        assert_eq!(
            get.headers(),
            &[("Accept".to_string(), "application/json".to_string())]
        );
        assert_eq!(get.params(), &[("owner".to_string(), "Rust".to_string())]);
        assert_eq!(get.timeout(), Some(1500));
        assert_eq!(get.response_type_value(), Some("json"));
        assert_eq!(get.credentials(), Some(true));
        assert_eq!(post.method(), HttpMethod::Post);
        assert_eq!(post.method().as_str(), "POST");
    }

    #[test]
    fn http_shortcut_config_preserves_options() {
        let config = RequestShortcutConfig::new()
            .header("Accept", "application/json")
            .header("Accept", "text/plain")
            .param("owner", "Rust")
            .timeout_ms(250)
            .response_type("text")
            .with_credentials(false);

        assert_eq!(
            config.headers(),
            &[("Accept".to_string(), "text/plain".to_string())]
        );
        assert_eq!(
            config.params(),
            &[("owner".to_string(), "Rust".to_string())]
        );
        assert_eq!(config.timeout(), Some(250));
        assert_eq!(config.response_type_value(), Some("text"));
        assert_eq!(config.credentials(), Some(false));
    }

    #[test]
    fn http_response_exposes_core_fields() {
        let response = HttpResponse::new("ok", 200, "OK", HttpResponseStatus::Complete);

        assert_eq!(response.data(), &"ok");
        assert_eq!(response.status(), 200);
        assert_eq!(response.status_text(), "OK");
        assert_eq!(response.xhr_status().as_str(), "complete");
        assert_eq!(
            HttpResponseStatus::from_angular("timeout"),
            HttpResponseStatus::Timeout
        );
    }

    #[test]
    fn topic_service_qualifies_event_names() {
        let service = TopicService::new("tasks");

        assert_eq!(service.topic(), "tasks");
        assert_eq!(service.event_name("saved"), "tasks:saved");
        assert_eq!(service.event_name(""), "tasks");
    }

    #[test]
    fn template_cache_service_stores_templates_by_url() {
        let mut cache = TemplateCacheService::new();

        assert!(cache.is_empty());
        cache.set("/templates/todo.html", "<todo-list></todo-list>");

        assert!(cache.contains("/templates/todo.html"));
        assert_eq!(
            cache.get("/templates/todo.html"),
            Some("<todo-list></todo-list>")
        );
        assert_eq!(cache.len(), 1);
        assert_eq!(
            cache.remove("/templates/todo.html"),
            Some("<todo-list></todo-list>".to_string())
        );
        assert!(!cache.contains("/templates/todo.html"));
    }

    #[test]
    fn storage_backend_trait_supports_memory_backend() {
        let mut storage = MemoryStorageBackend::new();

        assert!(storage.is_empty());
        storage.set("prefs", r#"{"theme":"dark"}"#);

        assert_eq!(StorageType::Local.as_str(), "local");
        assert_eq!(StorageType::Session.as_str(), "session");
        assert_eq!(StorageType::Cookie.as_str(), "cookie");
        assert_eq!(StorageType::Custom.as_str(), "custom");
        assert_eq!(
            storage.get("prefs"),
            Some(r#"{"theme":"dark"}"#.to_string())
        );
        assert_eq!(storage.len(), 1);

        storage.remove("prefs");

        assert_eq!(storage.get("prefs"), None);
    }

    #[test]
    fn cookie_options_and_service_preserve_values() {
        let options = CookieOptions::new()
            .with_path("/")
            .with_domain("example.test")
            .with_expires("2030-01-01T00:00:00Z")
            .with_secure(true)
            .with_same_site(CookieSameSite::Strict);
        let store_options = CookieStoreOptions::new().with_cookie(options.clone());
        let mut cookies = CookieService::new(options.clone());

        assert_eq!(options.path(), Some("/"));
        assert_eq!(options.domain(), Some("example.test"));
        assert_eq!(options.expires(), Some("2030-01-01T00:00:00Z"));
        assert!(options.secure());
        assert_eq!(options.same_site(), Some(CookieSameSite::Strict));
        assert_eq!(
            store_options.cookie().and_then(CookieOptions::same_site),
            Some(CookieSameSite::Strict)
        );
        assert_eq!(cookies.defaults().path(), Some("/"));

        cookies.put("session", "abc");

        assert_eq!(cookies.get("session"), Some("abc"));
        assert_eq!(cookies.get_all().len(), 1);

        cookies.remove("session");

        assert_eq!(cookies.get("session"), None);
    }
}
