// Generated by utils/generate-programmatic-view-tags.mjs. Do not edit.
use wasm_bindgen::JsValue;

use crate::view::{ProgrammaticViewChild, ProgrammaticViewProperties, ProgrammaticViewTags};

impl ProgrammaticViewTags {
    /// Creates a `a` element.
    pub fn a(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("a", properties, children)
    }

    /// Creates a `abbr` element.
    pub fn abbr(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("abbr", properties, children)
    }

    /// Creates a `address` element.
    pub fn address(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("address", properties, children)
    }

    /// Creates a `area` element.
    pub fn area(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("area", properties, children)
    }

    /// Creates a `article` element.
    pub fn article(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("article", properties, children)
    }

    /// Creates a `aside` element.
    pub fn aside(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("aside", properties, children)
    }

    /// Creates a `audio` element.
    pub fn audio(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("audio", properties, children)
    }

    /// Creates a `b` element.
    pub fn b(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("b", properties, children)
    }

    /// Creates a `base` element.
    pub fn base(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("base", properties, children)
    }

    /// Creates a `bdi` element.
    pub fn bdi(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("bdi", properties, children)
    }

    /// Creates a `bdo` element.
    pub fn bdo(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("bdo", properties, children)
    }

    /// Creates a `blockquote` element.
    pub fn blockquote(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("blockquote", properties, children)
    }

    /// Creates a `body` element.
    pub fn body(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("body", properties, children)
    }

    /// Creates a `br` element.
    pub fn br(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("br", properties, children)
    }

    /// Creates a `button` element.
    pub fn button(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("button", properties, children)
    }

    /// Creates a `canvas` element.
    pub fn canvas(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("canvas", properties, children)
    }

    /// Creates a `caption` element.
    pub fn caption(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("caption", properties, children)
    }

    /// Creates a `cite` element.
    pub fn cite(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("cite", properties, children)
    }

    /// Creates a `code` element.
    pub fn code(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("code", properties, children)
    }

    /// Creates a `col` element.
    pub fn col(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("col", properties, children)
    }

    /// Creates a `colgroup` element.
    pub fn colgroup(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("colgroup", properties, children)
    }

    /// Creates a `data` element.
    pub fn data(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("data", properties, children)
    }

    /// Creates a `datalist` element.
    pub fn datalist(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("datalist", properties, children)
    }

    /// Creates a `dd` element.
    pub fn dd(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("dd", properties, children)
    }

    /// Creates a `del` element.
    pub fn del(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("del", properties, children)
    }

    /// Creates a `details` element.
    pub fn details(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("details", properties, children)
    }

    /// Creates a `dfn` element.
    pub fn dfn(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("dfn", properties, children)
    }

    /// Creates a `dialog` element.
    pub fn dialog(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("dialog", properties, children)
    }

    /// Creates a `div` element.
    pub fn div(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("div", properties, children)
    }

    /// Creates a `dl` element.
    pub fn dl(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("dl", properties, children)
    }

    /// Creates a `dt` element.
    pub fn dt(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("dt", properties, children)
    }

    /// Creates a `em` element.
    pub fn em(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("em", properties, children)
    }

    /// Creates a `embed` element.
    pub fn embed(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("embed", properties, children)
    }

    /// Creates a `fieldset` element.
    pub fn fieldset(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("fieldset", properties, children)
    }

    /// Creates a `figcaption` element.
    pub fn figcaption(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("figcaption", properties, children)
    }

    /// Creates a `figure` element.
    pub fn figure(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("figure", properties, children)
    }

    /// Creates a `footer` element.
    pub fn footer(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("footer", properties, children)
    }

    /// Creates a `form` element.
    pub fn form(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("form", properties, children)
    }

    /// Creates a `h1` element.
    pub fn h1(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("h1", properties, children)
    }

    /// Creates a `h2` element.
    pub fn h2(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("h2", properties, children)
    }

    /// Creates a `h3` element.
    pub fn h3(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("h3", properties, children)
    }

    /// Creates a `h4` element.
    pub fn h4(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("h4", properties, children)
    }

    /// Creates a `h5` element.
    pub fn h5(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("h5", properties, children)
    }

    /// Creates a `h6` element.
    pub fn h6(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("h6", properties, children)
    }

    /// Creates a `head` element.
    pub fn head(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("head", properties, children)
    }

    /// Creates a `header` element.
    pub fn header(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("header", properties, children)
    }

    /// Creates a `hgroup` element.
    pub fn hgroup(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("hgroup", properties, children)
    }

    /// Creates a `hr` element.
    pub fn hr(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("hr", properties, children)
    }

    /// Creates a `html` element.
    pub fn html(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("html", properties, children)
    }

    /// Creates a `i` element.
    pub fn i(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("i", properties, children)
    }

    /// Creates a `iframe` element.
    pub fn iframe(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("iframe", properties, children)
    }

    /// Creates a `img` element.
    pub fn img(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("img", properties, children)
    }

    /// Creates a `input` element.
    pub fn input(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("input", properties, children)
    }

    /// Creates a `ins` element.
    pub fn ins(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("ins", properties, children)
    }

    /// Creates a `kbd` element.
    pub fn kbd(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("kbd", properties, children)
    }

    /// Creates a `label` element.
    pub fn label(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("label", properties, children)
    }

    /// Creates a `legend` element.
    pub fn legend(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("legend", properties, children)
    }

    /// Creates a `li` element.
    pub fn li(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("li", properties, children)
    }

    /// Creates a `link` element.
    pub fn link(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("link", properties, children)
    }

    /// Creates a `main` element.
    pub fn main(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("main", properties, children)
    }

    /// Creates a `map` element.
    pub fn map(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("map", properties, children)
    }

    /// Creates a `mark` element.
    pub fn mark(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("mark", properties, children)
    }

    /// Creates a `menu` element.
    pub fn menu(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("menu", properties, children)
    }

    /// Creates a `meta` element.
    pub fn meta(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("meta", properties, children)
    }

    /// Creates a `meter` element.
    pub fn meter(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("meter", properties, children)
    }

    /// Creates a `nav` element.
    pub fn nav(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("nav", properties, children)
    }

    /// Creates a `noscript` element.
    pub fn noscript(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("noscript", properties, children)
    }

    /// Creates a `object` element.
    pub fn object(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("object", properties, children)
    }

    /// Creates a `ol` element.
    pub fn ol(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("ol", properties, children)
    }

    /// Creates a `optgroup` element.
    pub fn optgroup(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("optgroup", properties, children)
    }

    /// Creates a `option` element.
    pub fn option(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("option", properties, children)
    }

    /// Creates a `output` element.
    pub fn output(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("output", properties, children)
    }

    /// Creates a `p` element.
    pub fn p(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("p", properties, children)
    }

    /// Creates a `picture` element.
    pub fn picture(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("picture", properties, children)
    }

    /// Creates a `pre` element.
    pub fn pre(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("pre", properties, children)
    }

    /// Creates a `progress` element.
    pub fn progress(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("progress", properties, children)
    }

    /// Creates a `q` element.
    pub fn q(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("q", properties, children)
    }

    /// Creates a `rp` element.
    pub fn rp(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("rp", properties, children)
    }

    /// Creates a `rt` element.
    pub fn rt(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("rt", properties, children)
    }

    /// Creates a `ruby` element.
    pub fn ruby(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("ruby", properties, children)
    }

    /// Creates a `s` element.
    pub fn s(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("s", properties, children)
    }

    /// Creates a `samp` element.
    pub fn samp(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("samp", properties, children)
    }

    /// Creates a `script` element.
    pub fn script(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("script", properties, children)
    }

    /// Creates a `search` element.
    pub fn search(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("search", properties, children)
    }

    /// Creates a `section` element.
    pub fn section(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("section", properties, children)
    }

    /// Creates a `select` element.
    pub fn select(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("select", properties, children)
    }

    /// Creates a `slot` element.
    pub fn slot(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("slot", properties, children)
    }

    /// Creates a `small` element.
    pub fn small(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("small", properties, children)
    }

    /// Creates a `source` element.
    pub fn source(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("source", properties, children)
    }

    /// Creates a `span` element.
    pub fn span(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("span", properties, children)
    }

    /// Creates a `strong` element.
    pub fn strong(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("strong", properties, children)
    }

    /// Creates a `style` element.
    pub fn style(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("style", properties, children)
    }

    /// Creates a `sub` element.
    pub fn sub(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("sub", properties, children)
    }

    /// Creates a `summary` element.
    pub fn summary(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("summary", properties, children)
    }

    /// Creates a `sup` element.
    pub fn sup(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("sup", properties, children)
    }

    /// Creates a `table` element.
    pub fn table(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("table", properties, children)
    }

    /// Creates a `tbody` element.
    pub fn tbody(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("tbody", properties, children)
    }

    /// Creates a `td` element.
    pub fn td(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("td", properties, children)
    }

    /// Creates a `template` element.
    pub fn template(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("template", properties, children)
    }

    /// Creates a `textarea` element.
    pub fn textarea(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("textarea", properties, children)
    }

    /// Creates a `tfoot` element.
    pub fn tfoot(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("tfoot", properties, children)
    }

    /// Creates a `th` element.
    pub fn th(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("th", properties, children)
    }

    /// Creates a `thead` element.
    pub fn thead(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("thead", properties, children)
    }

    /// Creates a `time` element.
    pub fn time(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("time", properties, children)
    }

    /// Creates a `title` element.
    pub fn title(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("title", properties, children)
    }

    /// Creates a `tr` element.
    pub fn tr(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("tr", properties, children)
    }

    /// Creates a `track` element.
    pub fn track(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("track", properties, children)
    }

    /// Creates a `u` element.
    pub fn u(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("u", properties, children)
    }

    /// Creates a `ul` element.
    pub fn ul(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("ul", properties, children)
    }

    /// Creates a `var` element.
    pub fn var(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("var", properties, children)
    }

    /// Creates a `video` element.
    pub fn video(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("video", properties, children)
    }

    /// Creates a `wbr` element.
    pub fn wbr(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("wbr", properties, children)
    }

    /// Creates a `acronym` element.
    pub fn acronym(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("acronym", properties, children)
    }

    /// Creates a `applet` element.
    pub fn applet(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("applet", properties, children)
    }

    /// Creates a `basefont` element.
    pub fn basefont(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("basefont", properties, children)
    }

    /// Creates a `bgsound` element.
    pub fn bgsound(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("bgsound", properties, children)
    }

    /// Creates a `big` element.
    pub fn big(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("big", properties, children)
    }

    /// Creates a `blink` element.
    pub fn blink(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("blink", properties, children)
    }

    /// Creates a `center` element.
    pub fn center(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("center", properties, children)
    }

    /// Creates a `dir` element.
    pub fn dir(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("dir", properties, children)
    }

    /// Creates a `font` element.
    pub fn font(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("font", properties, children)
    }

    /// Creates a `frame` element.
    pub fn frame(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("frame", properties, children)
    }

    /// Creates a `frameset` element.
    pub fn frameset(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("frameset", properties, children)
    }

    /// Creates a `isindex` element.
    pub fn isindex(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("isindex", properties, children)
    }

    /// Creates a `keygen` element.
    pub fn keygen(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("keygen", properties, children)
    }

    /// Creates a `listing` element.
    pub fn listing(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("listing", properties, children)
    }

    /// Creates a `marquee` element.
    pub fn marquee(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("marquee", properties, children)
    }

    /// Creates a `menuitem` element.
    pub fn menuitem(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("menuitem", properties, children)
    }

    /// Creates a `multicol` element.
    pub fn multicol(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("multicol", properties, children)
    }

    /// Creates a `nextid` element.
    pub fn nextid(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("nextid", properties, children)
    }

    /// Creates a `nobr` element.
    pub fn nobr(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("nobr", properties, children)
    }

    /// Creates a `noembed` element.
    pub fn noembed(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("noembed", properties, children)
    }

    /// Creates a `noframes` element.
    pub fn noframes(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("noframes", properties, children)
    }

    /// Creates a `param` element.
    pub fn param(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("param", properties, children)
    }

    /// Creates a `plaintext` element.
    pub fn plaintext(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("plaintext", properties, children)
    }

    /// Creates a `rb` element.
    pub fn rb(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("rb", properties, children)
    }

    /// Creates a `rtc` element.
    pub fn rtc(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("rtc", properties, children)
    }

    /// Creates a `spacer` element.
    pub fn spacer(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("spacer", properties, children)
    }

    /// Creates a `strike` element.
    pub fn strike(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("strike", properties, children)
    }

    /// Creates a `tt` element.
    pub fn tt(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("tt", properties, children)
    }

    /// Creates a `xmp` element.
    pub fn xmp(
        &self,
        properties: &ProgrammaticViewProperties,
        children: &[ProgrammaticViewChild],
    ) -> Result<ProgrammaticViewChild, JsValue> {
        self.tag("xmp", properties, children)
    }
}
