#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import ts from "typescript";
import {
  parameterDocumentation,
  symbolDocumentation,
  typeDocumentation,
} from "../../shared/typescript-documentation.mjs";

const root = path.resolve(import.meta.dirname, "../../..");
const namespacePath = path.join(root, "@types/namespace.d.ts");
const outputPath = path.join(root, "integrations/scala/NG_NAMESPACE_PARITY.md");
const check = process.argv.includes("--check");

const namespace = extractNamespace(namespacePath);
const output = renderParity(namespace.types, namespace.methods);

if (check) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";

  if (current !== output) {
    console.error(
      "Scala namespace parity artifact is stale. Run `make -C integrations/scala generate`.",
    );
    process.exit(1);
  }

  console.log(
    `Scala namespace parity artifact is fresh for ${namespace.types.length} ng types and ${namespace.methods.length} public methods.`,
  );
} else {
  fs.writeFileSync(outputPath, output);
  console.log(
    `Wrote ${path.relative(root, outputPath)} with ${namespace.types.length} ng types and ${namespace.methods.length} public methods.`,
  );
}

function extractNamespace(sourcePath) {
  const program = ts.createProgram([sourcePath], {
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.Latest,
  });
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(sourcePath);
  const types = [];
  const methods = [];
  const seenMethods = new Set();

  if (!sourceFile) throw new Error(`Unable to load ${sourcePath}`);

  function visit(node, inNgNamespace = false) {
    if (ts.isModuleDeclaration(node)) {
      const nextInNgNamespace =
        inNgNamespace ||
        (ts.isIdentifier(node.name) && node.name.escapedText.toString() === "ng");

      if (node.body) visit(node.body, nextInNgNamespace);
      return;
    }

    if (inNgNamespace && ts.isTypeAliasDeclaration(node)) {
      const type = checker.getTypeFromTypeNode(node.type);
      types.push({
        documentation: typeDocumentation(checker, node, type),
        name: node.name.escapedText.toString(),
      });
      collectMethods(
        checker,
        node.name.escapedText.toString(),
        type,
        methods,
        seenMethods,
      );
      return;
    }

    ts.forEachChild(node, (child) => visit(child, inNgNamespace));
  }

  visit(sourceFile);
  return { methods, types };
}

function collectMethods(checker, typeName, type, methods, seenMethods) {
  for (const property of checker.getPropertiesOfType(type)) {
    const declaration = property.valueDeclaration ?? property.declarations?.[0];
    if (!isAngularTsDeclaration(declaration) || property.name.startsWith("_")) continue;

    const signatures = checker.getSignaturesOfType(
      checker.getTypeOfSymbolAtLocation(property, declaration),
      ts.SignatureKind.Call,
    );
    if (signatures.length === 0) continue;

    const key = `${declaration.getSourceFile().fileName}:${declaration.pos}`;
    if (seenMethods.has(key)) continue;
    seenMethods.add(key);

    const signature = signatures.reduce((selected, candidate) =>
      !selected || candidate.parameters.length > selected.parameters.length
        ? candidate
        : selected,
    );
    methods.push({
      documentation: symbolDocumentation(
        checker,
        property,
        `Invokes the ${property.name} member of ng.${typeName}.`,
      ),
      name: `${typeName}.${property.name}`,
      parameters: signature.parameters.map((parameter) => {
        const parameterDeclaration =
          parameter.valueDeclaration ?? parameter.declarations?.[0] ?? declaration;

        return {
          documentation: parameterDocumentation(checker, parameter),
          name: parameter.name,
          type: publicTypeName(
            checker.typeToString(
              checker.getTypeOfSymbolAtLocation(parameter, parameterDeclaration),
              parameterDeclaration,
              ts.TypeFormatFlags.NoTruncation |
                ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope,
            ),
          ),
        };
      }),
    });
  }
}

function isAngularTsDeclaration(declaration) {
  return Boolean(
    declaration &&
      declaration
        .getSourceFile()
        .fileName.replaceAll("\\", "/")
        .includes("/@types/"),
  );
}

function renderParity(typeNames, methods) {
  const lines = [
    "# AngularTS Scala.js Namespace Parity",
    "",
    "Generated by `integrations/scala/tool/generate_ng_namespace_parity.mjs`.",
    "The source of truth is `@types/namespace.d.ts` public `ng` type aliases.",
    "",
    "Statuses:",
    "",
    "- `manual`: handwritten Scala facade exists.",
    "- `generated`: generated Scala facade exists.",
    "- `planned`: tracked but not implemented yet.",
    "- `unsupported`: intentionally unavailable with a reason in the roadmap.",
    "",
    "| ng type | AngularTS contract | Scala.js status |",
    "| --- | --- | --- |",
  ];

  const manual = new Set([
    "Angular",
    "AnchorScrollService",
    "AngularElementDefinition",
    "AngularElementModuleOptions",
    "AngularElementOptions",
    "AnimateService",
    "AnimationContext",
    "AnimationHandle",
    "AnimationLifecycleCallback",
    "AnimationOptions",
    "AnimationPhase",
    "AnimationPreset",
    "AnimationPresetHandler",
    "AnimationResult",
    "AppComponentOptions",
    "AnnotatedDirectiveFactory",
    "AnnotatedFactory",
    "AriaConfig",
    "AriaService",
    "ClassMap",
    "ClassValue",
    "CompileService",
    "Component",
    "ConnectionConfig",
    "ConnectionEvent",
    "Controller",
    "ControllerConstructor",
    "ControllerService",
    "CookieOptions",
    "CookieService",
    "CookieStoreOptions",
    "Directive",
    "DirectiveFactory",
    "DirectiveRestrict",
    "ElementScopeOptions",
    "EntityClass",
    "EntryFilterItem",
    "ErrorHandlingConfig",
    "EventDeliveryPolicy",
    "EventDeliveryPolicyContext",
    "EventBusService",
    "ExceptionHandlerService",
    "Expression",
    "FilterFactory",
    "FilterFn",
    "FilterService",
    "CurrencyFilterOptions",
    "HtmlCanvasConfig",
    "HttpMethod",
    "HttpParamSerializerService",
    "HttpDefaults",
    "HttpResponse",
    "HttpResponseStatus",
    "HttpService",
    "InjectorService",
    "InterpolateConfig",
    "InterpolationFunction",
    "InterpolateService",
    "Injectable",
    "ListenerFn",
    "LocationService",
    "LogService",
    "Machine",
    "MachineEventNamesOf",
    "MachineEventMap",
    "MachineEventsOf",
    "MachineEventTransitionConfig",
    "MachineEventTransitionContext",
    "MachineEventTransitionGuard",
    "MachineEventTransitionHook",
    "MachineEventTransitionUpdate",
    "MachineHooks",
    "MachineState",
    "MachineStateHooks",
    "MachineStatesOf",
    "MachineNoEvents",
    "MachineSendResult",
    "MachineSendStatus",
    "MachineService",
    "MachineSnapshot",
    "MachineStateConfig",
    "MachineStateDefinition",
    "MachineStateMap",
    "MachineStateTransitionMap",
    "NgModule",
    "NgModelController",
    "ParseService",
    "LinkFn",
    "EventBusConfig",
    "RealtimeProtocolEventDetail",
    "RealtimeProtocolMessage",
    "HttpRequestConfig",
    "HttpRequestOptions",
    "RestBackend",
    "RestCachePolicy",
    "RestCachePolicyContext",
    "RestCacheStore",
    "RestCacheStrategy",
    "RestFactory",
    "RestOptions",
    "RestRequest",
    "RestResponse",
    "RestRevalidateEvent",
    "RestService",
    "CachedRestBackendOptions",
    "RouterConfig",
    "RouterModuleDeclaration",
    "SceDelegateService",
    "SceService",
    "Scope",
    "ScopeEvent",
    "ScopeElement",
    "ScopeElementConstructor",
    "ServiceWorkerConfig",
    "ServiceWorkerErrorCode",
    "ServiceWorkerMessageEvent",
    "ServiceWorkerMessageTarget",
    "ServiceWorkerRegistrationState",
    "ServiceWorkerRequestOptions",
    "ServiceWorkerService",
    "ServiceWorkerUpdateState",
    "SseConfig",
    "SseConnection",
    "SseService",
    "StateDeclaration",
    "StateNavigationPolicyDeclaration",
    "StatePolicyDeclaration",
    "StateRetentionEvictionContext",
    "StateRetentionEvictionMode",
    "StateRetentionEvictionPolicy",
    "StateRetentionKeyPolicy",
    "StateRetentionMode",
    "StateRetentionPauseMode",
    "StateRetentionPolicyContext",
    "StateRetentionPolicyDeclaration",
    "StorageBackend",
    "StorageType",
    "StreamService",
    "SwapMode",
    "TemplateCacheService",
    "TemplateRequestService",
    "TranscludeFn",
    "Transition",
    "TransitionsService",
    "TransitionsService",
    "RouteContract",
    "RouteMap",
    "StateService",
    "ViewService",
    "WebSocketConfig",
    "WebSocketConnection",
    "WebSocketService",
    "WebComponentContext",
    "WebComponentInput",
    "WebComponentInputConfig",
    "WebComponentInputs",
    "WebComponentService",
    "WebTransportBufferInput",
    "WebTransportConfig",
    "WebTransportConnection",
    "WebTransportDatagramEvent",
    "WebTransportReconnectEvent",
    "WebTransportRetryDelay",
    "WebTransportService",
    "Workflow",
    "WorkflowCommand",
    "WorkflowCommandContract",
    "WorkflowCommandContext",
    "WorkflowCommandDefinition",
    "WorkflowContract",
    "WorkflowResult",
    "WorkflowService",
    "WorkflowSnapshot",
    "WorkflowSupervisor",
    "WorkflowSupervisorConfig",
    "WorkflowSupervisorPersistenceConfig",
    "WorkflowSupervisorPersistence",
    "WorkflowSupervisorSnapshot",
    "WorkerConfig",
    "WorkerError",
    "WorkerHandle",
    "WorkerService",
    "WorkerStatus",
    "WasmAbiExports",
    "WasmInstantiationResult",
    "WasmOptions",
    "WasmScope",
    "WasmScopeAbi",
    "WasmScopeAbiImportObject",
    "WasmScopeAbiImports",
    "WasmScopeBindingOptions",
    "WasmScopeOptions",
    "WasmScopeReference",
    "WasmScopeUpdate",
    "WasmScopeWatchOptions",
    "WasmService",
    "Validator",
  ]);

  for (const { documentation, name: typeName } of typeNames) {
    const status = manual.has(typeName) ? "manual" : "planned";
    lines.push(
      `| \`${typeName}\` | ${documentation.replaceAll("|", "\\|")} | ${status} |`,
    );
  }

  lines.push(
    "",
    "## Public Method Documentation",
    "",
    "Descriptions, parameter names, and parameter types are generated from the same TypeScript declarations as the Scala.js parity inventory.",
    "",
    "| ng member | Description | Parameters |",
    "| --- | --- | --- |",
  );

  for (const method of methods.sort((left, right) => left.name.localeCompare(right.name))) {
    const parameters =
      method.parameters.length === 0
        ? "None"
        : method.parameters
            .map(
              (parameter) =>
                `\`${escapeMarkdown(parameter.name)}: ${escapeMarkdown(parameter.type)}\` - ${escapeMarkdown(parameter.documentation)}`,
            )
            .join("<br>");
    lines.push(
      `| \`${escapeMarkdown(method.name)}\` | ${escapeMarkdown(method.documentation)} | ${parameters} |`,
    );
  }

  return `${lines.join("\n")}\n`;
}

function escapeMarkdown(value) {
  return value.replaceAll("|", "\\|").replaceAll("`", "\\`");
}

function publicTypeName(value) {
  return value.replace(/import\("[^"]+"\)\./gu, "");
}
