#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import ts from "typescript";

const root = path.resolve(import.meta.dirname, "../../..");
const namespacePath = path.join(root, "@types/namespace.d.ts");
const outputPath = path.join(root, "integrations/scala/NG_NAMESPACE_PARITY.md");
const check = process.argv.includes("--check");

const namespace = fs.readFileSync(namespacePath, "utf8");
const types = extractNamespaceTypes(namespace);
const output = renderParity(types);

if (check) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";

  if (current !== output) {
    console.error(
      "Scala namespace parity artifact is stale. Run `make -C integrations/scala generate`.",
    );
    process.exit(1);
  }

  console.log(`Scala namespace parity artifact is fresh for ${types.length} ng types.`);
} else {
  fs.writeFileSync(outputPath, output);
  console.log(`Wrote ${path.relative(root, outputPath)} with ${types.length} ng types.`);
}

function extractNamespaceTypes(sourceText) {
  const sourceFile = ts.createSourceFile(
    namespacePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const types = [];

  function visit(node, inNgNamespace = false) {
    if (ts.isModuleDeclaration(node)) {
      const nextInNgNamespace =
        inNgNamespace ||
        (ts.isIdentifier(node.name) && node.name.escapedText.toString() === "ng");

      if (node.body) visit(node.body, nextInNgNamespace);
      return;
    }

    if (inNgNamespace && ts.isTypeAliasDeclaration(node)) {
      types.push(node.name.escapedText);
      return;
    }

    ts.forEachChild(node, (child) => visit(child, inNgNamespace));
  }

  visit(sourceFile);
  return types;
}

function renderParity(typeNames) {
  const lines = [
    "# AngularTS Scala.js Namespace Parity",
    "",
    "Generated by `integrations/scala/tool/generate_ng_namespace_parity.mjs`.",
    "The source of truth is `@types/namespace.d.ts` public `ng` type aliases.",
    "",
    "Statuses:",
    "",
    "- `manual`: handwritten Scala facade exists.",
    "- `generated`: generated Scala facade exists.",
    "- `planned`: tracked but not implemented yet.",
    "- `unsupported`: intentionally unavailable with a reason in the roadmap.",
    "",
    "| ng type | Scala.js status |",
    "| --- | --- |",
  ];

  const manual = new Set([
    "Angular",
    "AnchorScrollService",
    "AngularElementDefinition",
    "AngularElementModuleOptions",
    "AngularElementOptions",
    "AnimateService",
    "AnimationContext",
    "AnimationHandle",
    "AnimationLifecycleCallback",
    "AnimationOptions",
    "AnimationPhase",
    "AnimationPreset",
    "AnimationPresetHandler",
    "AnimationResult",
    "AppComponentOptions",
    "AnnotatedDirectiveFactory",
    "AnnotatedFactory",
    "AriaConfig",
    "AriaService",
    "ClassMap",
    "ClassValue",
    "CompileService",
    "Component",
    "ConnectionConfig",
    "ConnectionEvent",
    "Controller",
    "ControllerConstructor",
    "ControllerService",
    "CookieOptions",
    "CookieService",
    "CookieStoreOptions",
    "Directive",
    "DirectiveFactory",
    "DirectiveRestrict",
    "ElementScopeOptions",
    "EntityClass",
    "EntryFilterItem",
    "ErrorHandlingConfig",
    "EventDeliveryPolicy",
    "EventDeliveryPolicyContext",
    "EventBusService",
    "ExceptionHandlerService",
    "Expression",
    "FilterFactory",
    "FilterFn",
    "FilterService",
    "CurrencyFilterOptions",
    "HtmlCanvasConfig",
    "HttpMethod",
    "HttpParamSerializerService",
    "HttpDefaults",
    "HttpResponse",
    "HttpResponseStatus",
    "HttpService",
    "InjectorService",
    "InterpolateConfig",
    "InterpolationFunction",
    "InterpolateService",
    "Injectable",
    "ListenerFn",
    "LocationService",
    "LogService",
    "Machine",
    "MachineEventNamesOf",
    "MachineEventMap",
    "MachineEventsOf",
    "MachineEventTransitionConfig",
    "MachineEventTransitionContext",
    "MachineEventTransitionGuard",
    "MachineEventTransitionHook",
    "MachineEventTransitionUpdate",
    "MachineHooks",
    "MachineState",
    "MachineStateHooks",
    "MachineStatesOf",
    "MachineNoEvents",
    "MachineSendResult",
    "MachineSendStatus",
    "MachineService",
    "MachineSnapshot",
    "MachineStateConfig",
    "MachineStateDefinition",
    "MachineStateMap",
    "MachineStateTransitionMap",
    "NgModule",
    "NgModelController",
    "ParseService",
    "LinkFn",
    "EventBusConfig",
    "RealtimeProtocolEventDetail",
    "RealtimeProtocolMessage",
    "HttpRequestConfig",
    "HttpRequestOptions",
    "RestBackend",
    "RestCachePolicy",
    "RestCachePolicyContext",
    "RestCacheStore",
    "RestCacheStrategy",
    "RestFactory",
    "RestOptions",
    "RestRequest",
    "RestResponse",
    "RestRevalidateEvent",
    "RestService",
    "CachedRestBackendOptions",
    "RouterConfig",
    "RouterModuleDeclaration",
    "SceDelegateService",
    "SceService",
    "Scope",
    "ScopeEvent",
    "ScopeElement",
    "ScopeElementConstructor",
    "ServiceWorkerConfig",
    "ServiceWorkerErrorCode",
    "ServiceWorkerMessageEvent",
    "ServiceWorkerMessageTarget",
    "ServiceWorkerRegistrationState",
    "ServiceWorkerRequestOptions",
    "ServiceWorkerService",
    "ServiceWorkerUpdateState",
    "SseConfig",
    "SseConnection",
    "SseService",
    "StateDeclaration",
    "StateNavigationPolicyDeclaration",
    "StatePolicyDeclaration",
    "StateRetentionEvictionContext",
    "StateRetentionEvictionMode",
    "StateRetentionEvictionPolicy",
    "StateRetentionKeyPolicy",
    "StateRetentionMode",
    "StateRetentionPauseMode",
    "StateRetentionPolicyContext",
    "StateRetentionPolicyDeclaration",
    "StorageBackend",
    "StorageType",
    "StreamService",
    "SwapMode",
    "TemplateCacheService",
    "TemplateRequestService",
    "TranscludeFn",
    "Transition",
    "TransitionsService",
    "TransitionsService",
    "RouteContract",
    "RouteMap",
    "StateService",
    "ViewService",
    "WebSocketConfig",
    "WebSocketConnection",
    "WebSocketService",
    "WebComponentContext",
    "WebComponentInput",
    "WebComponentInputConfig",
    "WebComponentInputs",
    "WebComponentService",
    "WebTransportBufferInput",
    "WebTransportConfig",
    "WebTransportConnection",
    "WebTransportDatagramEvent",
    "WebTransportReconnectEvent",
    "WebTransportRetryDelay",
    "WebTransportService",
    "Workflow",
    "WorkflowCommand",
    "WorkflowCommandContract",
    "WorkflowCommandContext",
    "WorkflowCommandDefinition",
    "WorkflowContract",
    "WorkflowResult",
    "WorkflowService",
    "WorkflowSnapshot",
    "WorkflowSupervisor",
    "WorkflowSupervisorConfig",
    "WorkflowSupervisorPersistenceConfig",
    "WorkflowSupervisorPersistence",
    "WorkflowSupervisorSnapshot",
    "WorkerConfig",
    "WorkerError",
    "WorkerHandle",
    "WorkerService",
    "WorkerStatus",
    "WasmAbiExports",
    "WasmInstantiationResult",
    "WasmOptions",
    "WasmScope",
    "WasmScopeAbi",
    "WasmScopeAbiImportObject",
    "WasmScopeAbiImports",
    "WasmScopeBindingOptions",
    "WasmScopeOptions",
    "WasmScopeReference",
    "WasmScopeUpdate",
    "WasmScopeWatchOptions",
    "WasmService",
    "Validator",
  ]);

  for (const typeName of typeNames) {
    const status = manual.has(typeName) ? "manual" : "planned";
    lines.push(`| \`${typeName}\` | ${status} |`);
  }

  return `${lines.join("\n")}\n`;
}
