#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import ts from "typescript";

const root = path.resolve(import.meta.dirname, "../../..");
const namespacePath = path.join(root, "@types/namespace.d.ts");
const outputPath = path.join(root, "integrations/scala/NG_NAMESPACE_PARITY.md");
const check = process.argv.includes("--check");

const namespace = fs.readFileSync(namespacePath, "utf8");
const types = extractNamespaceTypes(namespace);
const output = renderParity(types);

if (check) {
  const current = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, "utf8")
    : "";

  if (current !== output) {
    console.error(
      "Scala namespace parity artifact is stale. Run `make -C integrations/scala generate`.",
    );
    process.exit(1);
  }

  console.log(`Scala namespace parity artifact is fresh for ${types.length} ng types.`);
} else {
  fs.writeFileSync(outputPath, output);
  console.log(`Wrote ${path.relative(root, outputPath)} with ${types.length} ng types.`);
}

function extractNamespaceTypes(sourceText) {
  const sourceFile = ts.createSourceFile(
    namespacePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  );
  const types = [];

  function visit(node, inNgNamespace = false) {
    if (ts.isModuleDeclaration(node)) {
      const nextInNgNamespace =
        inNgNamespace ||
        (ts.isIdentifier(node.name) && node.name.escapedText.toString() === "ng");

      if (node.body) visit(node.body, nextInNgNamespace);
      return;
    }

    if (inNgNamespace && ts.isTypeAliasDeclaration(node)) {
      types.push(node.name.escapedText.toString());
      return;
    }

    ts.forEachChild(node, (child) => visit(child, inNgNamespace));
  }

  visit(sourceFile);
  return types;
}

function renderParity(typeNames) {
  const lines = [
    "# AngularTS Scala.js Namespace Parity",
    "",
    "Generated by `integrations/scala/tool/generate_ng_namespace_parity.mjs`.",
    "The source of truth is `@types/namespace.d.ts` public `ng` type aliases.",
    "",
    "Statuses:",
    "",
    "- `manual`: handwritten Scala facade exists.",
    "- `generated`: generated Scala facade exists.",
    "- `planned`: tracked but not implemented yet.",
    "- `unsupported`: intentionally unavailable with a reason in the roadmap.",
    "",
    "| ng type | Scala.js status |",
    "| --- | --- |",
  ];

  const manual = new Set([
    "Angular",
    "AngularService",
    "AnchorScrollService",
    "AngularElementDefinition",
    "AngularElementModuleOptions",
    "AngularElementOptions",
    "AnimateService",
    "AnimationContext",
    "AnimationHandle",
    "AnimationLifecycleCallback",
    "AnimationOptions",
    "AnimationPhase",
    "AnimationPreset",
    "AnimationPresetHandler",
    "AnimationResult",
    "AppComponentOptions",
    "AnnotatedDirectiveFactory",
    "AnnotatedFactory",
    "AriaConfig",
    "AriaService",
    "ClassMap",
    "ClassValue",
    "CompileService",
    "Component",
    "ConnectionConfig",
    "ConnectionEvent",
    "Controller",
    "ControllerConstructor",
    "ControllerService",
    "CookieOptions",
    "CookieService",
    "CookieStoreOptions",
    "Directive",
    "DirectiveFactory",
    "DirectiveRestrict",
    "DocumentService",
    "ElementService",
    "ElementScopeOptions",
    "EntityClass",
    "EntryFilterItem",
    "ErrorHandlingConfig",
    "EventDeliveryDecisionType",
    "EventDeliveryPolicy",
    "EventDeliveryPolicyContext",
    "EventDeliveryPolicyDecision",
    "EventBusService",
    "ExceptionHandlerService",
    "Expression",
    "DateFilterOptions",
    "FilterFactory",
    "FilterFn",
    "FilterService",
    "CurrencyFilterOptions",
    "NumberFilterOptions",
    "HtmlCanvasConfig",
    "HttpMethod",
    "HttpParamSerializerService",
    "HttpPromise",
    "HttpProviderDefaults",
    "HttpResponse",
    "HttpResponseStatus",
    "HttpService",
    "InjectorService",
    "InterpolateConfig",
    "InterpolationFunction",
    "InterpolateService",
    "Injectable",
    "ListenerFn",
    "LocationService",
    "LogService",
    "Machine",
    "MachineConfig",
    "MachineEventMap",
    "MachineGuard",
    "MachineHooks",
    "MachineMode",
    "MachineModeHooks",
    "MachineNoEvents",
    "MachineService",
    "MachineSnapshot",
    "MachineTransition",
    "MachineTransitionContext",
    "MachineTransitionDefinition",
    "MachineTransitionDescriptor",
    "MachineTransitionHook",
    "MachineTransitionMap",
    "MachineTransitionResult",
    "NgModule",
    "NgModelController",
    "NativeAnimationOptions",
    "NativeWebTransport",
    "ParseService",
    "PublicLinkFn",
    "PubSubConfig",
    "PubSubService",
    "RealtimeProtocolEventDetail",
    "RealtimeProtocolMessage",
    "RequestConfig",
    "RequestShortcutConfig",
    "RelativeTimeFilterOptions",
    "RestBackend",
    "RestCachePolicy",
    "RestCachePolicyContext",
    "RestCachePolicyDecision",
    "RestCacheStore",
    "RestCacheStrategy",
    "RestDefinition",
    "RestFactory",
    "RestOptions",
    "RestRequest",
    "RestResponse",
    "RestRevalidateEvent",
    "RestService",
    "CachedRestBackendOptions",
    "RootElementService",
    "RootScopeService",
    "RouterConfig",
    "RouterModuleDeclaration",
    "SceDelegateService",
    "SceService",
    "Scope",
    "ScopeEvent",
    "ScopeService",
    "ScopeElement",
    "ScopeElementConstructor",
    "ServiceWorkerConfig",
    "ServiceWorkerMessageClient",
    "ServiceWorkerMessageClientError",
    "ServiceWorkerMessageClientErrorCode",
    "ServiceWorkerMessageClientOptions",
    "ServiceWorkerMessageClientRequestOptions",
    "ServiceWorkerMessageEvent",
    "ServiceWorkerMessageRequest",
    "ServiceWorkerMessageResponse",
    "ServiceWorkerMessageTarget",
    "ServiceWorkerRegistrationState",
    "ServiceWorkerService",
    "ServiceWorkerSupport",
    "ServiceWorkerUpdateState",
    "SseConfig",
    "SseConnection",
    "SseProtocolEventDetail",
    "SseProtocolMessage",
    "SseService",
    "StateDeclaration",
    "StateNavigationPolicyDeclaration",
    "StatePolicyDeclaration",
    "StateRetentionEvictionContext",
    "StateRetentionEvictionMode",
    "StateRetentionEvictionPolicy",
    "StateRetentionKeyPolicy",
    "StateRetentionMode",
    "StateRetentionPauseMode",
    "StateRetentionPolicyContext",
    "StateRetentionPolicyDeclaration",
    "StateResolveArray",
    "StateResolveObject",
    "StorageBackend",
    "StorageType",
    "StreamService",
    "SwapModeType",
    "TemplateCacheService",
    "TemplateRequestService",
    "TranscludeFn",
    "Transition",
    "TransitionService",
    "TransitionsService",
    "TypedRouteDeclaration",
    "TypedRouteMap",
    "TypedRouteName",
    "TypedRouteParams",
    "TypedRouteResolves",
    "TypedStateService",
    "TypedTransition",
    "ViewService",
    "WebSocketConfig",
    "WebSocketConnection",
    "WebSocketService",
    "WebComponentContext",
    "WebComponentInput",
    "WebComponentInputConfig",
    "WebComponentInputs",
    "WebComponentService",
    "WebTransportBufferInput",
    "WebTransportCertificateHash",
    "WebTransportConfig",
    "WebTransportConnection",
    "WebTransportDatagramEvent",
    "WebTransportOptions",
    "WebTransportReconnectEvent",
    "WebTransportRetryDelay",
    "WebTransportService",
    "WindowService",
    "Workflow",
    "WorkflowCommand",
    "WorkflowCommandContext",
    "WorkflowCommandMap",
    "WorkflowCommandOptions",
    "WorkflowCommandResult",
    "WorkflowConcurrencyPolicy",
    "WorkflowConfig",
    "WorkflowDiagnostic",
    "WorkflowHistoryEntry",
    "WorkflowMode",
    "WorkflowNoCommands",
    "WorkflowService",
    "WorkflowSnapshot",
    "WorkflowSnapshotMigration",
    "WorkflowStateEngine",
    "WorkflowStateEngineContext",
    "WorkflowStateEngineFactory",
    "WorkflowStatus",
    "WorkflowSupervisor",
    "WorkflowSupervisorConfig",
    "WorkflowSupervisorDiagnostic",
    "WorkflowSupervisorIndexedDbPersistenceConfig",
    "WorkflowSupervisorPersistence",
    "WorkflowSupervisorPersistencePolicy",
    "WorkflowSupervisorRecoveryPolicy",
    "WorkflowSupervisorSnapshot",
    "WorkflowSupervisorStatus",
    "WorkflowWorkerClient",
    "WorkflowWorkerHost",
    "WorkflowWorkerHostConfig",
    "WorkflowWorkerMessage",
    "WorkflowWorkerRequest",
    "WorkflowWorkerRequestOperation",
    "WorkflowWorkerResponse",
    "WorkflowWorkerSnapshotMessage",
    "WorkerConfig",
    "WorkerConnection",
    "WorkerService",
    "WasmAbiExports",
    "WasmInstantiationResult",
    "WasmOptions",
    "WasmScope",
    "WasmScopeAbi",
    "WasmScopeAbiImportObject",
    "WasmScopeAbiImports",
    "WasmScopeBindingOptions",
    "WasmScopeOptions",
    "WasmScopeReference",
    "WasmScopeUpdate",
    "WasmScopeWatchOptions",
    "WasmService",
    "Validator",
  ]);

  for (const typeName of typeNames) {
    const status = manual.has(typeName) ? "manual" : "planned";
    lines.push(`| \`${typeName}\` | ${status} |`);
  }

  return `${lines.join("\n")}\n`;
}
