name = "angular_ts"
version = "0.0.1"
target = "javascript"
description = "Official Gleam facade for authoring AngularTS applications."
licences = ["MIT"]
repository = { type = "github", user = "angular-wave", repo = "angular.ts" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
typescript_declarations = true
