import { Angular } from "./angular.ts";
import type {
  AngularRuntimeConstructorInput,
  AngularRuntimeOptions,
  RuntimeModule,
} from "./angular-runtime.ts";
import type {
  AngularComposition,
  DirectiveRegistration,
  DirectiveRegistrations,
  FilterRegistration,
  FilterRegistrations,
  ProviderRegistration,
  ServiceRegistration,
  ServiceRegistrations,
} from "./runtime/index.ts";
import type {
  AfterRenderCallback,
  AfterRenderOptions,
} from "./core/render/after-render.ts";
import type {
  Policy,
  PolicyContext,
  PolicyDecision,
} from "./core/policy/policy.ts";
import type {
  Machine,
  MachineContract,
  MachineConfig,
  MachineService,
  MachineSendResult,
  MachineSendStatus,
  MachineSnapshot,
} from "./services/machine/machine.ts";
import type {
  Workflow,
  WorkflowContract,
  WorkflowCommand,
  WorkflowCommandContract,
  WorkflowCommandContext,
  WorkflowCommandDefinition,
  WorkflowResult,
  WorkflowService,
  WorkflowSnapshot,
  WorkflowSupervisor,
  WorkflowSupervisorConfig,
  WorkflowSupervisorSnapshot,
} from "./services/workflow/workflow.ts";

/**
 * Default browser entry point.
 */
export const angular = new Angular();

export { AngularRuntime, createAngular } from "./runtime/index.ts";
export { afterRender, queueAfterRender } from "./core/render/after-render.ts";
export {
  a,
  abbr,
  acronym,
  address,
  applet,
  area,
  article,
  aside,
  attrs,
  audio,
  b,
  base,
  basefont,
  bdi,
  bdo,
  bgsound,
  big,
  blink,
  blockquote,
  body,
  br,
  button,
  canvas,
  caption,
  center,
  cite,
  code,
  col,
  colgroup,
  data,
  datalist,
  dd,
  del,
  details,
  dfn,
  dialog,
  dir,
  div,
  dl,
  dt,
  each,
  em,
  embed,
  event,
  fieldset,
  figcaption,
  figure,
  font,
  footer,
  form,
  frame,
  frameset,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  head,
  header,
  hgroup,
  hr,
  html,
  i,
  iframe,
  img,
  input,
  ins,
  isindex,
  kbd,
  keygen,
  label,
  legend,
  li,
  link,
  listing,
  main,
  map,
  mark,
  marquee,
  menu,
  menuitem,
  meta,
  meter,
  multicol,
  nav,
  nextid,
  nobr,
  noembed,
  noframes,
  noscript,
  object,
  ol,
  optgroup,
  option,
  output,
  p,
  param,
  picture,
  plaintext,
  pre,
  progress,
  props,
  q,
  rb,
  rp,
  rt,
  rtc,
  ruby,
  s,
  samp,
  script,
  search,
  section,
  select,
  slot,
  small,
  source,
  spacer,
  span,
  strike,
  strong,
  style,
  sub,
  summary,
  sup,
  table,
  tag,
  tagNS,
  tags,
  tbody,
  td,
  template,
  textarea,
  tfoot,
  th,
  thead,
  time,
  title,
  tr,
  track,
  tt,
  u,
  ul,
  varTag,
  video,
  wbr,
  xmp,
} from "./core/compile/programmatic-view.ts";
export { defineWorkflow } from "./services/workflow/workflow.ts";
export type { GeolocationValue } from "./directive/geolocation/geolocation.ts";
export type {
  ProgrammaticViewProperties,
  ProgrammaticViewPropertyValue,
  ProgrammaticViewTag,
  ProgrammaticViewTags,
  ProgrammaticKeyedView,
  ProgrammaticViewAttributeValue,
  ProgrammaticViewAttributes,
  ProgrammaticViewLiteralProperties,
} from "./core/compile/programmatic-view.ts";
export type {
  ProgrammaticView,
  ProgrammaticViewChild,
  ProgrammaticViewContext,
  ProgrammaticViewPrimitive,
  ComponentDefinition,
  ProgrammaticViewReader,
} from "./interface.ts";

export type {
  AfterRenderCallback,
  AfterRenderOptions,
  AngularRuntimeConstructorInput,
  AngularRuntimeOptions,
  RuntimeModule,
  AngularComposition,
  DirectiveRegistration,
  DirectiveRegistrations,
  FilterRegistration,
  FilterRegistrations,
  Machine,
  MachineContract,
  MachineConfig,
  MachineService,
  MachineSendResult,
  MachineSendStatus,
  MachineSnapshot,
  Policy,
  PolicyContext,
  PolicyDecision,
  ProviderRegistration,
  ServiceRegistration,
  ServiceRegistrations,
  Workflow,
  WorkflowContract,
  WorkflowCommand,
  WorkflowCommandContract,
  WorkflowCommandContext,
  WorkflowCommandDefinition,
  WorkflowResult,
  WorkflowService,
  WorkflowSnapshot,
  WorkflowSupervisor,
  WorkflowSupervisorConfig,
  WorkflowSupervisorSnapshot,
};
